### PR TITLE
Fix Moment.js locale defined by inline 'moment' script

### PR DESCRIPTION
**Pull request by noisysocks**
Fixes a few misconfigurations in the Moment.js locale set up by the inline 'moment' script.

- `parentLocale` will not work when using `updateLocale()`. Use `defineLocale()` instead.
- `doy` must be provided when setting `dow`.
- `meridiem` can be set using the info we have in `WP_Locale`.
- `LTS`, `L` and `LLLL` must be provided when setting `longDateFormat`.

Some of the fixes here are borrowed from https://github.com/WordPress/gutenberg/pull/39670 which fixes the call to `moment.updateLocale` made by `@wordpress/date`.

An alternative to this PR is to remove the inline script from `moment` altogether. It was added in https://core.trac.wordpress.org/changeset/44262 without any note. I believe it was a mistake. It's not necessary since `@wordpress/date` will also call `moment.updateLocale` / `moment.defineLocale` and `@wordpress/date` is the only part of WP Admin that relies on moment localisation. It's possible that third party plugins now rely on this, though. What do you think @hellofromtonya @SergeyBiryukov?

Trac ticket:
https://core.trac.wordpress.org/ticket/51142
https://core.trac.wordpress.org/ticket/52695

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by yoancutillas** [comment]
Hello, thank you for providing this fix.
Not sure why it was blocked though...

However, I recently tried your fix and found out that **one more thing needs to be fixed:** 
In https://github.com/noisysocks/wordpress-develop/blob/fix/moment-locale/src/wp-includes/script-loader.php#L175-L180
```
'longDateFormat' => array(
  'LT'   => get_option( 'time_format', __( 'g:i a' ) ),
  'LTS'  => null,
  'L'    => null,
  'LL'   => get_option( 'date_format', __( 'F j, Y' ) ),
  'LLL'  => __( 'F j, Y g:i a' ),
  'LLLL' => null,
),
```
The PHP format needs to be converted to the Moment JS format:
```
'longDateFormat' => array(
  'LT'   => wp_convert_php_datetime_format_to_moment_js( get_option( 'time_format', __( 'g:i a' ) ) ),
  'LTS'  => null,
  'L'    => null,
  'LL'   => wp_convert_php_datetime_format_to_moment_js( get_option( 'date_format', __( 'F j, Y' ) ) ),
  'LLL'  => wp_convert_php_datetime_format_to_moment_js( __( 'F j, Y g:i a' ) ),
  'LLLL' => null,
),
```

Where the wp_convert_php_datetime_format_to_moment_js function would be:
```
/**
 * Convert a PHP datetime format to moment JS format
 * @param {string} php_format
 * @returns {string}
 */
function wp_convert_php_datetime_format_to_moment_js( $php_format ) {
	$format_map = array(
		'd' => 'DD',
		'D' => 'ddd',
		'j' => 'D',
		'l' => 'dddd',
		'N' => 'E',
		'w' => 'd',
		'W' => 'W',
		'F' => 'MMMM',
		'm' => 'MM',
		'M' => 'MMM',
		'n' => 'M',
		'o' => 'GGGG',
		'Y' => 'YYYY',
		'y' => 'YY',
		'a' => 'a',
		'A' => 'A',
		'g' => 'h',
		'G' => 'H',
		'h' => 'hh',
		'H' => 'HH',
		'i' => 'mm',
		's' => 'ss',
		'u' => 'X',
		'e' => 'z',
		'O' => 'ZZ',
		'P' => 'Z',
		'T' => 'z',
		'c' => 'YYYY-MM-DD[T]HH:mm:ssZ',
		'r' => 'ddd, DD MMM YYYY HH:mm:ss ZZ',
		'U' => 'X'
	);
	
	$has_backslash = false;
	$moment_js_format = '';
	foreach( str_split( $php_format ) as $char ) {
		if( $char === '\\' && ! $has_backslash ) { $has_backslash = true; continue; }
		$moment_js_format .= $has_backslash || ! isset( $format_map[ $char ] ) ? '[' . $char . ']' : $format_map[ $char ];
		$has_backslash = false;
	}
	
	return $moment_js_format;
}

```

**Comment by noisysocks** [comment]
Thanks @yoancutillas. I'll put the relevant Trac tickets for this patch into the 6.1 milestone so that it doesn't fall off our collective radar again 🙂

**Comment by peterwilsoncc** [comment]
> An alternative to this PR is to remove the inline script from `moment` altogether. It was added in https://core.trac.wordpress.org/changeset/44262 without any note. I believe it was a mistake. It's not necessary since `@wordpress/date` will also call `moment.updateLocale` / `moment.defineLocale` and `@wordpress/date` is the only part of WP Admin that relies on moment localisation. It's possible that third party plugins now rely on this, though.

After four years, it's probably safer to assume that it's used somewhere. 

I can see a few big plugins using [moment as a dependency without wp-date](https://wpdirectory.net/search/01G87WQSSJHEBXM1TTM5SJTF7Y) but I am unable to figure out how to tell if they're using the i18n features. A search for `moment\.` did not help ;)

**Comment by louwie17** [comment]
Hi @noisysocks, just ran across this as I was trying to decipher why the `week.dow` locale setting stopped working in Wordpress 6.0 (works in 5.9).
I was curious if this fix will also address this issue?
Currently when I run `moment().startOf('week');` in 5.9, it adheres to the `start_of_week` setting from Wordpress settings, if I run it in 6.0, it always returns Sunday (unless I run the `updateLocale` script again).

Let me know if I should really be creating a new issue for this, more context can be found here: https://a8c.slack.com/archives/C7U3Y3VMY/p1658140947358049

**Comment by noisysocks** [comment]
Hey @louwie17. Yes. When I run `moment().startOf('week').toString()` in `trunk` I see that it does not respect `start_of_week` but when I run it on this branch it works okay.

**Comment by louwie17** [comment]
> Hey @louwie17. Yes. When I run `moment().startOf('week').toString()` in `trunk` I see that it does not respect `start_of_week` but when I run it on this branch it works okay.

@noisysocks that is good to hear, thanks for checking 👍 it will be great if this could be in the next Wordpress release and/or patch release if there is one.

**Comment by yoancutillas** [comment]
On an additional note, since Wordpress doesn't support ordinal suffixes translation, we are losing its support for momentJS too.
**It means that every locale will have the english ordinal suffixes (-st, -nd, -rd, -th)**, inherited from the only available parentLocale 'en'.**

We could add an "ordinal" parameter definition in the code ([docs](https://momentjs.com/docs/#/customization/ordinal/)), but WP doesn't provides the localized values. And, even if moment-with-locales.js is loaded, our code overrides the locale definition, so with can't get it from momentJS either.

I can't see any solution for that, any idea?

**Review by peterwilsoncc — COMMENTED** [review]
I created a [mini plugin for testing this](https://gist.github.com/peterwilsoncc/b1dd0bfde5c6d0caf8b08da75e88728c).

The long form formatting using the [displaying settings](https://momentjs.com/docs/#/displaying/) in the documentation worked, as they use the correct forms for moment.js

Using the shortcut formats didn't work as expected, as the PHP formatting values differ from those used by momentJS. For example, `LT` literally shows `g:i am` (the am/pm values match in both PHP and Moment).

The console output from the mini plugin in dutch was:

```
Month 2 2nd 02 Feb Februar
Day Week 1 1st Mo Montag
AMPM am AM
Time zone +11:00 +1100
Date Default g:i am 10:39:58 AM 02/13/2023 F j, 2023 j. F 2023 G:i Montag, Februar 13, 2023 10:39 AM
```

I experimented with removing the `longDateFormat` block and the values were somewhat correct. It did show replacement values but the date formats were Americanized (ie, 2/13/2023 rather than 13/2/2023).

I think some conversion of values will be needed per the earlier comment, https://github.com/WordPress/wordpress-develop/pull/2456#issuecomment-1184265048, however it may need some additional work to handle escaping: `\d` will show the literal character `d`.

**Comment by yoancutillas** [comment]
Hi @peterwilsoncc, the provided `wp_convert_php_datetime_format_to_moment_js` function handles escaping: `wp_convert_php_datetime_format_to_moment_js( '\d' );` returns `'[d]'` which is displayed by momentjs as the literal character `d`.

**Comment by peterwilsoncc** [comment]
@yoancutillas Is there any chance you could create a pull request with the example code above and add some unit tests? If you don't have experience writing tests then it's fine if you'd rather not.

**Comment by yoancutillas** [comment]
I am not used to PR and I have no experience with unit tests, but I think I managed to make a PR: https://github.com/WordPress/wordpress-develop/pull/4071

**Pull request closed without merging**
