### PR TITLE
Merge two docblocks to keep code according DRY rule

### PR DESCRIPTION
**Pull request by wojtekn**
In this PR, I propose merging file-level docblock with class-level docblock to avoid repeating information.

Trac ticket:  https://core.trac.wordpress.org/ticket/57099

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by hz-tyfoon** [comment]
Hello @wojtekn , Your PR looks good.
Looks to me, this 👇 one can also be included with the changes. 

https://github.com/WordPress/wordpress-develop/blob/0cb8475c0d07d23893b1d73d755eda5f12024585/tests/phpunit/tests/admin/wpCommunityEvents.php#L2-L18

**Comment by wojtekn** [comment]
Thanks, @hz-tyfoon!. I've included this change in the PR.

**Review by costdev — APPROVED** [review]
Thanks for the PR @wojtekn! LGTM :+1:

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r55337](https://core.trac.wordpress.org/changeset/55337).

**Pull request closed without merging**
