### PR TITLE
Fix wav file not getting uploaded in Gutenberg 

### PR DESCRIPTION
**Pull request by Imran92**
Farther details can be found here https://github.com/Automattic/wp-calypso/issues/93778 .

When we upload the `wav` file [here](https://github.com/Automattic/wp-calypso/issues/93778#issuecomment-2306885584), Chrome and all other browsers identify the `mimetype` of the file to be `audio/wav`, but Firefox, identifies the `mimetype` as `audio/x-wav`.

WordPress core has a default (extensible) set of mime-type that it allows uploading. You can find them here https://github.com/WordPress/wordpress-develop/blob/3b1e57752d5dd737477873b6797e3f8209aec078/src/wp-includes/functions.php#L3392-L3513 . You’ll notice that there is the `audio/wav` mime-type there, but not `audio/x-wav`.
So when Gutenberg tries to check the `mimetype` of the file in Firefox here https://github.com/WordPress/gutenberg/blob/5773ae60ca33bda03f2a35e6707d961b8db3af18/packages/media-utils/src/utils/upload-media.js#L91-L118, it sees that the mime-type (`audio/x-wav`) isn’t one of the allowed ones.
So it throws an error.

Here we are including the `x-wav` mime type.

Before applying this patch -
- Use Firefox browser
- Open a page or a post in Gutenberg editor.
- Try to drag and drop this WAV file in the editor https://tinyurl.com/24tkan96
- You should see an error like below
image

After applying this patch -
- Try to do the same drag-and-drop operation as before
- You should not see an error this time
- Also try the same in Chrome and other browsers, make sure no error is thrown
- Try uploading this file in Media Uploader and make sure no error is thrown
- Try with other wav files and media files too

Trac ticket: https://core.trac.wordpress.org/ticket/61948

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ramonjd** [comment]
Good call @Imran92!

I've opened the equivalent Gutenberg backport here:

- https://github.com/WordPress/gutenberg/pull/66850

**Comment by ramonjd** [comment]
I think maybe this needs a rebase or at least the tests restarted. 👍🏻

**Comment by Imran92** [comment]
> I think maybe this needs a rebase or at least the tests restarted. 👍🏻

Thanks! I synced the branch with my fork and all the tests are passing now

**Review by ramonjd — APPROVED** [review]
Tested and LGTM

Should we add a version annotation in the function comment docs?

```
@since 6.8.0 Support was added for `audio/x-wav`.
```

**Comment by Imran92** [comment]
> Tested and LGTM
> 
> Should we add a version annotation in the function comment docs?
> 
> ```
> @since 6.8.0 Support was added for `audio/x-wav`.
> ```

Thanks @ramonjd ! I've added a comment here https://github.com/WordPress/wordpress-develop/pull/7265/commits/adbe059d44445c90c4db0aed6f639bef952c71ec, should I just go ahead and update the patch on the tracks ticket?

**Comment by ramonjd** [comment]
Thank you @Imran92 !! This all LGTM. 

I can commit later today.

> should I just go ahead and update the patch on the tracks ticket?

I don't think it's necessary. When you have already linked a Github PR to the trac ticket, there's not need for a patch file.

The Github PR is the "patch". 

See: https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/

**Comment by ramonjd** [comment]
Committed in [r59389](https://core.trac.wordpress.org/changeset/59389) / 6f47a2c453e5e272c3f33cc5438c51e20a95d7f2

**Pull request closed without merging**
