### PR TITLE
REST API: Move link preparation to dedicated methods

### PR DESCRIPTION
**Pull request by dlh01**
Trac ticket: https://core.trac.wordpress.org/ticket/56019
Trac ticket: https://core.trac.wordpress.org/ticket/56020

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@dlh01 Let's keep these as they own tickets. 
Can you add some unit tests as well please.

**Comment by dlh01** [comment]
@spacedmonkey Are you saying you want separate PRs for each ticket?

**Comment by spacedmonkey** [comment]
> @spacedmonkey Are you saying you want separate PRs for each ticket?

Yes please.

**Comment by dlh01** [comment]
@spacedmonkey I've opened #2965 and #2966 for the separate tickets and will close this PR.

I see that post type and taxonomy links are currently being tested in [`WP_Test_REST_Post_Types_Controller::check_post_type_obj()`](https://github.com/WordPress/wordpress-develop/blob/01021eb8f64b9b8f9ff0ff04edf2da48ec66e566/tests/phpunit/tests/rest-api/rest-post-types-controller.php#L219-L251) and [`WP_Test_REST_Taxonomies_Controller::check_taxonomy_object()`](https://github.com/WordPress/wordpress-develop/blob/01021eb8f64b9b8f9ff0ff04edf2da48ec66e566/tests/phpunit/tests/rest-api/rest-taxonomies-controller.php#L252-L278), respectively. Could you elaborate on what kind of test coverage you'd like added?

**Pull request closed without merging**
