### PR TITLE
Pin the floating-ui package versions in package-lock.json

### PR DESCRIPTION
**Pull request by tellthemachines**
To avoid breaking updates.

Trac ticket: https://core.trac.wordpress.org/ticket/58847

Essentially copies the fix from the previous time we had this problem: https://github.com/WordPress/wordpress-develop/pull/4155#discussion_r1121383013

Hope we can make our popovers work with the latest versions of those packages before too much longer 😅 but given it's RC time again this seems like the safest option for now.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
LGTM

Thank you for fixing this! 🙇🏻 


| Before | After |
| ------------- | ------------- |
|   |   |

**Comment by huzaifaalmesbah** [comment]
Thank you very much for this solution. @tellthemachines

**Review by spacedmonkey — APPROVED** [review]

**Comment by tellthemachines** [comment]
Committed to trunk in [r56284](https://core.trac.wordpress.org/changeset/56284). Pending testing on trunk to check the issue is fixed, we can then commit it to the release branch.

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/56289

**Pull request closed without merging**
