### PR TITLE
Sync editor packages for WordPress 6.5 RC4

### PR DESCRIPTION
**Pull request by getdave**
Syncs editor packages for WordPress 6.5 RC4. Contains changes as per

https://github.com/WordPress/gutenberg/pull/60241

Note [these changes were triaged and approved by release leads in WP Slack](https://wordpress.slack.com/archives/C02RQBWTW/p1711544477269099).

Trac ticket: https://core.trac.wordpress.org/ticket/60315

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by getdave** [comment]
cc @swissspidy @dream-encode @desrosj @youknowriad

**Comment by getdave** [comment]
⚠️ I have yet to test these changes. I will endeavour to do so first thing tomorrow UTC+0.

**Review by desrosj — APPROVED** [review]
This looks good to me. I'm seeing the expected changes, and my testing to confirm the bugs are fixed has been successful.

**Review by aaronjorbin — APPROVED** [review]
I've also tested and belive that this is looking good

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/57888.

**Pull request closed without merging**
