### PR TITLE
Feat: Update the `underscore` js to 1.13.7

### PR DESCRIPTION
**Pull request by hbhalodia**
Trac ticket: https://core.trac.wordpress.org/ticket/61836

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by desrosj** [comment]
Thanks @hbhalodia! Could you also update `wp-includes/script-loader.php` to indicate the correct version for the `scripts->add( 'underscore' );` call?

**Comment by hbhalodia** [comment]
Sure, I would update the PR.

**Comment by hbhalodia** [comment]
Hi @desrosj, This is now updated. Thank You,

**Review by aristath — APPROVED** [review]

**Comment by peterwilsoncc** [comment]
Merged [r58880](https://core.trac.wordpress.org/changeset/58880) / https://github.com/WordPress/wordpress-develop/commit/faf75b7925b3dfcb7c711bd060fac8a3d2b9cdf2

**Pull request closed without merging**
