### PR TITLE
Remove redundant server state from Interactivity Router

### PR DESCRIPTION
**Pull request by sirreal**
https://github.com/WordPress/gutenberg/pull/66183
https://github.com/WordPress/wordpress-develop/pull/7600

Trac ticket: https://core.trac.wordpress.org/ticket/62465

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by gziolo** [comment]
Tested in WordPress Playground, everything works correctly with the Query block and region-based client-side navigation.

**Comment by sirreal** [comment]
@michalczaplinski @darerodz @luisherranz This was necessary to workaround a bug that was fixed in https://github.com/WordPress/gutenberg/pull/66183. Do you want to take this over to remove the redundant state now that the bugfix is in Core?

**Review by michalczaplinski — APPROVED** [review]
I've tested it and the Query Loop works just fine. The router animation continues to appear now.

**Comment by michalczaplinski** [comment]
Commited to Core in https://core.trac.wordpress.org/changeset/59416

**Pull request closed without merging**
