### PR TITLE
HTML API: Rename test classes according to #56846-trac

### PR DESCRIPTION
**Pull request by dmsnell**
See [58899-trac](https://core.trac.wordpress.org/ticket/58899#ticket)

### CODE REVIEW

**Comment by dmsnell** [comment]
cc: @costdev @ockham

**Review by costdev — APPROVED** [review]
Thanks for the ping @dmsnell! The changes look good to go. 🙂

**Comment by ockham** [comment]
Thanks both. Committed to Core in https://core.trac.wordpress.org/changeset/56299.

**Comment by dmsnell** [comment]
Thank you both!

**Pull request closed without merging**
