### PR TITLE
Do not hardcode script languages path for themes

### PR DESCRIPTION
**Pull request by swissspidy**
The change in https://core.trac.wordpress.org/ticket/60891 / https://core.trac.wordpress.org/changeset/57922 was not tested enough with themes that load script translations. It caused a regression where WP tried to look up script translations for a theme in `wp-content/languages/plugins`.

Even when using a custom `WP_PLUGIN_DIR`/`WP_PLUGIN_URL` configuration, we should always use the correct path for themes and plugins alike.

To-do:

* [x] Add unit tests

Trac ticket: https://core.trac.wordpress.org/ticket/62016

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/59126

**Comment by them-es** [comment]
@swissspidy Could you have a look at whether this is a viable alternative approach?

**Replace the changes in this commit with only the following line:**
[Line 1210](https://github.com/WordPress/wordpress-develop/pull/7423/files#diff-31cd15428a59baa3494149d7ccf047ce80c8d7783d6e889c80d118043548ee1aL1210) `$languages_path = WP_LANG_DIR . '/' . $relative[0];`

At least this fixes a regression reported 2 weeks ago: https://core.trac.wordpress.org/ticket/62155

**Comment by swissspidy** [comment]
No, this just reintroduces the original bug.

**Comment by swissspidy** [comment]
@them-es #7562 should address this, please test

**Comment by them-es** [comment]
@swissspidy Yes that seems to fix the reported Multisite regression. Thank you for the quick turnaround 👍

**Pull request closed without merging**
