### PR TITLE
#55646 Correct the documented arguments for XML-RPC server methods

### PR DESCRIPTION
**Pull request by johnbillion**
Trac ticket: https://core.trac.wordpress.org/ticket/55646

### CODE REVIEW

**Review by SergeyBiryukov — APPROVED** [review]
Looks good to me :+1:

**Comment by audrasjb** [comment]
Honestly I wasn't aware of numbered variable names before, but TIL: it's already used several times in Core, like `parse_db_host()` for example.

Looks good to me at a glance but I think that if we're going to generalize this to many functions, we should probably open a Meta ticket to improve the docblock parser, as it looks pretty bugged on DevHub. For example, see https://developer.wordpress.org/reference/classes/wpdb/parse_db_host/

**Comment by audrasjb** [comment]
Yeah there's at least a bug with `$0`: https://developer.wordpress.org/reference/functions/wp_maybe_grant_site_health_caps/

Definitely something we should fix :)

**Comment by johnbillion** [comment]
Well spotted Jb, will you open a meta ticket?

**Comment by audrasjb** [comment]
Sure!

**Review by audrasjb — APPROVED** [review]

**Comment by audrasjb** [comment]
Meta ticket, for reference: https://meta.trac.wordpress.org/ticket/6433

**Comment by johnbillion** [comment]
https://core.trac.wordpress.org/changeset/53881

**Pull request closed without merging**
