### PR TITLE
Restore static caching in _load_textdomain_just_in_time()

### PR DESCRIPTION
**Pull request by ocean90**
For context see [the caching in 5.5.3](https://github.com/WordPress/wordpress-develop/blob/69d6206926f5a683ce9d643a4712de132529dca3/src/wp-includes/l10n.php#L1183-L1291).

Trac ticket: https://core.trac.wordpress.org/ticket/51678

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
Could you perhaps expand a bit on this change? Why another static cache on before the registry?

**Comment by ocean90** [comment]
@swissspidy See the linked Trac ticket and the caching we had before. Without the cache we now repeatedly call `load_textdomain()` (and thus increased file system reads) for domains without any files.

**Comment by swissspidy** [comment]
Right. I was more thinking about calling `$wp_textdomain_registry->set()` in `_load_textdomain_just_in_time()` so that `$wp_textdomain_registry` acts as the sole cache here. (as suggested in https://core.trac.wordpress.org/ticket/51678#comment:14). But perhaps that's a bit too complex?

**Comment by ocean90** [comment]
@swissspidy This would only work if we make the registry locale aware, right? https://github.com/WordPress/wordpress-develop/pull/694 would be related.

**Comment by swissspidy** [comment]
yes indeed

**Comment by ocean90** [comment]
In this case I tend to revert the change for 5.6 so we'd have enough time for testing other implementations.

**Comment by swissspidy** [comment]
Could also use this approach here and extend the class in 5.7, no strong opinion either way

**Pull request closed without merging**
