### PR TITLE
Make `$theme_has_support` on array.

### PR DESCRIPTION
**Pull request by spacedmonkey**
Trac ticket: https://core.trac.wordpress.org/ticket/58758

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by felixarntz — COMMENTED** [review]
That's a neat solution that requires only few changes, so IMO the best option for now. 👍 

Can you add a unit test that calls this for two different themes in a single test with the caching enabled, to cover that the array approach works?

**Comment by spacedmonkey** [comment]
@felixarntz We already have a nice test suite for this in [Tests_Theme_WpThemeHasThemeJson](https://github.com/WordPress/wordpress-develop/blob/trunk/tests/phpunit/tests/theme/wpThemeHasThemeJson.php). There is already a test for switching themes. See [test_switching_themes_recalculates_support](https://github.com/WordPress/wordpress-develop/blob/f933aa3616aa8d49bdd67886e4af287579093c25/tests/phpunit/tests/theme/wpThemeHasThemeJson.php#L60-L71).

**Review by felixarntz — APPROVED** [review]
@spacedmonkey Ah, good point. Looks like that test indeed already covers the change here - nice one 👍

**Review by westonruter — APPROVED** [review]

**Comment by spacedmonkey** [comment]
Committed - https://github.com/WordPress/wordpress-develop/commit/a92f7bf8cb52b4d00554b5888d39b6a6440f7824

**Pull request closed without merging**
