### PR TITLE
Feature: Add wp_get_wp_version() function to return the current WordPress version

### PR DESCRIPTION
**Pull request by Debarghya-Banerjee**
Trac Ticket: [Core-61627](https://core.trac.wordpress.org/ticket/61627)

## Summary:
- This pull request proposes the introduction of a helper function to retrieve the WordPress version accurately without relying on the version.php file directly. This enhancement aims to address issues where plugins override the $wp_version global variable, potentially breaking WordPress functionality.

## Problem Statement:
- In various scenarios, WordPress relies on the version.php file to obtain the correct WordPress version. However, some plugins advise overriding the $wp_version global variable to hide the WordPress version for perceived security benefits. This practice can lead to compatibility issues and disrupt core functionalities that depend on accurate version detection.

## Solution:
- Introduced a dedicated helper function that retrieves the current WordPress version reliably. This function will centralize version retrieval, ensuring consistent and accurate reporting of the WordPress version across different contexts without the risk of interference from plugins modifying global variables.

## Impact:

- Introducing the proposed helper function for retrieving the WordPress version will:

    - `Enhance Reliability`: Ensure consistent and accurate reporting of the WordPress version across environments, reducing errors caused by variable overrides.

    - `Improve Compatibility`: Mitigate conflicts with plugins that modify core variables, fostering better compatibility and stability for themes and plugins.

    - `Streamline Maintenance`: Simplify ongoing maintenance by providing a standardized method for version retrieval, reducing complexity and potential issues.

    - `Enhance Security Practices`: Promote transparency in WordPress version reporting, aiding in vulnerability assessment and site security.

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
It would be good to implement this in a few places that are using the pattern already.

If you search the code base for `require ABSPATH . WPINC . '/version.php';` you will find some suitable locations.

Ignore the following files as they either don't have access to the function or are used to populate the global:

* src/wp-settings.php
* src/wp-admin/load-scripts.php
* src/wp-admin/load-styles.php
* src/wp-includes/script-loader.php

**Comment by Debarghya-Banerjee** [comment]
Hi @peterwilsoncc , I have addressed your feedback, please let me know, if I have missed out on something. Thanks :-)

**Review by peterwilsoncc — APPROVED** [review]
Thanks @Debarghya-Banerjee, this looks good to me and tests well.

I've taken the liberty of pushing 86aed60fbd6dd461e4cc364bf61646785583435d and 8bc0d1b1b35080e04100d892bea7c98b8b121753 to expand the documentation and comments to explain why the function is not used in `script-loader.php`

**Comment by peterwilsoncc** [comment]
Merged [r58813](https://core.trac.wordpress.org/changeset/58813) / https://github.com/WordPress/wordpress-develop/commit/c41304d73c32c968056abd2b1ffa19e83e9833a9

Thanks for your work on this, Debarghya.

It looks like WordPress 6.7 will be the first version in which you have been given props. Congratulations! The Core Contributor badge won't appear on your WordPress.org profile until after the release so please don't worry that it hasn't been added immediately.

**Comment by Debarghya-Banerjee** [comment]
Thanks @peterwilsoncc :-)

**Pull request closed without merging**
