### PR TITLE
Fixed missing escape

### PR DESCRIPTION
**Pull request by nareshbheda**
Trac ticket: https://core.trac.wordpress.org/ticket/59278

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by audrasjb** [comment]
Thanks for the PR. FWIW there is at least one other occurrence in this file:
- https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-admin/includes/class-custom-image-header.php#L341

**Comment by nareshbheda** [comment]
@audrasjb Thank you for the suggestion,  I have applied your suggestion in the latest commit.

**Comment by kebbet** [comment]
Why add escaping in line 341, it does not make sense @audrasjb?

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r57364](https://core.trac.wordpress.org/changeset/57364).

**Pull request closed without merging**
