### PR TITLE
Update Twemoji to 15.0.3.

### PR DESCRIPTION
**Pull request by desrosj**
This switches the source for the Twemoji library from twitter/twemoji to jdecked/twemoji while also applying the 15.0.3 update.

Trac ticket: https://core.trac.wordpress.org/ticket/57600

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
This looks good to me, the test can probably be a blackbird as it uses a ZWJ https://emojipedia.org/black-bird

**Comment by peterwilsoncc** [comment]
@desrosj In 63c1fa5b7eebbef0191394c0c22e1890d3bed4df I've pushed the update to the JavaScript tests.

On a system that doesn't support the new emoji, the canvas renders identically 
Screen Shot 2024-01-30 at 1 52 55 pm

Using the emoji in a post renders on a system without support renders the emoji correctly
Screen Shot 2024-01-30 at 1 55 52 pm

On a system that does support the new emoji, the canvas renders differently 
IMG_92B2260A7FE8-1

**Comment by desrosj** [comment]
Thanks @peterwilsoncc! I started to do some precommit testing on this earlier today before I helped get the update out, and I noticed that the `grunt  precommit:emoji` script is broken. I tried several different forms of the URL, including changing it to a version specific one, but couldn't get it to work. I'll check in some more my tomorrow, but if you care to have a look during your day, feel free.

**Comment by peterwilsoncc** [comment]
@desrosj Looks to be due to GitHub [sunsetting SVN support](https://github.blog/2023-01-20-sunsetting-subversion-support/). The grunt file is trying to use svn to get a list of the files without doing a clone.

https://github.com/WordPress/wordpress-develop/blob/cf8b74de164f322a78ea51921b236213805e6f79/Gruntfile.js#L1056

**Comment by peterwilsoncc** [comment]
In https://github.com/WordPress/wordpress-develop/pull/5804/commits/21cfb61661e405f8a422a5172937c520dfec17a0 I've pushed a fix to the precommit script that uses the GitHub CLI instead of SVN.

It appears to be working but I haven't pushed the changes to the formatting file as it would be good to get a logic check on that from you.

**Comment by mirkashifmirkashif94** [comment]
Consider alternatives to Twemoji for emoji script and image library in light of recent changes at Twitter. Options include EmojiOne, JoyPixels, OpenMoji, Noto Emoji, Apple Color Emoji, Microsoft Segoe UI Emoji,{{{
#!html
<a href="https://casino-hotspot.com"></a><a href="https://comogabaritar.com.br"></a><a href="https://www.averyinjurylaw.com"></a><a href="https://www.duplicatebill.net"></a>
}}} and Twilio's Open Source Emojis. Choose based on licensing, emoji variety, and platform compatibility.

**Comment by peterwilsoncc** [comment]
Precommit broken due to the number of files exceeding 1000. 

I've tried using the graphql API and it works locally but the grunt.spawn command I've written is broken but should show what I am trying to do.

**Comment by desrosj** [comment]
Committed in [Core-57626](https://core.trac.wordpress.org/changeset/57626). I've moved all build related changes to #6107 for further exploration.

**Pull request closed without merging**
