### PR TITLE
Help/About: Update About section images

### PR DESCRIPTION
**Pull request by ryelle**
Switch to the CDN URLs for the images on the About page. Update the images used on Freedoms & Privacy to match the 6.1 design style.

Link to screenshots: [freedoms](https://user-images.githubusercontent.com/541093/197580657-1ce78f78-10a7-4acd-9ac2-59153669befc.png), [privacy](https://user-images.githubusercontent.com/541093/197580665-9fcbbeda-c154-4e25-86ee-ea59a1d56fc7.png)

Trac ticket: https://core.trac.wordpress.org/ticket/56357

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by audrasjb** [comment]
The PR looks good to me @ryelle (and the new images look great too!)

freedoms
privacy
about

**Comment by kebbet** [comment]
An optimized version of privacy.svg. I remade it with Illustrator.
`<svg width="320" height="320" viewBox="0 0 320 320" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"><g fill="#FFFFFF" stroke="#3858E9" stroke-width="1.2" stroke-miterlimit="10"><path d="M256.7.9H63.3C28.9.9.9 28.9.9 63.3V160a159.1 159.1 0 0 0 318.2 0V63.3c0-34.4-28-62.4-62.4-62.4z"/><circle cx="231.7" cy="104.2" r="35.1"/><circle cx="221.1" cy="114.8" r="35.1"/><circle cx="210.5" cy="125.4" r="35.1"/><circle cx="199.9" cy="136" r="35.1"/><circle cx="189.3" cy="146.6" r="35.1"/><circle cx="178.7" cy="157.2" r="35.1"/><circle cx="168.1" cy="167.8" r="35.1"/><circle cx="158.1" cy="177.8" r="35.1"/><circle cx="146.9" cy="189" r="35.1"/><circle cx="136.3" cy="199.6" r="35.1"/><circle cx="126.2" cy="189.5" r="35.1"/><circle cx="116.1" cy="179.4" r="35.1"/><circle cx="106" cy="169.3" r="35.1"/><circle cx="95.9" cy="159.2" r="35.1"/><circle cx="85.8" cy="149.1" r="35.1"/></g></svg>
`

**Comment by kebbet** [comment]
freedom-1.svg -> 
`<svg width="180" height="180" viewBox="0 0 180 180" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" focusable="false"><g fill="#FFFFFF" stroke="#3858E9" stroke-width="1.2" stroke-miterlimit="10"><circle cx="36.3" cy="90" r="35.8"/><circle cx="37.5" cy="101.2" r="35.8"/><circle cx="40.8" cy="111.5" r="35.8"/><circle cx="46.1" cy="120.8" r="35.8"/><circle cx="53" cy="128.9" r="35.8"/><circle cx="61.4" cy="135.5" r="35.8"/><circle cx="71" cy="140.3" r="35.8"/><circle cx="81.6" cy="143.1" r="35.8"/><circle cx="92.9" cy="143.7" r="35.8"/><circle cx="103.9" cy="141.9" r="35.8"/><circle cx="114" cy="138.1" r="35.8"/><circle cx="123.1" cy="132.4" r="35.8"/><circle cx="130.8" cy="125.1" r="35.8"/><circle cx="136.9" cy="116.4" r="35.8"/><circle cx="141.2" cy="106.5" r="35.8"/><circle cx="143.5" cy="95.7" r="35.8"/><circle cx="143.5" cy="84.3" r="35.8"/><circle cx="141.2" cy="73.6" r="35.8"/><circle cx="136.9" cy="63.7" r="35.8"/><circle cx="130.8" cy="55" r="35.8"/><circle cx="123.1" cy="47.6" r="35.8"/><circle cx="114" cy="41.9" r="35.8"/><circle cx="103.9" cy="38.1" r="35.8"/><circle cx="92.9" cy="36.4" r="35.8"/><circle cx="81.6" cy="37" r="35.8"/><circle cx="71" cy="39.7" r="35.8"/><circle cx="61.4" cy="44.5" r="35.8"/><circle cx="53" cy="51.1" r="35.8"/><circle cx="46.1" cy="59.2" r="35.8"/><circle cx="40.8" cy="68.5" r="35.8"/><circle cx="37.5" cy="78.9" r="35.8"/><circle cx="36.4" cy="90" r="35.8"/></g></svg>
`

**Comment by kebbet** [comment]
WIP: https://github.com/WordPress/wordpress-develop/pull/3523

**Comment by kebbet** [comment]
#3523 Optimizes 5 of the SVG files. freedom-2.svg is not optimized with new shapres and reduced clip masks, due to cutting circles resutls in complex shapes.

**Comment by ryelle** [comment]
Committed in [r54690](https://core.trac.wordpress.org/changeset/54690)

**Pull request closed without merging**
