### PR TITLE
WP Backport Block Supports: Add text columns (column count) to typography block supports

### PR DESCRIPTION
**Pull request by ramonjd**
This PR adds the PHP changes for the following Gutenberg PRs:

- https://github.com/WordPress/gutenberg/pull/33587
- https://github.com/WordPress/gutenberg/pull/46566

Frontend changes also need to be ported and will be done before WP 6.3 beta (before June 27)

Testing:

`npm run test:php -- --filter Tests_Theme_wpThemeJson`

Trac ticket: https://core.trac.wordpress.org/ticket/58549

### CODE REVIEW

**Comment by ramonjd** [comment]
@aaronrobertshaw do these ported changes look okay to you?

**Comment by aaronrobertshaw** [comment]
Thank you for wrangling this backport @ramonjd 

I think we might need to also backport the addition of `textColumns` support to the style engine which was added to Gutenberg in https://github.com/WordPress/gutenberg/pull/46566. As it's all for one feature, should that be part of this backport or separate?

The changes in this PR look good in terms of addressing https://github.com/WordPress/gutenberg/pull/33587 though.

**Comment by ramonjd** [comment]
> I think we might need to also backport the addition of textColumns support to the style engine which was added to Gutenberg in https://github.com/WordPress/gutenberg/pull/46566.

Good spotting. I'll add it to this PR. 👍 

thanks

**Review by tellthemachines — APPROVED** [review]
Thanks for putting this up @ramonjd ! I spotted a missing since comment and added it in 😄 

Code LGTM and in accordance with the Gutenberg PRs; it won't really be testable in the UI until npm packages are updated but I can confirm everything else in the typography support is still working correctly.

**Comment by tellthemachines** [comment]
Committed in [r55985](https://core.trac.wordpress.org/changeset/55985) / [9a9a672](https://github.com/WordPress/wordpress-develop/commit/9a9a672a83b9e852bf03bc642ec42ac0eae9fdec).

**Pull request closed without merging**
