### PR TITLE
Update Welcome panel to match 6.1 release style

### PR DESCRIPTION
**Pull request by ryelle**
Apply the "About page" style update to the Welcome panel on the dashboard. This includes the 6.1 bubble image which is also added via https://github.com/WordPress/wordpress-develop/pull/3461.

This also updates the design to match the current color scheme. I'll link to screenshots, to avoid image-dumping in the ticket.

[Default](https://user-images.githubusercontent.com/541093/196289270-1a32cf73-aaf8-4790-8d4f-215d76990e4a.png), [Blue](https://user-images.githubusercontent.com/541093/196289265-fdef2791-c9b5-4e05-985e-5043c133d4db.png), [Coffee](https://user-images.githubusercontent.com/541093/196289267-49881a3d-db24-4340-b236-6172b66b15f5.png), [Ectoplasm](https://user-images.githubusercontent.com/541093/196289269-b55aa059-da3a-4b51-8c6a-80454cafe388.png), [Light](https://user-images.githubusercontent.com/541093/196289271-ffd6dc48-8386-4513-8611-13e598c80c83.png), [Midnight](https://user-images.githubusercontent.com/541093/196289273-c2898cbb-d32d-4ebf-ba87-03a22c3dad68.png), [Modern](https://user-images.githubusercontent.com/541093/196289275-eeef59f3-65df-4c02-a125-0b67682d5626.png), [Ocean](https://user-images.githubusercontent.com/541093/196289278-b4c5571a-e41e-4fb6-876f-f8b4714d7067.png), [Sunrise](https://user-images.githubusercontent.com/541093/196289279-ece13614-ce30-4cf4-8ced-06091e0b128e.png).

And on small screens, the background disappears. [Default](https://user-images.githubusercontent.com/541093/196289285-92fa17ac-2a0a-4e65-b274-2a705b0d47f1.png), [Blue](https://user-images.githubusercontent.com/541093/196289281-0a64d81a-c712-420b-98a4-636653e99d18.png), [Coffee](https://user-images.githubusercontent.com/541093/196289282-5c315609-dc6d-477e-9d4b-c37b851ca3b1.png), [Ectoplasm](https://user-images.githubusercontent.com/541093/196289283-9d066b5c-6905-4542-b437-cbb33d901ed1.png), [Light](https://user-images.githubusercontent.com/541093/196289287-02eb5fcb-12e3-4ed6-a241-89f75c69fd16.png), [Midnight](https://user-images.githubusercontent.com/541093/196289288-813ce343-8864-4337-b70f-dd0177fd66a3.png), [Modern](https://user-images.githubusercontent.com/541093/196289289-88233183-f4d5-467a-9f1b-ff58f1253c65.png), [Ocean](https://user-images.githubusercontent.com/541093/196289292-ec5c5f56-0820-45df-ae0c-a100a17d1eed.png), [Sunrise](https://user-images.githubusercontent.com/541093/196289293-d5612d88-e6b0-4ac2-bdb7-9bba76b77f61.png).

Trac ticket: https://core.trac.wordpress.org/ticket/56703

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by richtabor** [comment]
Mind swapping out the first icon with this one? I'd say its a bit clearer. Thanks!

Edit

**Comment by richtabor** [comment]
I think they look ace ✨

**Comment by ryelle** [comment]
> Mind swapping out the first icon with this one? I'd say its a bit clearer. Thanks!

Done ✅ 
Screen Shot 2022-10-18 at 10 14 47 AM

**Comment by dream-encode** [comment]
Merged into core in https://core.trac.wordpress.org/changeset/54638.

**Pull request closed without merging**
