### PR TITLE
REST API: Add missing options to the settings endpoint

### PR DESCRIPTION
**Pull request by Mamaduka**
PR registers options for the settings endpoints. Unfortunately, we missed them during WP 6.0 backports - https://github.com/WordPress/gutenberg/pull/38607#issuecomment-1138526934.

## Testing Instructions
1. Open a Post or Page editor.
2. Run this snippet in the DevTools console - `wp.data.select('core').getEntityRecord( 'root', 'site' );`
3. Confirm newly registered settings are returned.

Trac ticket: https://core.trac.wordpress.org/ticket/56058

---
**This Pull Request is for code review only. Please keep all other discussions in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by Mamaduka** [comment]
I'm not sure how to fix the remaining failure. Is there a command for regenerating API fixtures?

**Comment by spacedmonkey** [comment]
@Mamaduka If you run the tests locally, but running `npm run test:php`, it should regenerate that file. Just it and push it and it will fix the tests.

**Review by spacedmonkey — APPROVED** [review]
Looks good to me.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR!

This was merged to WP trunk in https://core.trac.wordpress.org/changeset/53588, but I noticed that the new options are the only ones in `register_initial_settings()` that use the `number` type instead of `integer`. If I'm reading it correctly, that means they can technically be floats. Since both `page_on_front` and `page_for_posts` are page IDs, should they be `integer`?

**Comment by Mamaduka** [comment]
Thanks for catching that, @SergeyBiryukov 🙇

**Comment by SergeyBiryukov** [comment]
I've made a follow-up commit that switches the type to integer as per the comment above :)

**Comment by SergeyBiryukov** [comment]
Thanks for the confirmation that it was OK to change the type :) Merged in https://core.trac.wordpress.org/changeset/53589.

Backported to the 6.0 branch in https://core.trac.wordpress.org/changeset/53590.

**Pull request closed without merging**
