### PR TITLE
Update Readme.html

### PR DESCRIPTION
**Pull request by pawki07**
Trac ticket: https://core.trac.wordpress.org/ticket/52315#section-pr

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by audrasjb — COMMENTED** [review]
Hello,
The readme file looks fine as it is without this PR. Why do you want to add those extra spaces? They aren't necessary :)

**Comment by pawki07** [comment]
> 
> 
> Hello,
> The readme file looks fine as it is without this PR. Why do you want to add those extra spaces? They aren't necessary :)

Screenshot (723)_LI
I was talking about the links which is visible on the readme.html. Have a look at it.

**Comment by audrasjb** [comment]
> > Hello,
> > The readme file looks fine as it is without this PR. Why do you want to add those extra spaces? They aren't necessary :)
> 
> Screenshot (723)_LI
> I was talking about the links which is visible on the readme.html. Have a look at it.

Sorry But I don't understand what's the issue here @pawki07 ?

**Comment by pawki07** [comment]
> 
> 
> > > Hello,
> > > The readme file looks fine as it is without this PR. Why do you want to add those extra spaces? They aren't necessary :)
> > 
> > 
> > Screenshot (723)_LI
> > I was talking about the links which is visible on the readme.html. Have a look at it.
> 
> Sorry But I don't understand what's the issue here @pawki07 ?

As explained by @SergeyBiryukov , now I understood that markup is broken and we need not add whitespaces to fix it. Thank you for the clarification.

**Pull request closed without merging**
