### PR TITLE
Interactivity API: Fix code formatting and add better types in docstrings

### PR DESCRIPTION
**Pull request by michalczaplinski**
Addresses minor formatting issues and adds better types in docstrings.

Following up on https://github.com/WordPress/wordpress-develop/pull/7460

Trac ticket: https://core.trac.wordpress.org/ticket/62149

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by michalczaplinski** [comment]
Committed with https://core.trac.wordpress.org/changeset/59153

**Comment by westonruter** [comment]
Props me too 😄

**Comment by michalczaplinski** [comment]
Oh, my apologies, Weston! 🙏 I've just read https://make.wordpress.org/core/handbook/best-practices/contributor-attribution-props/ and realized that Props should be given much more liberally than I had thought. 

Is there a way to add them post hoc?

**Comment by westonruter** [comment]
No big deal! Just that since most of the PR consisted of my suggestions from the previous PR review, it seemed like I should have been on the props list. 

You can fix up props in the Core Props screen on Make/Core: https://make.wordpress.org/core/wp-admin/admin.php?page=props-edit-core

**Comment by michalczaplinski** [comment]
Done 👍 

It doesn't appear in the [changeset](https://core.trac.wordpress.org/changeset/59153) but it seems to have updated in the UI.

**Pull request closed without merging**
