### PR TITLE
Twenty Twenty-Two: add alternate style variations

### PR DESCRIPTION
**Pull request by kjellr**
Trac ticket: https://core.trac.wordpress.org/ticket/55433

This PR adds three style variations to the Twenty Twenty-Two theme.  It is dependent on the Webfonts API: https://github.com/WordPress/wordpress-develop/pull/2622. If and when that is merged, this PR can be reviewed.

**Testing instructions**

- Check out this PR
- Go to the site editor and visit the global styles panel
- Click "Browse Styles"
- Verify all four variations load correctly

---

Todo: 

- [x] Get fonts working (Reliant on https://github.com/WordPress/gutenberg/pull/40262)
- [x] Implement pink and red variants.
- [x] Update readme with font information.

### CODE REVIEW

**Comment by jffng** [comment]
With the inclusion of https://github.com/WordPress/wordpress-develop/pull/2622 in time for Beta 3, would it make sense and be possible to include this PR, since it leverages the feature?

I'm happy to prep the commit to trunk, but would need help on the backport to 6.0 branch I think because I don't have those privileges.

**Comment by hellofromtonya** [comment]
>With the inclusion of https://github.com/WordPress/wordpress-develop/pull/2622 in time for Beta 3, would it make sense and be possible to include this PR, since it leverages the feature?

Yes, I think so. Why? The decision to include the webfonts stopgate during the beta cycle was to include TT2's new styles variations in 6.0 and for themers too.

>I'm happy to prep the commit to `trunk`, but would need help on the backport to 6.0 branch I think because I don't have those privileges.

The 6.0-branch doesn't exist yet, i.e. not until RC1. I'll ping you once the webfonts stopgap PR is committed. Then this PR can be committed too.

**Comment by hellofromtonya** [comment]
@jffng https://core.trac.wordpress.org/changeset/53282 committed https://github.com/WordPress/wordpress-develop/pull/2622 into `trunk`. It's now available for this TT2 PR.

**Review by hellofromtonya — APPROVED** [review]
Used this PR for testing the internal-only theme.json webfonts handler (see PR #2622 and commit https://core.trac.wordpress.org/changeset/53282). Works well 👍

**Comment by jffng** [comment]
Committed in https://core.trac.wordpress.org/changeset/53286/, thanks for all the work and consideration to make this happen.

**Pull request closed without merging**
