### PR TITLE
Use  WP_Term::get_instance if object_id is present.

### PR DESCRIPTION
**Pull request by spacedmonkey**
Trac ticket:  https://core.trac.wordpress.org/ticket/58327
---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by felixarntz — COMMENTED** [review]
@spacedmonkey Can you clarify your thinking behind this change? I'm not sure I understand. What is the relevant difference between `get_term()` and `WP_Term::get_instance()`?

**Comment by spacedmonkey** [comment]
@felixarntz @joemcgill 

Basically, `get_term` has some overhead attached to it. It has filters and after the filtering, it rerun the sanitisation. When `all_with_object_id` is requsted ( in `update_object_term_cache` ), you only need the raw object. `update_object_term_cache` only needs to the term ids, so those filters and sanitisation are not needed. The sanitisation is run in `WP_Term::get_instance()` meaning no break in B/C. But as `update_object_term_cache` run on every WP_Query, which can be run 10+ times on many themes, ( block template parts, menus etc ), these calls to get_term can really really mount up, resulting in thousands of calls to `sanative_term` and `apply_filters`. 

This change is a side effect of https://github.com/WordPress/wordpress-develop/commit/4a9f5fe3be47914b3f2b30aaf863761335cf1ad2 , resulting in the unexpected overhead.

**Comment by peterwilsoncc** [comment]
@spacedmonkey I think `get_post` had the same overhead and was solved by bypassing the filtering when possible:

https://github.com/WordPress/wordpress-develop/blob/5ebe28966e5decbe1862c147bf98db0d8094038e/src/wp-includes/class-wp-post.php#L251-L253

Would this work in `WP_Term::get_instance` instead of changing WP Query? The terms are cached with raw sanitization so this should save a bunch of work for sites using `get_term()` too.

```diff
diff --git a/src/wp-includes/class-wp-term.php b/src/wp-includes/class-wp-term.php
index 0f5631353e..f98c132017 100644
--- a/src/wp-includes/class-wp-term.php
+++ b/src/wp-includes/class-wp-term.php
@@ -182,7 +182,9 @@ final class WP_Term {
 		}
 
 		$term_obj = new WP_Term( $_term );
-		$term_obj->filter( $term_obj->filter );
+		if ( empty( $term_obj->filter ) || 'raw' !== $term_obj->filter ) {
+			$term_obj->filter( $term_obj->filter );
+		}
 
 		return $term_obj;
 	}
diff --git a/src/wp-includes/taxonomy.php b/src/wp-includes/taxonomy.php
index a611307b6d..eb452ab7b5 100644
--- a/src/wp-includes/taxonomy.php
+++ b/src/wp-includes/taxonomy.php
@@ -3827,6 +3827,10 @@ function update_term_cache( $terms, $taxonomy = '' ) {
 		// Object ID should not be cached.
 		unset( $_term->object_id );
 
+		if ( empty( $_term->filter ) || 'raw' !== $_term->filter ) {
+			sanitize_term( $_term, $_term->taxonomy, 'raw' );
+		}
+
 		$data[ $term->term_id ] = $_term;
 	}
 	wp_cache_add_multiple( $data, 'terms' );
```

**Comment by spacedmonkey** [comment]
@peterwilsoncc I have created a PR based on your idea. https://github.com/WordPress/wordpress-develop/pull/5260. This solution multiple problems, of double sanitation. Please take a look.

**Comment by spacedmonkey** [comment]
Fixed in https://github.com/WordPress/wordpress-develop/commit/c1247f6a278bd6a5fec799964177743b5d26a2aa

**Pull request closed without merging**
