### PR TITLE
KSES: Allow leading trailing double hyphen in data attributes

### PR DESCRIPTION
**Pull request by sirreal**
Trac ticket: Core-61052

Allow data attrbitues with leading, trailing, and double `-` in the attribute name.

This relaxes the hyphen restriction introduced in https://core.trac.wordpress.org/changeset/43981. It is intended to be a simple change to allow data attributes used frequently by the Interactivity API like `data-wp-on--click="…"`.

It is _not_ a substitute for https://github.com/WordPress/wordpress-develop/pull/6429. I'd like to see that move ahead the data attribute restrictions further relaxed to align with what's allowed by the specification. This _is_ intended to be a smaller and easier change to solve the immediate need that can be landed without too much difficulty.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by dmsnell — APPROVED** [review]
As a step improvement this is helpful. I'm leaving #6429 open, but I don't want it to be a blocker for opening up this patch.

**Comment by sirreal** [comment]
I agree, I'd still prefer to see https://github.com/WordPress/wordpress-develop/pull/6429. Landing this is compatible with https://github.com/WordPress/wordpress-develop/pull/6429 as a future enhancement.

**Comment by cbravobernal** [comment]
I tested writing custom HTML in a post with a contributor, author, editor and admin roles and:

Screenshot 2024-06-03 at 14 00 22


 - In `trunk`, the `data-wp-on--click` is not saved on the database.
Screenshot 2024-06-03 at 13 58 37

 -  Within this branch, `data-wp--on--click` is saved on the database.
Screenshot 2024-06-03 at 13 59 26

**Review by cbravobernal — APPROVED** [review]
Works as expected.

**Comment by dmsnell** [comment]
Merged in [[58294]](https://core.trac.wordpress.org/changeset/58294)
https://github.com/wordpress/wordpress-develop/commit/89bec7acd8530a75ee1fcd287d7a328c4e024fa9

**Pull request closed without merging**
