### PR TITLE
Plugin Dependencies tab

### PR DESCRIPTION
**Pull request by afragen**
This PR adds the ability to define plugin dependencies using a `Requires Plugins` header.

```php
/**
 * Plugin Name: Test Dependencies
 * Author: Andy Fragen
 * Description: Test for Required Plugins header.
 * Version: 0.1
 * Requires Plugins: gutenberg, woocommerce
 */
```

If any installed plugin contains a `Requires Plugins` header with correct data. The user will see an admin notice with a link to a new **Dependencies** tab in the **Install Plugins** page.

The Dependencies tab will contain a listing of all plugins that have been designated as plugin dependencies. From this tab the user may easily install/activate any plugin dependency. The listed plugin cards contain information reporting the plugins that require each specific dependency.

The admin notice will continue to display until all plugin dependencies have been installed.

The plugins page will display information in the plugin row of installed plugin dependencies showing what plugins require them.

Installed plugin dependencies will be unable to be deleted. Once activated they will be unable to be deactivated.

This PR creates a tab in the plugins install  ( **Plugins > Add New** ) page as this seems to be the logical area to install a plugin. Specifically it does not display uninstalled plugin dependencies in the **Installed Plugins** page. Doing so would seem illogical. Whether the tab is in the Plugins page or in the Plugins Install page it is a filter.

This PR makes no attempt to ensure that a plugin with dependencies behaves correctly if any of those dependencies
are not installed. That is the responsibility of the plugin developer.

### Disagreements

- Creating a tab in the **Install Plugins** page instead of in the **Plugins** page
- Scroll directly to the uninstalled plugins in the dependencies tab.

Trac ticket: https://core.trac.wordpress.org/ticket/22316

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by afragen** [comment]
In this example there are 2 unactivated plugins, Test Dependencies and Test Dependencies 2. These both have defined `Required Plugins` headers defined.

These headers are sanitized to only allow valid dot org plugin slugs. An example of one of these headers is
`Required Plugins: gutenberg, hello-dolly, "junk-list ,  here for test", 435_bad`

An admin notice is present to let the users know there are still unmet plugin dependencies. Once all plugin dependencies have been installed the admin notice will not display. 

The plugin row displays information for plugin dependencies showing the plugins that require each specific plugin dependency.

plugin-page-dependencies

The Dependencies tab displays plugin cards for all plugin dependencies. Each plugin card displays information as to which installed plugin is asking for the dependency.

plugin-install-dependencies

**Comment by afragen** [comment]
Simplified Dependencies tab header message as suggested in https://core.trac.wordpress.org/ticket/22316#comment:236 

screenshot_121

**Comment by afragen** [comment]
Updated to use active voice for header as `Requires Plugins`. Consistent with other **Requires** headers.

**Comment by afragen** [comment]
Added automatic plugin deactivation when required plugins are not installed and active.

**Comment by afragen** [comment]
There is a feature plugin with this PR at https://github.com/afragen/plugin-dependencies-tab

The plugin will receive updates via [Git Updater](https://github.com/afragen/git-updater)

**Comment by afragen** [comment]
Put message below description in plugin card.
screenshot_157

**Comment by paaljoachim** [comment]
I have now tested both the PR's.

PR 1. Single line notification for each dependency.
https://github.com/WordPress/wordpress-develop/pull/1547#issuecomment-1083689256
Adds this example message: **Plugin "Sample" depends on plugin "gutenberg" to be installed. Install and activate "gutenberg"**
There are 4 lines with notifications. I felt flooded by all the notifications. I received a one line per plugin overview.

PR 2. This PR. Adds a new method Dependencies tab in the Add New plugins screen. 
Screenshot 2022-04-02 at 23 34 27

Uploading the sample plugin which includes dependencies. I see this:
Screenshot 2022-04-02 at 23 39 48

It does not flood the screen with notifications. There is only one line. It mentions that I need to go to the Dependencies install page which then brings me over here:
Screenshot 2022-04-02 at 23 41 37

I can easily see which plugins are needed to be installed for the "Sample" plugin to be activated.

This flow feels like a method that has always existed in WordPress core but that I have never noticed it before. It flows well. The UI is easy to understand. It does not flood me with notifications. This PR feels a lot tighter intertwined with core compared to the other PR. I also have in the back of my mind that we are also in general working on showing less notifications in the top which takes up a lot of visual space.

Also looking at the information included below the Sample plugin:
1- PR.
Plugin "Sample" has unmet dependencies. Once all required plugins are installed the plugin will be automatically activated. Alternatively you can cancel the activation of this plugin by clicking on the "cancel activation request" link above.

---> The above text is confusing as one can just skip activating the plugin. But here it seems that one will need to click "Cancel activation request" to make the top notifications go away.

2- This PR has a much more subtile approach: Requires: WooCommerce, Gutenberg
---> It just mentions which plugins are required to be installed and activated before one is able to activate the plugin.

1-PR feels like an older method.
2-This PR feels tighter and adds more subtile touch. Easier to deal with. Feels tightly integrated into core.

**Comment by peterwilsoncc** [comment]
Closing this off as it was decided to go down the feature project route, the repo is https://github.com/WordPress/wp-plugin-dependencies

**Pull request closed without merging**
