### PR TITLE
Populate WP_ENVIRONMENT_TYPE for local environment

### PR DESCRIPTION
**Pull request by igorradovanov**
This change populates the new `WP_ENVIRONMENT_TYPE` variable for the local development environment with the value of 'development' using the WordPress CLI.

Trac ticket: https://core.trac.wordpress.org/ticket/50903

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
We have a local environment type now that we could use instead. https://core.trac.wordpress.org/ticket/51064

**Comment by igorradovanov** [comment]
@TimothyBJacobs I agree with you that 'local' would be a better env type in this case. Let's see what @johnbillion thinks of this since the trac was originally raised to set the value to 'development'.

**Comment by johnbillion** [comment]
Yeah `local` would be better, thanks for pointing that out.

**Comment by igorradovanov** [comment]
Thanks Timothy and John.

The latest patch has been applied. Travis CI is running the checks.

Switched ```development``` to ```local``` in the .env file.

**Comment by dream-encode** [comment]
Merged into WP Core in https://core.trac.wordpress.org/changeset/49121

**Pull request closed without merging**
