### PR TITLE
Move deprecateL10nObject to its own file

### PR DESCRIPTION
**Pull request by noisysocks**
By moving `deprecateL10nObject()` to its own script, we're able to remove `common` as a dependency of `updates`. This means that we're not unnecessarilly executing `common` in `customize.php` which both fixes 51425 and means that there are ~2000 less lines of JavaScript executed in `customize.php`.

Trac ticket: https://core.trac.wordpress.org/ticket/51425

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Is it worth considering putting this in `@wordpress/deprecated`?

**Comment by ocean90** [comment]
Note that this was only a temporary solution which [will be removed in 5.7](https://core.trac.wordpress.org/ticket/51317) so I don't think we should move it into its own file.

**Comment by noisysocks** [comment]
> Is it worth considering putting this in `@wordpress/deprecated`?

It's a little cumbersome to do this because `@wordpress/deprecated` is a package in the Gutenberg repo. I'm not sure that it's worth the effort if this is a temporary function like @ocean90 says.

> Note that this was only a temporary solution which [will be removed in 5.7](https://core.trac.wordpress.org/ticket/51317) so I don't think we should move it into its own file.

Aha, I see. So `deprecateL10nObject` will be completely removed? Do you think then it's best to hold off on fixing 51425 until 5.7?

**Comment by hellofromtonya** [comment]
Resolved in changeset https://core.trac.wordpress.org/changeset/49625

**Pull request closed without merging**
