### PR TITLE
Type cast `gmt_offset` throughout.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Follow up to [r58923](https://core.trac.wordpress.org/changeset/58923) / https://github.com/WordPress/wordpress-develop/commit/6e7b1243f30af7b85d7dff44df4c86d852dec7df

In multiple locations throughout the code base the `gmt_offset` value is used in it's original form, this can lead to type errors.

Core-56358
Core-58986
Core-60629

I suspect a helper function may be the solution or adding some type casting to the `option_gmt_offset` filter.

cc @rarst as I can not ping you with a review request in the UI.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by Rarst** [comment]
> @Rarst as I can not ping you with a review request in the UI.

That would be because I am set to unavailable, due to being busy with war. 😬

To my memory most of nuance with `gmt_offset` type is when localized WP installs initiate it to string or something.

I would rather be refactoring it the heck out of usage, it's double-old API with opaque filter overrides and we don't _want_ it used at all.

**Comment by peterwilsoncc** [comment]
> I would rather be refactoring it the heck out of usage, it's double-old API with opaque filter overrides and we don't _want_ it used at all.

I've been thinking about this. I think it's a good enhancement to move in this direction but for the purpose of the PHP 8 compatibility would rather take a KISS approach and fix the code with the light touch.

That will allow for a more considered approach for any refactoring rather than doing it in a half baked manner.

**Comment by hellofromtonya** [comment]
Sorry for my delay in responding. The changes fully align to the changes made in r . They explicitly type cast to the needed data type before performing a math operation. Can also see it in action across PHP versions https://3v4l.org/rW2Ob#veol.

>I suspect a helper function may be the solution

Repeating code is not optimal. But given the goal @Rarst shared is to "refactoring it the heck out of usage", introducing a helper function now means deprecating it later.

>or adding some type casting to the `option_gmt_offset` filter.

What if the consuming code expects and uses it as a `string` and is not doing a math operation using it? Such a change would need exploration.

Given the bigger picture goal of getting rid of it, baby steps, i.e. tiny one-step-at-a-time, to resolve the immediate issues.

**Comment by hellofromtonya** [comment]
@peterwilsoncc how's the test coverage for the affected functions?

**Comment by peterwilsoncc** [comment]
> how's the test coverage for the affected functions?

@hellofromtonya The REST API's post controller is well tested and includes the specific case of shimming the post modified date in `WP_Test_REST_Posts_Controller::test_create_post_draft()`.

The others not so much:

- wp-mail.php is an endpoint
- bookmarks has some tests 
- The upgrader routine is tested in this repo but I'm not sure it's run very often https://github.com/WordPress/wordpress-upgrade-tester -- I'll check with Colin re:status of that.

**Comment by Rarst** [comment]
I skipped over helper function possibility. Don't think it's that involved of operation, I was thinking something like `wp_timezone()->getOffset(date_create_immutable('now',timezone_open('UTC')))`. Just talking from my head, hadn't worked through that one.

**Review by hellofromtonya — APPROVED** [review]
[As I previously noted](https://github.com/WordPress/wordpress-develop/pull/7233#issuecomment-2327431927), this baby step resolves the immediate issue and uses the existing pattern committed in https://core.trac.wordpress.org/changeset/58923.

Ideally these changes would have full test coverage. That said, in talking with @peterwilsoncc, he shared:

>The tests are there for current features and the upgrade tests should catch anything in the ugrade routine

Getting this committed early enough gives a longer soak time to hopefully uncover any issues.

I think this is ready enough for commit ✅

**Comment by peterwilsoncc** [comment]
Merged [r59064](https://core.trac.wordpress.org/changeset/59064) / https://github.com/WordPress/wordpress-develop/commit/bf09fe506620678fb82c3b872309edda0ed8ce61

**Pull request closed without merging**
