### PR TITLE
Comment content can be string with zero

### PR DESCRIPTION
**Pull request by cawa-93**
Trac ticket: https://core.trac.wordpress.org/ticket/49903#ticket

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by aduth** [comment]
`empty` may have been anticipating one or both of _not set_ and _empty string_. Personally, I think rather than handling the exceptions, it could be framed as more targeted to the specific anticipated problem values.

```php
if ( ! isset( $prepared_comment['comment_content'] ) || $prepared_comment['comment_content'] === '' ) {
```

Or, if `comment_count` is always set, and doesn't need to be checked:

```php
if ( $prepared_comment['comment_content'] === '' ) {
```

**Comment by TimothyBJacobs** [comment]
Yeah, I think it would be better to do an `isset` check and looking for an empty string exactly. That matches `wp_handle_comment_submission`.

**Comment by cawa-93** [comment]
@TimothyBJacobs  I agree with you. I didn't think about matching the behavior in the `wp_handle_comment_submission`. Then, perhaps, should the same hook be added to allow empty comments?

```php
$allow_empty_comment = apply_filters( 'rest_allow_empty_comment', false, $prepared_comment );
$missing_content = ! isset( $prepared_comment['comment_content'] ) || '' === $prepared_comment['comment_content']
	
if ( $missing_content && ! $allow_empty_comment ) {
	return new WP_Error(
		'rest_comment_content_invalid',
		__( 'Invalid comment content.' ),
		array( 'status' => 400 )
	);
}
```

**Comment by TimothyBJacobs** [comment]
Yeah I think it'd be great to make sure we realign ourselves with `wp_handle_comment_submission`.

**Comment by TimothyBJacobs** [comment]
Another related ticket: https://core.trac.wordpress.org/ticket/43177

**Comment by TimothyBJacobs** [comment]
Fixed in 1e030c4062f87b3881012d977a9adc3ade9c63b9.

**Pull request closed without merging**
