### PR TITLE
44098: Widget initialized without id_base with namespace

### PR DESCRIPTION
**Pull request by Mte90**
As https://core.trac.wordpress.org/ticket/44098 this happens when the widget is initialized without defining the `id_base` that is auto generated. The problem is that doesn't handle namespaces so this can create warning by php because the preg_match include a string with a backslash `\`.

Trac ticket: https://core.trac.wordpress.org/ticket/44098

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by Mte90** [comment]
This should fix the linting but for the test failing I don't know how I can mock a fake namespace and class.

**Comment by hmfs** [comment]
Hello @Mte90 ,

I am a new (hopeful) contributor. I saw this Trac ticket posted in the WordPress core slack room.

I was able to get the test to work by adding a namespaced widget. It seems cleaner to do this in a separate file than to try to add it to the original widget test file. I also had to adjust the logic in `WP_Widget` because `end` will fail the test when its argument is not a variable.

The code is available [here](https://github.com/WordPress/wordpress-develop/compare/master...hmfs:trac-44098).

Please let me know if you have questions.

**Comment by Mte90** [comment]
Hi @hmfs I merged your patch in this pull request.
Let's see if it is good now :-)

**Comment by Mte90** [comment]
@hmfs now the unit tests fails `Fatal error: Class 'Namespace\Sub\Sub\Class' not found in /var/www/src/wp-includes/class-wp-widget-factory.php on line 61`

**Comment by hmfs** [comment]
Hi @Mte90 ,

Thanks for the notice.

The test in `tests/phpunit/tests/widgets.php` should be removed because it was migrated into the first test in `tests/phpunit/tests/widgets-namespaced.php` due to the complexity of adding multiple namespaces per file.

It also looks like the coding standards are complaining about the structure of `widgets-namespaced.php`.

Both issues are fixed in this new PR to this branch: https://github.com/Mte90/wordpress-develop/pull/4

**Comment by Mte90** [comment]
Perfect :-D

**Comment by Mte90** [comment]
Ticket resolved

**Pull request closed without merging**
