### PR TITLE
Fix several typos and spelling mistakes for 6.6

### PR DESCRIPTION
**Pull request by swissspidy**
I used a GitHub action to find some spelling mistakes / typos and then manually fixed all of them.

The intention is to fix them all in one go, but **not** actually commit the GitHub action itself.

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by worais — COMMENTED** [review]
Hi @swissspidy :)

Crate-ci/typos@master step already pointed out some annotations, If you think it's opportune I can fix it.

image

**Comment by swissspidy** [comment]
@worais there are too many false positives. please ignore for now :) I'll open a ticket if I find some of them useful enough.

**Comment by worais** [comment]
@swissspidy  Perfect :) 
If I can help with anything, I'm available.

**Comment by swissspidy** [comment]
@SergeyBiryukov Would appreciate your review here as you're usually the one making this kind of changes.

My idea is to fix the typos as part of https://core.trac.wordpress.org/ticket/60699. The GHA is just for testing, not for committing.

**Comment by SergeyBiryukov** [comment]
> Would appreciate your review here as you're usually the one making this kind of changes.

Curious why `wp-admin/includes/ms.php` and `wp-includes/formatting.php` are excluded. Looks great to me otherwise! 👍

**Comment by swissspidy** [comment]
There were some false positives reported in those files, so it was easier to just ignore them here during development.

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/57987 / https://core.trac.wordpress.org/changeset/57988

Can do this again periodically I think

**Pull request closed without merging**
