### PR TITLE
Opt-out from re-registration of private APIs.

### PR DESCRIPTION
**Pull request by adamziel**
## Description 

Gutenberg introduced a system of sharing private APIs in
https://github.com/WordPress/gutenberg/pull/46131. One of the
safeguards is a check preventing the same module from opting-in
twice so that contributors cannot easily gain access by pretending
to be a core module.

That safeguard is only meant for WordPress core and not for
the released `@wordpress` packages. However, right now it is
opt-out and must be explicitly disabled by developers wanting to
install the `@wordpress` packages. Let's make it opt-out instead.

This commit opts-out from that check in WordPress core by setting
the `IS_WORDPRESS_CORE` to `true`. Once it's merged,
the Gutenberg plugin should be adjusted to use `false` as the
default value.

In other words:

* Before this PR and [Gutenberg#48352](https://github.com/WordPress/gutenberg/pull/48352), double opt-in safeguard is enabled by default
* After this PR and [Gutenberg#48352](https://github.com/WordPress/gutenberg/pull/48352), double opt-in safeguard is disabled by default AND WordPress core explicitly enables it

## Test plan:

Merging this PR will have no immediate effect:

* At the moment, WordPress core contains a Gutenberg version where re-registration is not allowed.
* Merging this PR on its own will not change anything in that Gutenberg version.
* The **related Gutenberg PR** **allows** the re-registration by default, but will only affect WordPress core once it is backported to `wordpress-develop` repo.

I recommend:
* Merging this PR now to make sure it's not overlooked later on
* **Not** backporting the Gutenberg PR for 6.2 

This way, the check will be enabled by default in 6.2 and enabled explicitly in 6.3.

Trac ticket: https://core.trac.wordpress.org/ticket/57795

### CODE REVIEW

**Comment by adamziel** [comment]
cc @gziolo @ntsekouras @hellofromtonya

**Review by gziolo — APPROVED** [review]
Yes, it looks like we can safely land it at any time. It won't take effect until WordPress packages are synced with the related changes. The change impacts only the build process.

**Comment by adamziel** [comment]
@hellofromtonya @peterwilsoncc let me know if you think this is suitable for merging, and if yes then I could make it my first commit.

**Comment by hellofromtonya** [comment]
@adamziel I marked the ticket for commit and assigned the commit to you. Go ahead with your first commit 🎉

**Review by peterwilsoncc — APPROVED** [review]

**Comment by adamziel** [comment]
Committed in https://core.trac.wordpress.org/changeset/55512/trunk – thank you everyone! 🎉

**Pull request closed without merging**
