### PR TITLE
Administration: Remove uses of contracted verb forms.

### PR DESCRIPTION
**Pull request by audrasjb**
Trac ticket: https://core.trac.wordpress.org/ticket/38913

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by hellofromtonya** [comment]
@audrasjb  the tests are failing as the strings changed. Mary Baum is reviewing the string changes to help me out. Once she's done and it's all okay, then the tests can be updated to match.

**Comment by audrasjb** [comment]
> @audrasjb the tests are failing as the strings changed. Mary Baum is reviewing the string changes to help me out. Once she's done and it's all okay, then the tests can be updated to match.

PR refreshed :)

**Comment by audrasjb** [comment]
@jeffpaul PR refreshed against trunk. It is available for final review :)

**Comment by audrasjb** [comment]
PR refreshed to replace "can not" with "cannot"

**Comment by audrasjb** [comment]
Committed

**Pull request closed without merging**
