### PR TITLE
Update terser webpack plugin

### PR DESCRIPTION
**Pull request by joemcgill**
Trac ticket: https://core.trac.wordpress.org/ticket/58660

**TESTING INSTRUCTIONS**

After applying this PR, run a new build locally by running `npm run build` (or `npm run build:dev` if you are running WP from `src`). Make sure `SCRIPT_DEBUG` is set to `false` in your `wp-config.php`, and load the block editor in the admin. It should load properly and no longer white screen.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by joemcgill** [comment]
I've overwritten the original change so that this PR excludes changes to the built PHP files that were originally present.

**Review by azaozz — APPROVED** [review]
Testing local builds in both /src and /build, all seems to work well with and without `SCRIPT_DEBUG`.

**Review by Clorith — APPROVED** [review]
Also applies cleanly here, and builds everything as expected gain 👍

**Comment by joemcgill** [comment]
This was added in https://core.trac.wordpress.org/changeset/56097.

**Pull request closed without merging**
