### PR TITLE
REST API: Improve the block type schema for the `name` field

### PR DESCRIPTION
**Pull request by gziolo**
Trac ticket: https://core.trac.wordpress.org/ticket/59346

The goal of this PR is to align the schema between `block.json` and the REST API endpoint for block types. It looks like the `name` field isn't validated in all places and if it uses pattern matching in the REST API code, then it's slightly different.

https://github.com/WordPress/gutenberg/blob/aa938166f28bcfff6c7b8d1caac5a95f78852f97/schemas/json/block.json#L26

https://github.com/WordPress/gutenberg/blob/f6d16f0b9f0a71d51c7178d35902c078b0d33c08/packages/blocks/src/api/registration.js#L231

I opted for using the same pattern as during block registration in JavaScript:

```php
'^[a-z][a-z0-9-]*/[a-z][a-z0-9-]*$'
```

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@gziolo Don't we need to regenerate this line -https://github.com/WordPress/wordpress-develop/blob/trunk/tests/qunit/fixtures/wp-api-generated.js

**Comment by gziolo** [comment]
> @gziolo Don't we need to regenerate this line -https://github.com/WordPress/wordpress-develop/blob/trunk/tests/qunit/fixtures/wp-api-generated.js

Do you mean we should also update the pattern used with URLs, like:

https://github.com/WordPress/wordpress-develop/blob/e413569b67d86608485d59a0b90898207eeb5067/tests/qunit/fixtures/wp-api-generated.js#L9931

or

https://github.com/WordPress/wordpress-develop/blob/e413569b67d86608485d59a0b90898207eeb5067/tests/qunit/fixtures/wp-api-generated.js#L9962

I executed all unit tests and this file hasn't changed. The comment included explains that the file is auto-generated with `test_build_wp_api_client_fixtures`.

**Comment by ockham** [comment]
Thank you! I'll have a closer look in a bit, but one thing I was wondering -- could we express the fact that the keys in `blockHooks` are block `name`s (as defined earlier in the schema) even more semantically (rather than using the same RegEx as a constant)? I've seen there's something called `$ref` in the JSON schema spec -- think that could work here? 🤔

**Comment by gziolo** [comment]
> I've seen there's something called `$ref` in the JSON schema spec -- think that could work here? 🤔 

There is a code comment included in the same method which suggests it can't be used:

https://github.com/WordPress/wordpress-develop/blob/e00f028a676490178b06f985cabe3d8dd8c5adc9/src/wp-includes/rest-api/endpoints/class-wp-rest-block-types-controller.php#L397

**Review by spacedmonkey — APPROVED** [review]
Looks good to me.

**Comment by gziolo** [comment]
Committed with [56676](https://core.trac.wordpress.org/changeset/56676).

**Pull request closed without merging**
