### PR TITLE
Add a filter to `wp_get_active_and_valid_themes()`

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://core.trac.wordpress.org/ticket/57928

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Closing in favor of https://github.com/WordPress/wordpress-develop/pull/4409

**Comment by szepeviktor** [comment]
Oh nooo! This was my favorite PR of 2023 🙃

**Comment by danielbachhuber** [comment]
> Oh nooo! This was my favorite PR of 2023

@szepeviktor How were you intending to use it?

**Comment by szepeviktor** [comment]
I'm not a WordPress user, just forced to live in the ecosystem.

**Review by szepeviktor — APPROVED** [review]

**Pull request closed without merging**
