### PR TITLE
The grammatical issue has been fixed in option.php

### PR DESCRIPTION
**Pull request by nazmulhudadev**
The mistake has been fixed.

Trac ticket: https://core.trac.wordpress.org/ticket/58338

### CODE REVIEW

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @nazmulhudadev, There is one more instance https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/option.php#L730 that need to be correct.

**Comment by nazmulhudadev** [comment]
Hi @mukeshpanchal27,

Thanks for reviewing the changes.

I've made the required changes in [line 730](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/option.php#L730) as well.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @nazmulhudadev, The changes look good to me.

**Review by krupal-panchal — APPROVED** [review]

**Comment by krupal-panchal** [comment]
@nazmulhudadev Found one more instance on https://github.com/krupal-panchal/wordpress-develop/blob/trunk/src/wp-includes/ms-blogs.php#L422

Also, address this.

**Comment by nazmulhudadev** [comment]
Hi @krupal-panchal,

Thanks for spotting the typo.
It has been fixed in a new PR https://github.com/WordPress/wordpress-develop/pull/4480

**Review by krupal-panchal — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
Merge the changes in https://github.com/WordPress/wordpress-develop/pull/4480 into this and close that PR.

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/55884

**Pull request closed without merging**
