### PR TITLE
Fix mismatched parameter names in child classes (Trac 51553 - task 1)

### PR DESCRIPTION
**Pull request by jrfnl**
This PR fixes all known instances of parameter name mismatches between methods in child classes vs the names used in the parent class.

Notes:
* Whenever the parameter name which was originally used in the method signature of the child class was significantly more descriptive than the parameter name used in the method signature of the parent class, the parameter name in the method signature has been changed, but an assignment to the "old" parameter name is made near the top of the function to keep the readability of the rest of the function code intact. This also reduces code churn.
* While doing these renames I noticed that a _lot_ of these functions violate the LISKOV principle by having covariant parameters, while parameters are supposed to be contravariant. This is outside the scope of this ticket, but is a concern.
    Ref: https://www.php.net/manual/en/language.oop5.variance.php

Trac ticket: https://core.trac.wordpress.org/ticket/51553

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by jrfnl** [comment]
Rebased for merge conflicts due to 5b6a20af07f7a34b1e20611a58741e20454cbd1a

**Comment by jrfnl** [comment]
@desrosj I would have happily rebased ...

**Comment by desrosj** [comment]
Sorry! I was actively reviewing so figured I'd just update to use the same PR. Updating the ticket soon!

**Review by hellofromtonya — APPROVED** [review]
I did a thorough deep code review multiple times during pair programming sessions with @jrfnl. The PR is ready for commit 👍

**Comment by hellofromtonya** [comment]
Each atomic commit as been committed with the following changesets https://core.trac.wordpress.org/log/?revs=51728,51734-51735,51737,51739,51779-51790

**Pull request closed without merging**
