### PR TITLE
Set default wp_global_styles

### PR DESCRIPTION
**Pull request by spacedmonkey**
Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
For reference, the issue now is this PHP warning when accessing the REST API:

```
<b>Warning</b>:  Undefined property: Gutenberg_REST_Global_Styles_Revisions_Controller_6_5::$parent_post_type
```

**Comment by getdave** [comment]
> Gutenberg_REST_Global_Styles_Revisions_Controller_6_5

I believe possibly because the extended class sets that property access to private

https://github.com/WordPress/wordpress-develop/blob/e9ab1c15b15bb0c369c87433122a1b0991a1a301/src/wp-includes/rest-api/endpoints/class-wp-rest-revisions-controller.php#L25

Exploring also in https://github.com/WordPress/gutenberg/pull/58972

**Comment by jonnynews** [comment]
This fixes the e2e tests - https://github.com/WordPress/wordpress-develop/pull/6105/commits/95db1e9e668861c48ed974dd6562c8d1c63adf7d

**Review by getdave — APPROVED** [review]
Testing with Gutenberg Plugin active as per original bug report I could not reproduce the original error with these changes in this PR.

Reverting those changes manually sees the error re-appear.

I also ended up coming up with much the same fix on Gutenberg repo so I'm fairly confident this is good.

**Comment by spacedmonkey** [comment]
Now that global controller changes have been reverted, we need a new patch that reapply them. To that end, here is the original PR with a fix applied. Closing this PR in favour of this https://github.com/WordPress/wordpress-develop/pull/6105

**Pull request closed without merging**
