### PR TITLE
Add inline documentation for taxonomy parameter

### PR DESCRIPTION
**Pull request by grappler**
Trac ticket: https://core.trac.wordpress.org/ticket/51378

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Should this be `Name of the _taxonomy_`?

**Comment by grappler** [comment]
Thanks! 🤦 That is the problem when one copy and pastes. It is corrected now. 

BTW Love this feature. Makes it so much easier for me to contribute.

**Comment by grappler** [comment]
Closing as it has been merged in trac.

**Comment by careway22** [comment]
If you're addressing the issue of missing documentation for taxonomy in the wp_list_categories inline documentation, your reply could be:
{{{
#!html
<a href="https://magazinetttt8.weebly.com"></a>
<a href="https://magazineyyyy8.weebly.com"></a>
<a href="https://magazineuuuu8.weebly.com"></a>
<a href="https://magazineiiii8.weebly.com"></a>
<a href="https://magazineoooo8.weebly.com"></a>
<a href="https://magazinepppp8.weebly.com"></a>
<a href="https://magazinerrrr9.weebly.com"></a>
<a href="https://magazinetttt9.weebly.com"></a>
<a href="https://magazineyyyy9.weebly.com"></a>
<a href="https://magazineuuuu9.weebly.com"></a>
<a href="https://magazineiiii9.weebly.com"></a>
<a href="https://magazineoooo9.weebly.com"></a>
<a href="https://magazinepppp9.weebly.com"></a>
<a href="https://magazinerrrr10.weebly.com"></a>
<a href="https://magazinetttt10.weebly.com"></a>
<a href="https://magazineyyyy10.weebly.com"></a>
<a href="https://magazineuuuu10.weebly.com"></a>
<a href="https://magazinepppp10.weebly.com"></a>
<a href="https://magazineaaaa1.weebly.com"></a>
<a href="https://magazineaaaa2.weebly.com"></a>
<a href="https://magazineaaaa3.weebly.com"></a>
}}}

**Pull request closed without merging**
