### PR TITLE
Sync packages for WP 6.1 RC 3

### PR DESCRIPTION
**Pull request by ockham**
Includes the latest round of Gutenberg bugfix PRs that were approved for inclusion during [yesterday’s triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1666627277005809). The following Gutenberg PRs were cherry-picked:

- https://github.com/WordPress/gutenberg/pull/45189
- https://github.com/WordPress/gutenberg/pull/45234
- https://github.com/WordPress/gutenberg/pull/45161
- https://github.com/WordPress/gutenberg/pull/45159
- https://github.com/WordPress/gutenberg/pull/45169
- https://github.com/WordPress/gutenberg/pull/45166
- https://github.com/WordPress/gutenberg/pull/45173
- https://github.com/WordPress/gutenberg/pull/45143
- https://github.com/WordPress/gutenberg/pull/44213
- https://github.com/WordPress/gutenberg/pull/44993
- https://github.com/WordPress/gutenberg/pull/44854
- https://github.com/WordPress/gutenberg/pull/45087
- https://github.com/WordPress/gutenberg/pull/45074

Furthermore, it includes the following fixes that were merged directly into Gutenberg's `wp/6.1` branch:

- https://github.com/WordPress/gutenberg/pull/45163
- https://github.com/WordPress/gutenberg/pull/45118
- https://github.com/WordPress/gutenberg/pull/45265

Needed for today's WP 6.1 RC 3 release.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by jeffpaul** [comment]
At a high-level, these items as described seem valid for RC3 but I'll defer to @desrosj @dream-encode @getsource and others on the release team for any technical concerns with the changes themselves

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by ockham** [comment]
I realize it's quite a large number of PRs again this time -- more than for [RC 2](https://github.com/WordPress/wordpress-develop/pull/3485) 😕 

FWIW, 5 of them add block deprecations that were previously missed:

- https://github.com/WordPress/gutenberg/pull/45161
- https://github.com/WordPress/gutenberg/pull/45159
- https://github.com/WordPress/gutenberg/pull/45169
- https://github.com/WordPress/gutenberg/pull/45166
- https://github.com/WordPress/gutenberg/pull/45173

Their absence would cause blocks saved in 6.0 to break in 6.1. Here's the relevant issue: https://github.com/WordPress/gutenberg/issues/45153

**Comment by ockham** [comment]
https://github.com/WordPress/gutenberg/pull/45087 only affects e2e tests in the GB repo -- it doesn't have any impact on code in Core. (It does [touch code in the `packages/e2e-test-utils-playwright` folder](https://github.com/WordPress/gutenberg/pull/45087/files#diff-d5c1429df0cd623c2e1f1c67f8cdb083140f2c29625019c80ac78a93eb50b0fc), but that package is [marked as private](https://github.com/WordPress/gutenberg/blob/f89007199d6a74b81cb0bfbd6972f9a3f926b29a/packages/e2e-test-utils-playwright/package.json) and hasn't been published to npm yet.)

It was needed on GB's `wp/6.1` branch for e2e tests to pass after https://github.com/WordPress/gutenberg/pull/45074 was merged.

**Comment by ockham** [comment]
https://github.com/WordPress/gutenberg/pull/45265 only affect's GB's "compatibility layer" with WP 6.0. That PR was needed for GB's own PHP unit tests to pass after I landed [r54670](https://core.trac.wordpress.org/changeset/54670/).

It also doesn't have any consequences for Core: The [corresponding code in Core](https://github.com/WordPress/wordpress-develop/blob/e33a49b1bd314e0f64402eaacf4cedf4919d9cd0/src/wp-includes/block-editor.php#L296-L372) was [previously updated](https://github.com/WordPress/wordpress-develop/commit/3381f05fa241daf172d6c1c893fd25959c3b0656#diff-edfc853e670c7bfc5a838dc74f75ba5d8b95cb4adbddf0644d9227bcb692e344).

**Comment by ockham** [comment]
Closing in favor of https://github.com/WordPress/wordpress-develop/pull/3527.

**Pull request closed without merging**
