### PR TITLE
Pin PHP at 8.2 for Performance Tests on the 6.4 branch

### PR DESCRIPTION
**Pull request by joemcgill**
Trac ticket: https://core.trac.wordpress.org/ticket/60127

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by joemcgill** [comment]
The Performance Tests [are passing](https://github.com/WordPress/wordpress-develop/actions/runs/9165243613/job/25198262479?pr=6587) with PHP pinned to 8.2.

**Review by speedyprem — APPROVED** [review]
Looks good to me

**Comment by joemcgill** [comment]
@desrosj, given the state of #6674 do you think we should commit this or wait and update the workflow in the 6.4 branch to use the new reusable workflow?

**Comment by desrosj** [comment]
Because this is a unique fix that has not yet been committed to `trunk`/a later branch, let's merge this separately and then follow up with the changes in #6674, and then #6385.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/58272.

**Pull request closed without merging**
