### PR TITLE
Administration: Update the background image for the Welcome Panel for 6.2

### PR DESCRIPTION
**Pull request by ryelle**
Updates the background image for the Welcome Panel to use the 6.2 style. This introduces a new file separate from the about header since the design is slightly different. The header is also updated to match each color scheme.

| Default | Modern (same as default) | Ocean | Ectoplasm |
|---|---|---|---|
| default | modern | ocean | ecto |

Trac ticket: https://core.trac.wordpress.org/ticket/57759

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ryelle** [comment]
I've flipped the background on RTL sites so that the green dot doesn't overlap the content. I'm not sure if the shapes are meant to be something that mirroring breaks, though, so just let me know if this solution needs work, @richtabor.

| Before | After |
|----|----|
| Screen Shot 2023-03-01 at 10 10 30 | Screen Shot 2023-03-01 at 10 09 22 |

**Comment by richtabor** [comment]
Works for me.

**Comment by richtabor** [comment]
We may need to tweak the coloring in the alternate color schemes, but I’m good for getting this in.

**Comment by ryelle** [comment]
Merged in [r55451](https://core.trac.wordpress.org/changeset/55451).

**Pull request closed without merging**
