### PR TITLE
Restore comma in `printf` for plugins list table

### PR DESCRIPTION
**Pull request by sabernhardt**
Combines markup on the same line and restores the comma removed in r56599.

[Trac 59590](https://core.trac.wordpress.org/ticket/59590)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by petitphp — APPROVED** [review]
PR looks good to me 👍

**Comment by petitphp** [comment]
@sabernhardt There are a lot of unrelated merge commits, can you try rebasing your branch to the latest version of trunk ?

**Comment by sabernhardt** [comment]
I tried rebasing within GitHub Desktop, but it did not change the PR. If it might help, I uploaded the diff from this PR.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @sabernhardt for the PR. LGTM!

**Comment by sabernhardt** [comment]
Committed in r56824

**Pull request closed without merging**
