### PR TITLE
Excluded individual files from the $_old_files array if their parent directories are already present.

### PR DESCRIPTION
**Pull request by shohel**
The implemented update ensures that when processing the $_old_files array, any individual files referenced within the array are excluded from deletion if their corresponding parent directories are already included. 

Trac ticket: https://core.trac.wordpress.org/ticket/58995

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by pbiron — CHANGES_REQUESTED** [review]
Thanx for the PR @shohel !!!

I think there are 2 more files that should be removed (L253-254, from WP 3.0):

        wp-includes/js/codepress/engines/khtml.js
        wp-includes/js/codepress/engines/older.js

Other than that, looks good!

**Comment by shohel** [comment]
@pbiron 

Hey Paul, thank you for noticing it, I've removed these two files as their parent `wp-includes/js/codepress` directory already exists

**Review by pbiron — APPROVED** [review]
LGTM!

**Comment by dream-encode** [comment]
@shohel Thanks for the PR!  Merged into core in https://core.trac.wordpress.org/changeset/57598.

**Pull request closed without merging**
