### PR TITLE
Upgrade/Install: Remove package signature verification until the feature is fully implemented.

### PR DESCRIPTION
**Pull request by audrasjb**
https://core.trac.wordpress.org/ticket/47315

### CODE REVIEW

**Review by speedyprem — APPROVED** [review]
Looking good

**Comment by peterwilsoncc** [comment]
@audrasjb Is the intent to remove the signature warning just from themes and plugins or are you intending to remove it from Core too? 

Core upgrades don't use the `run` method so if the intent is to remove the warning from there too I think this line will need changing too

https://github.com/WordPress/wordpress-develop/blob/13b571eeacf5a71e23c80d9f1d6b5cb5114e14af/src/wp-admin/includes/class-core-upgrader.php#L124

**Comment by audrasjb** [comment]
Thanks @peterwilsoncc. I added a commit to also take Core into account.

**Review by peterwilsoncc — APPROVED** [review]
This looks good to me, thanks JB.

I've tested the plugins updater and can confirm the message no longer displays.

Screen Shot 2024-06-04 at 8 53 45 am

I've not been able to test the core updater as I am unable to get to the screen -- I think that will need to be done once these changes are in the nightly release.

**Comment by audrasjb** [comment]
Thanks for the review! Committted in https://core.trac.wordpress.org/changeset/58319

**Pull request closed without merging**
