### PR TITLE
#52356 Use the `amd64/mysql` and `amd64/mariadb` images on arm64 machines

### PR DESCRIPTION
**Pull request by johnbillion**
Trac ticket: https://core.trac.wordpress.org/ticket/52356

### CODE REVIEW

**Comment by afragen** [comment]
I've tested this PR and it works on my M1 Mac. Thanks @johnbillion

**Comment by gziolo** [comment]
`npm run env:start` works great.

When I run `npm run env:install` I see the following error:

```
Status: Downloaded newer image for wordpressdevelop/cli:latest
Creating wordpress-develop-svn_cli_run ... done
ERROR 2002 (HY000): Can't connect to MySQL server on 'mysql' (115)
ERROR: 1
child_process.js:866
    throw err;
    ^

Error: Command failed: docker-compose run --rm cli config create --dbname=wordpress_develop --dbuser=root --dbpass=password --dbhost=mysql --path=/var/www/src --force
    at checkExecSyncError (child_process.js:790:11)
    at execSync (child_process.js:863:15)
    at wp_cli (/Users/gziolo/Projects/wordpress-develop-svn/tools/local-env/scripts/install.js:52:2)
    at Object.<anonymous> (/Users/gziolo/Projects/wordpress-develop-svn/tools/local-env/scripts/install.js:14:1)
```

Am I missing anything?

**Comment by johnbillion** [comment]
@gziolo Thanks for testing, that sounds like you're encountering https://core.trac.wordpress.org/ticket/50342 which is a bug unrelated to this change. If you run `npm run env:install` again it should work.

**Comment by gziolo** [comment]
> @gziolo Thanks for testing, that sounds like you're encountering https://core.trac.wordpress.org/ticket/50342 which is a bug unrelated to this change. If you run `npm run env:install` again it should work.

I can confirm it resolves the issue. All good in that case. I'm super excited about this patch, thank you so much 🎉

**Comment by gziolo** [comment]
Committed with https://core.trac.wordpress.org/changeset/53358 🎉

**Pull request closed without merging**
