### PR TITLE
Fix typos in `wp_admin_notice()` calls

### PR DESCRIPTION
**Pull request by dlh01**
Trac ticket: https://core.trac.wordpress.org/ticket/59830

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Nice catch.

**Comment by mukeshpanchal27** [comment]
Patch working fine:
Screenshot 2023-11-08 at 12 14 21 PM

**Comment by qasumitbagthariya** [comment]
Patch is working as expected.

Before:
Before


After:
image

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r57084](https://core.trac.wordpress.org/changeset/57084).

**Pull request closed without merging**
