### PR TITLE
External Libraries: Update Requests to version 2.0.11

### PR DESCRIPTION
**Pull request by swissspidy**
Trac ticket: https://core.trac.wordpress.org/ticket/60838

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
Just realized https://github.com/WordPress/wordpress-develop/commit/ed821528ee82a71078a491dfdbc30dfc8f7d7170 wasn’t synced back to Requests 🤔

**Review by jrfnl — APPROVED** [review]
@swissspidy Looked it over and have confirmed this is the patch needed for the 2.0.11 release. All good.

**Comment by jrfnl** [comment]
> Just realized [ed82152](https://github.com/WordPress/wordpress-develop/commit/ed821528ee82a71078a491dfdbc30dfc8f7d7170) wasn’t synced back to Requests 🤔

@schlessera and me have put that patch on the agenda for our next Requests call. Might need some work to bring the patch up to scratch (+ add tests), but once that's done we'll include it in the next release.

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/57876

**Comment by jrfnl** [comment]
Thanks @swissspidy !

**Pull request closed without merging**
