### PR TITLE
Fix: Undefined array key `attrs` warning.

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Trac ticket: https://core.trac.wordpress.org/ticket/59468

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by kafleg** [comment]
This PR works fine. I am not able to see the Warning now.

**Review by tellthemachines — APPROVED** [review]
I'm not sure how to reproduce the original issue, but code change LGTM! It's a good idea as a general principle to expect array keys to not exist 😄

**Comment by tellthemachines** [comment]
Committed in [r56731](https://core.trac.wordpress.org/changeset/56731).

**Comment by andrewserong** [comment]
Thanks for fixing this up, everyone!

**Pull request closed without merging**
