### PR TITLE
Upgrade/Install: Verify plugin packages during bulk upgrade.

### PR DESCRIPTION
**Pull request by costdev**
Previously, bulk upgrades did not verify that a plugin package was compatible with the site's WordPress version or the server's PHP version. This could lead to incompatible updates being installed, causing various compatibility issues and errors.

This change implements the following checks:
- If available, the API response's `requires` and `requires_php` values are checked for compatibility. This saves time, diskspace, memory and file operations by failing the upgrade before the package is downloaded and unpacked.
- If the API check passes, the downloaded and unpacked package is verified using `Plugin_Upgrader::check_package()` to ensure a plugin file is present, and the plugin's "RequiresWP" and "RequiresPHP" headers are compatible, if present. This ensures that an API/Plugin headers mismatch does not cause an incompatible plugin to be installed.

Trac ticket: https://core.trac.wordpress.org/ticket/59198

### CODE REVIEW

**Comment by afragen** [comment]
Tested locally and works.

**Review by SergeyBiryukov — APPROVED** [review]

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @costdev for the PR. Working fine for me.

**Review by johnbillion — APPROVED** [review]
@costdev Go for it

**Comment by costdev** [comment]
Committed in [56525](https://core.trac.wordpress.org/changeset/56525).

**Pull request closed without merging**
