### PR TITLE
Make sitemap.xml redirect more robust

### PR DESCRIPTION
**Pull request by swissspidy**
Trac ticket: https://core.trac.wordpress.org/ticket/61931

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
cc @pbiron

**Comment by andreilupu** [comment]
After testing this case I can confirm the issue on `wordpress:trunk` branch. With a custom permalink set, if I try to visit `http://localhost:8889/sitemap.xml` I get a redirect to the "404 - not found" template.

After switching to `swissspidy:fix/61931-sitemap-redirect` when I visit `http://localhost:8889/sitemap.xml` I get a redirect to  `http://localhost:8889/wp-sitemap.xml` and I can see the proper Sitemap template.

Good job! 👍

**Comment by peterwilsoncc** [comment]
Are you able to add a test case for the permalink structures noted in the ticket?

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/59228

**Pull request closed without merging**
