### PR TITLE
Add filters when rendering inner blocks

### PR DESCRIPTION
**Pull request by azaozz**
Add `pre_render_inner_block`, `render_inner_block_data`, and `render_inner_block_context` filters that run before an inner block is rendered.

Trac ticket: https://core.trac.wordpress.org/ticket/51612

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by azaozz** [comment]
This patch is similar to the original idea by @noisysocks https://github.com/WordPress/wordpress-develop/pull/691/commits/b04425a5d557ada359a1a7768cf1ba80e2d486bf only the filters are in `render()` and run before the inner WP_Block is instantiated (same as how they run for the top/parent WP_Block).

**Comment by draganescu** [comment]
This is actually a cool idea! 🚀

**Comment by noisysocks** [comment]
> This patch is similar to the original idea by @noisysocks [b04425a](https://github.com/WordPress/wordpress-develop/commit/b04425a5d557ada359a1a7768cf1ba80e2d486bf) only the filters are in `render()` and run before the inner WP_Block is instantiated (same as how they run for the top/parent WP_Block).

Clever! That addresses [the main criticism](https://github.com/WordPress/wordpress-develop/pull/691#issuecomment-724123869) of my original approach which was that the filters were being called in `WP_Block::__construct` and not `WP_Block::render`. Admittedly it breaks encapsulation to have one object mutate another, but I don't see why it should matter in practice, and both objects are of the same type.

> The filters have _inner in the name to distinguish them from the top block's filters. The same context could also be provided in a different way, perhaps. Ideas welcome :)

I do not like this. It creates extra work for plugin developers as they'll have to define two filters instead of one. Blocks should work the same way regardless of whether they’re nested inside another block or not.

**Comment by azaozz** [comment]
Hmm, tests seem to fail globally at the moment, something about mismatched cert. https://github.com/WordPress/wordpress-develop/pull/1684/commits/80695cfd4f0a439e931755fa12d5f5cee8797b43 should be fine, tests pass locally.

**Comment by azaozz** [comment]
> it breaks encapsulation to have one object mutate another, but I don't see why it should matter in practice

Right, to get to the inner blocks you'll need to render the top/parent block. However there's a `pre_render_block` filter meant to short-circuit the rendering including any inner/nested blocks, so the results can be very different if that filter is not applied. Not sure we can do anything to avoid/daly running that filter...

> I do not like this. It creates extra work for plugin developers as they'll have to define two filters instead of one. Blocks should work the same way regardless

Yeah, devs will have to use both "top" and "inner" filters. Having a different name makes it very clear the currently filtered block is inner. Blocks should work the same way bit they don't, and most look very differently when nested. Also was thinking it may be useful to pass some more context to the inner filters, but may be redundant.

Updated the PR and changed the filter names to match. Context is provided by adding another param: `$parent_block` which is null for top level blocks. That should be enough for inner blocks imho.

**Comment by draganescu** [comment]
> Blocks should work the same way but they don't, and most look very differently when nested.

I think this point is valid, maybe "some" not "most", but it's a little inconvenience that I think adds more control IMO.

**Comment by noisysocks** [comment]
Yes but often the reason a block looks different when nested is only due to styling. The HTML will be the same. The most common use case for these filters is to slightly change the HTML. I think that plugin developers and theme developers will expect that the filters do this regardless of whether the block is nested or not.

> Updated the PR and changed the filter names to match. Context is provided by adding another param: $parent_block which is null for top level blocks. That should be enough for inner blocks imho.

I agree. Perfect 🙂

**Review by noisysocks — APPROVED** [review]
Code and approach LGTM and this tests well locally 👍

Might want to consider adding a unit test to `tests/phpunit/tests/blocks/wpBlock.php`.

**Comment by azaozz** [comment]
Fixed in https://core.trac.wordpress.org/changeset/51894.

**Pull request closed without merging**
