### PR TITLE
Change default value of settings.shadow.defaultPresets to false

### PR DESCRIPTION
**Pull request by t-hamano**
This PR is a follow-up to #6178.

[The original Gutenberg PR](https://github.com/WordPress/gutenberg/pull/58766) had a change made to `theme.json`, but #6178 did not include it.

Trac ticket: https://core.trac.wordpress.org/ticket/60633

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by vcanales — APPROVED** [review]
Thanks for catching this. LGTM

**Review by madhusudhand — APPROVED** [review]
I apologize for the oversight in the initial pull request. I've reviewed the changes, and they look good to me. Thank you for taking care of this.

**Comment by swissspidy** [comment]
What are the testing instructions for this?

**Comment by youknowriad** [comment]
The testing instructions should be something like:

 - Use a classic theme that doesn't have a theme.json or doesn't have `appearanceTools: true` in its theme.json.
 - The shadow controls shouldn't appear on the inspector control (sidebar) of the button block.

**Review by swissspidy — APPROVED** [review]

**Comment by swissspidy** [comment]
Thanks @youknowriad, I can confirm this then 👍

**Comment by t-hamano** [comment]
> - Use a classic theme that doesn't have a theme.json or doesn't have appearanceTools: true in its theme.json.
> - The shadow controls shouldn't appear on the inspector control (sidebar) of the button block.

Thank you. This is correct.

**Comment by swissspidy** [comment]
Committed to trunk in https://core.trac.wordpress.org/changeset/57827

Needs double sign-off (`dev-reviewed`) from another committer for backporting to 6.5

**Comment by youknowriad** [comment]
Added the "dev-reviewed" tag. This LGTM

**Pull request closed without merging**
