### PR TITLE
Fixed Typo in wp_parse_url() description

### PR DESCRIPTION
**Pull request by mehedifoysal**
Trac ticket: https://core.trac.wordpress.org/ticket/55355

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mehedifoysal** [comment]
Hi @SergeyBiryukov, I'm working on your ticket. As I am new I could use some feedback if this is the correct way.?

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍  Ready for commit

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! This looks good to me as well, I've just pushed some minor formatting adjustments for better readability.

**Comment by hellofromtonya** [comment]
Thanks @SergeyBiryukov for further improvements. Prepping commit now.

**Comment by hellofromtonya** [comment]
Committed via changeset https://core.trac.wordpress.org/changeset/52838

Thank you @mehedifoysal! Congrats on your first Core contribution 🎉

**Pull request closed without merging**
