### PR TITLE
Update packages for 5.9.3

### PR DESCRIPTION
**Pull request by Mamaduka**
Updated packages:

```
 - @wordpress/block-directory@3.0.29
 - @wordpress/block-library@6.0.28
 - @wordpress/customize-widgets@2.0.29
 - @wordpress/edit-post@5.0.29
 - @wordpress/edit-site@3.0.29
 - @wordpress/edit-widgets@3.1.24
```

Trac ticket: https://core.trac.wordpress.org/ticket/55474

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by Mamaduka** [comment]
Do not merge this; the `package-lock.json` has too many changes.

**Comment by Mamaduka** [comment]
@audrasjb, it looks like the previous package update was only [committed](https://github.com/WordPress/wordpress-develop/commit/c78c8761731ead09562cf1e30d00bddaec405d18) into the `5.9` branch.

I see two options here:

A) We can cherry-pick this commit into the trunk and follow the default git flow.
B) I can checkout and create PR for the `5.9` branch.

Let me know which option do you prefer.

**Comment by audrasjb** [comment]
@Mamaduka hmm I'm not 100% sure we only want to commit this to branch 5.9.
In 5.9.1 we also updated packages for trunk: https://core.trac.wordpress.org/changeset/52765

**Comment by Mamaduka** [comment]
@audrasjb correct, but we forgot to do the same for 5.9.2.

Should we go with option A?

I can also try updating packages in two steps, bump for 5.9.2 and then 5.9.3.

**Comment by audrasjb** [comment]
I pinged @jorgefilipecosta who handled packages updates for the 5.9.2 security release, just to confirm we're making the right decision :)

**Comment by Mamaduka** [comment]
After discussing the issue with @jorgefilipecosta, I went with option B.

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/53030

**Pull request closed without merging**
