### PR TITLE
`WP_Automatic_Updater`: Limit directory traversal when checking for VCS.

### PR DESCRIPTION
**Pull request by costdev**
Trac ticket: https://core.trac.wordpress.org/ticket/42619

### CODE REVIEW

**Comment by costdev** [comment]
The following do not work:
- Storing the original value in `$open_basedir_backup` then using `ini_set( 'open_basedir', $open_basedir_backup )`
- `ini_restore()`
- `ini_set( 'open_basedir', '' )`
- `ini_set( 'open_basedir', '/' )`

Any ideas?

**Comment by costdev** [comment]
When attempting to reset the `open_basedir` PHP directive in the test, the following do not work:
- Storing the original value in `$open_basedir_backup` then using `ini_set( 'open_basedir', $open_basedir_backup )`
- `ini_restore( 'open_basedir' )`
- `ini_set( 'open_basedir', '' )`
- `ini_set( 'open_basedir', '/' )`

Any ideas?

**Comment by costdev** [comment]
Update: I've added two additional tests to the PR that use `@runInSeparateProcess` and `@preserveGlobalState disabled` to allow for testing the `open_basedir` PHP directive. The docblock for the test methods explains why these annotations are used for these.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r55425](https://core.trac.wordpress.org/changeset/55425).

Note:
* I have slightly modified the two tests for the `open_basedir` directive, as they failed on my setup with multiple checkouts and a symlink to the `vendor` directory in the “primary” checkout. There were some issues with PHPUnit along the lines of:
```
Warning: include(): open_basedir restriction in effect. File(S:\home\wordpress.test\develop-trunk\vendor\phpunit\phpunit\src\Framework\TestFailure.php) is not within the allowed path(s): (S:\home\wordpress.test\develop-test/;S:\home\wordpress.test\develop-test/src/) in S:\home\wordpress.test\develop-trunk\vendor\composer\ClassLoader.php on line 444
Warning: include(S:\home\wordpress.test\develop-trunk\vendor\phpunit\phpunit\src\Framework\TestFailure.php): Failed to open stream: Operation not permitted in S:\home\wordpress.test\develop-trunk\vendor\composer\ClassLoader.php on line 444
Warning: include(): Failed opening 'S:\home\wordpress.test\develop-trunk\vendor\composer/../phpunit/phpunit/src/Framework/TestFailure.php' for inclusion (include_path='.;C:\php\pear') in S:\home\wordpress.test\develop-trunk\vendor\composer\ClassLoader.php on line 444
Class "PHPUnit\Framework\TestFailure" not found
```
* I have also removed the error suppression operator from the `is_dir()` call, which was added in [r25764](https://core.trac.wordpress.org/changeset/25764) as a workaround for the same issue, and should no longer be necessary with this commit.

**Pull request closed without merging**
