### PR TITLE
Update Google Fonts collection data url for 6.7 release

### PR DESCRIPTION
**Pull request by matiasbenedetto**
## What?
The current Google font collection data is not up-to-date, with the latest additions to the list of available fonts and the latest versions of the existing ones. This PR updates the URL of the new file hosted on the WordPress.org CDN https://meta.trac.wordpress.org/ticket/7808 (pending).

## Why?
To update the Google fonts collection data with the latest fonts and versions of those fonts.

## Trac
Trac ticket: https://core.trac.wordpress.org/ticket/62258

---
These are some links for reference only.

Issues:
https://github.com/WordPress/gutenberg/issues/64685
https://github.com/WordPress/google-fonts-to-wordpress-collection/issues/34
https://core.trac.wordpress.org/ticket/62258
https://meta.trac.wordpress.org/ticket/7808

Data updates:
https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/38
https://github.com/WordPress/google-fonts-to-wordpress-collection/pull/40

### CODE REVIEW

**Review by peterwilsoncc — COMMENTED** [review]
LGTM, thanks Matias.

I'll hold off clicking approve so I can test against w.org once the upstream commit is made.

**Review by peterwilsoncc — APPROVED** [review]
LGTM.

In testing, I confirmed the presence of the Zain font to validate that WordPress was hitting the updated endpoint.

**Comment by peterwilsoncc** [comment]
Merged [r59286](https://core.trac.wordpress.org/changeset/59286) / https://github.com/WordPress/wordpress-develop/commit/c374a1bbc8ca66989bf7793f2849e8624575aea5

**Comment by ockham** [comment]
Thanks a lot for taking care of this, @matiasbenedetto and @peterwilsoncc!

**Pull request closed without merging**
