### PR TITLE
Remove duplicate call to `locate_block_template()`

### PR DESCRIPTION
**Pull request by dlh01**
Trac ticket: https://core.trac.wordpress.org/ticket/58299

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
I ran a profiling test against the current trunk, and it showed that removing some function calls improved performance. This might be of interest to @felixarntz, @spacedmonkey, @eclarke1, and @joemcgill.

Screenshot 2023-06-19 at 12 12 19 PM

**Comment by spacedmonkey** [comment]
@ockham  Do you mind providing some context why this function needs to called twice?

**Comment by ockham** [comment]
I looked around a bit, and this looks indeed like an oversight. As I said in this [comment](https://core.trac.wordpress.org/ticket/58299#comment:8) on the corresponding Trac ticket: 

>> Adding `locate_block_template()` as a filter on `{$type}_template` would have been necessary in the Gutenberg plugin, but not in core, given the call that was added directly to `get_query_template()`.
> 
> This seems like a plausible explanation; we might've overlooked the filters when backporting the code from Gutenberg to Core.

To unfurl the call stack a bit: The code that this PR removes loops over all template types and [adds  `locate_block_template` as a filter to all their corresponding `{$type}_template` hooks](https://github.com/WordPress/wordpress-develop/pull/4443/files#diff-a0147faba3a7610c1d7961955d1dd3a111ac0bd196353e6042d5aa187273d29eL25) (e.g. `home_template`, `single_template`, etc). The [`{$type}_template` filters](https://developer.wordpress.org/reference/hooks/type_template/) are only being applied in one spot: https://github.com/WordPress/wordpress-develop/blob/88de9a9d8efe13a21ebdcdfbf6f87d78875c8f0e/src/wp-includes/template.php#L103

The LOC _directly before that line_ (and its comment block) is the "other" call to `locate_block_template()`, passing the same arguments: https://github.com/WordPress/wordpress-develop/blob/88de9a9d8efe13a21ebdcdfbf6f87d78875c8f0e/src/wp-includes/template.php#L66

So it looks pretty safe indeed to remove the filters from the hook! I've done a bit of smoke testing, and things seem to continue to work fine.

**Review by ockham — APPROVED** [review]
Nice find @dlh01 😄 

As elaborated in [my comment](https://github.com/WordPress/wordpress-develop/pull/4443#issuecomment-1608097969), I think this is safe to land :shipit:

**Review by felixarntz — COMMENTED** [review]
@dlh01 Can we add a PHPUnit test (pretty much an integration test) to ensure this doesn't break the template loading logic?

**Comment by dlh01** [comment]
Apologies, @felixarntz, but could you elaborate about the template-loading outcome(s) that should be tested?

**Comment by felixarntz** [comment]
@dlh01 Fair question. Taking another look, this change is probably irrelevant to any testing.

However, as far as I can tell there are no tests at all for the block template specific bits of the `get_query_template()` function. This is not strictly responsibility of a PR like this, but those should have been added whenever the `locate_block_template()` call was added to `get_query_template()`.

To unblock this PR, I'm happy to approve this, but it would be great if you could use a separate PR to add at least some basic test coverage to ensure that `get_query_template()` returns the expected result for some block templates use-cases, as otherwise we can't really make such changes safely, without test coverage.

**Comment by dlh01** [comment]
Sure thing! I'll open a new ticket when I have those tests ready.

**Review by spacedmonkey — APPROVED** [review]

**Comment by spacedmonkey** [comment]
Committed https://github.com/WordPress/wordpress-develop/commit/02ea2f1d75a77d014708fd0d38677e85065742e9

**Pull request closed without merging**
