### PR TITLE
Simplify initialization of `WP_Block_Parser::$empty_attrs`

### PR DESCRIPTION
**Pull request by dlh01**
Trac ticket: https://core.trac.wordpress.org/ticket/59168

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@dlh01 I like this change. But I would remove the changes to docs. We can do this elsewhere and it does not need to block this change.

**Comment by dlh01** [comment]
@spacedmonkey OK, I removed the docs changes and will submit them separately.

**Comment by dmsnell** [comment]
This change was applied to Gutenberg in WordPress/gutenberg#54424.
Follow-up is taking place in WordPress/gutenberg#54496.

Should this be done separately or come through via an update to the Gutenberg packages? cc: @mcsf

**Comment by spacedmonkey** [comment]
Fixed upstream.

**Pull request closed without merging**
