### PR TITLE
#56703 - Bump jQuery.scrollTo 2.1.2 > 2.1.3

### PR DESCRIPTION
**Pull request by sarahricker**
Trac ticket: https://core.trac.wordpress.org/ticket/56702
Updating scrollTo jQuery plugin included in Twenty Seventeen, from version 2.1.2 to version [2.1.3](https://github.com/flesler/jquery.scrollTo/releases/tag/v2.1.3).

**Testing Note:** 
In 2.1.3, jQuery.isFunction is removed since it has been deprecated.
[A full list of changes can be found on GitHub](https://github.com/flesler/jquery.scrollTo/compare/2.1.2...v2.1.3).

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by desrosj — CHANGES_REQUESTED** [review]
Thanks for the PR @sarahricker!

I'm seeing a lot more changes than the library update actually shows ([diff](https://github.com/flesler/jquery.scrollTo/compare/2.1.2...v2.1.3#diff-8aace416b4e45f8e0047614e75d85de9b78ff7664226daa58c21ebc3899412a2)). I think your editor may be auto-applying some JavaScript coding standards changes on paste (if that was how you updated the file).

Could you try copying the file without any of those changes so the diff more closely matches the one linked above?


Also, the version specified in the `wp_enqueue_script()` call in `functions.php` also needs to be updated.

**Comment by sarahricker** [comment]
Thanks @desrosj! The reason for the excessive changes is actually that we don't seem to have a true copy of 2.1.2. If you checkout before commit  [18fb646](https://github.com/WordPress/wordpress-develop/pull/3381/commits/18fb6461f45a8547022d98eecb69b7744f00e9fd) and compare our version to the file in [jquery.scrollTo/releases/tag/2.1.2](https://github.com/flesler/jquery.scrollTo/releases/tag/2.1.2) and run a diff, there is quite a difference. ☹️ 

As such, we should probably do some extra testing to be sure other stuff isn't breaking. But, it's probably good to get the true version in there - what do you think?

I'll work on updating the version specified in the wp_enqueue_script() call in functions.php in the meantime. Thanks for the catch!

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @sarahricker LGTM

**Review by desrosj — APPROVED** [review]
@sarahricker Ah! That makes more sense then why there are extra changes. The library copies in Core should always be exact copies whenever possible.

Since the other changes are strictly white space related, I think this should be pretty low risk to include.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/54374.

**Comment by sarahricker** [comment]
Awesome, thanks!

**Pull request closed without merging**
