### PR TITLE
Reduce specificity of global styles and layout selectors.

### PR DESCRIPTION
**Pull request by tellthemachines**
Trac ticket: https://core.trac.wordpress.org/ticket/61165

Syncs changes from https://github.com/WordPress/gutenberg/pull/60106, https://github.com/WordPress/gutenberg/pull/60228 and https://github.com/WordPress/gutenberg/pull/61340.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by tellthemachines** [comment]
Just realised that changes from #6489 are likely to conflict with these, especially the test string updates, so I might hold off on updating this one until #6489 is committed.

**Comment by tellthemachines** [comment]
PHP tests are updated, so marking this ready for review!

**Comment by aaronrobertshaw** [comment]
There are some proposed changes to specificity in https://github.com/WordPress/gutenberg/pull/61638 and a [general consensus](https://github.com/WordPress/gutenberg/discussions/61810) to proceed with those changes for WP6.6.

Given the tight timeline until the 6.6 beta I've put together a [separate draft PR](https://github.com/WordPress/wordpress-develop/pull/6633) bringing together all the specificity changes from the following PRs:

- https://github.com/WordPress/gutenberg/pull/60106
- https://github.com/WordPress/gutenberg/pull/60228
- https://github.com/WordPress/gutenberg/pull/61340
- https://github.com/WordPress/gutenberg/pull/61638

Once they settle that could be rolled into this PR or the core ticket updated to point to the alternate backport.

**Comment by tellthemachines** [comment]
Closing in favour of #6633.

**Pull request closed without merging**
