### PR TITLE
Global Styles: Invalidate global block styles cache on style change

### PR DESCRIPTION
**Pull request by aaronrobertshaw**
This PR is an initial pass at preventing stale global block styles from being rendered on the frontend in 6.6

#### Problem

Caching was recently added to the global block styles in `wp_add_global_styles_for_blocks`, this was keyed only on the block name or metadata meaning the cached styles were returned even if the styles had recently changed.

#### Proposed Solution

Cache the global block styles using a hash of the style data as well.

#### Steps to replicate issue on trunk

Copied from [#71](https://core.trac.wordpress.org/ticket/59595#comment:71)

1. Open the site editor on a WP 6.6 RC3 site running Twenty Twenty Four theme
2. Click the editor preview to go into edit mode
3. Open the Global Styles sidebar panel on the right hand side
4. Click Blocks
5. Select the Button block
6. Give the Button block a style, e.g. Background color set to a gradient
7. Save the global styles
8. Load the site frontend — notice that the styling on the Button is applied
9. Go back to global styles and give the Button block another style, e.g. large font size
10. Save the global styles
11. Load the site frontend and notice that the Button block's styling has not changed — it'll be cached with the previous styles that were originally saved

#### Test Instructions

1. Checkout this PR and repeat the steps above. This time the styles should update appropriately
2. Confirm that the cache is still used when styles haven't changed.

Trac ticket: https://core.trac.wordpress.org/ticket/59595

Props go to @tellthemachines for isolating the cause and @andrewserong for his assistance in debugging also.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by aaronrobertshaw** [comment]
I'll be AFK for a couple of days. So please feel free to push changes, rework, or discard this PR. It's only meant to help find a possible solution for 6.6.

**Comment by tellthemachines** [comment]
I gave this a quick test run on my local and this does seem to fix the issue!

**Review by joemcgill — CHANGES_REQUESTED** [review]
Thanks, @aaronrobertshaw! This indeed fixes the bug, but splits the responsibility of cache busting in two separate places—the hash added to the transient name, and also to the block node keys stored in the cache. I'd prefer that the responsibility for cache invalidation be handled in one place.

I've proposed an alternative in #6879 that I think will fix this as well, which I'd appreciate feedback on.

**Comment by aaronrobertshaw** [comment]
Closing in favour of https://github.com/WordPress/wordpress-develop/pull/6879

**Pull request closed without merging**
