### PR TITLE
Coding Standards: Add visibility to methods in `tests/phpunit/tests/` T-U-W-X files.

### PR DESCRIPTION
**Pull request by costdev**
Coding Standards: Add visibility to methods in `tests/phpunit/tests/` T-U-W-X files.

"Visibility should always be declared"
See: https://make.wordpress.org/core/2020/03/20/updating-the-coding-standards-for-modern-php/

This commit applies the following sniffs to files in `tests/phpunit/tests` T-U-W-X directories:
- Squiz.Scope.MethodScope
- PSR2.Methods.MethodDeclaration
- PSR2.Classes.PropertyDeclaration
- Squiz.WhiteSpace.ScopeKeywordSpacing

For most methods, these now indicate `public` visibility to avoid breaking backwards compatibility.
Any remaining methods now indicate `private` visibility where appropriate.

Additional fixups in this PR:
1. Methods touched by this PR have had unnecessary underscores removed from their names.

Trac ticket: https://core.trac.wordpress.org/ticket/54177

### CODE REVIEW

**Review by hellofromtonya — APPROVED** [review]
Looks good 👍 Ready for `commit`.

**Comment by hellofromtonya** [comment]
@costdev Can you rebase with `master` to resolve these conflicts please? Then it'll be ready to go.

**Comment by costdev** [comment]
@hellofromtonya There was a failure on [WP_REST_Block_Directory_Controller_Test::test_get_items](https://github.com/WordPress/wordpress-develop/runs/4101681393?check_suite_focus=true#step:17:78), but passes for me locally. Might just need a re-run.

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/52010.

**Pull request closed without merging**
