### PR TITLE
Allow opting out of block patterns

### PR DESCRIPTION
**Pull request by youknowriad**
Trac ticket: https://core.trac.wordpress.org/ticket/50669

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by youknowriad** [comment]
@desrosj That's a good point, that said, this is a pattern already used for several theme supports, I fear the inconcistency a little bit.

**Comment by youknowriad** [comment]
I pushed a commit with your proposal.

**Comment by desrosj** [comment]
Ya, I'd prefer to not add more `disable-*` features if possible. It looks like there are currently 2 supported. Looking at deprecating those in favor of more clear options may be worthwhile.

Looking through Core, there are currently no theme features added by default without a related function being called ([`add_editor_style()`](https://github.com/WordPress/wordpress-develop/blob/b00172339467889b736cf0a8d0a7bc5a502b1158/src/wp-includes/theme.php#L2037) and [`register_nav_menus()`](https://github.com/WordPress/wordpress-develop/blob/a9368a89e527e9857245381e1047fc97148708c9/src/wp-includes/nav-menu.php#L90) are examples of that pattern). Not sure if there is a way to use this pattern instead.

A third option we have is using a short-circuit filter.
```
$filter_result = apply_filters( 'support_core_block_patterns', true );
if ( ! $filter_result ) {
    return;
}
```

Returning any "falsey" value will disable the function. This is also a pattern used throughout Core ([`wp_maybe_load_widgets()` ](https://github.com/WordPress/wordpress-develop/blob/efb0b5859837eef6b3a6badb397df80c85add6ee/src/wp-includes/functions.php#L4615)is one example). This would mean changing the function to `wp_maybe_register_block_patterns()`, but it wouldn't necessarily help inform theme developers declare support for block patterns.

**Comment by youknowriad** [comment]
I think the current pattern applied on this PR is growing on me. Something like `add_editor_style()` would work if the "support" applied to all patterns, not just core ones. And the filter solution doesn't look semantic enough.

**Comment by youknowriad** [comment]
About the current "disable-" theme supports, hopefully, these will be replaced with theme.json file when global styles land.

**Comment by desrosj** [comment]
> About the current "disable-" theme supports, hopefully, these will be replaced with theme.json file when global styles land.

As an aside, I'd love to see examples of this and how the server would remain aware of support for various features.

> I think the current pattern applied on this PR is growing on me. Something like `add_editor_style()` would work if the "support" applied to all patterns, not just core ones. And the filter solution doesn't look semantic enough.

What if we just removed `core-` from the feature name? ~Thinking out loud, we could also allow the specific block patterns supported to be passed to the theme support feature similar to how the HTML5 and custom logo features accept arguments,~ actually, this would just replicate the `register_block_pattern()` function.

**Comment by nosolosw** [comment]
:wave: I gave this a spin:

- I wonder if there's a need to selectively enable patterns instead of an on/off switch? If so, we could provide a filter others can hook into:
  - Want to disable all patterns? Return an empty array from the filter.
  - Want to enable a few of them? Return an array with the patterns you want to be enabled.

- I can't get this patch to work. The patterns aren't registered so they aren't shown in the inserter. Perhaps when the block-patterns.php file loads it's too late to declare theme support? I'm not familiar with how that works, but I also haven't seen any example of using theme support outside the theme's functions.php file (even functions that use `add_theme_support` like `register_nav_menus` are meant to be called within the theme's functions.php) so thought I'd mention it.

**Comment by youknowriad** [comment]
> I can't get this patch to work. The patterns aren't registered so they aren't shown in the inserter.

it worked well on my testing but i'll give it a second check to confirm.

> I wonder if there's a need to selectively enable patterns instead of an on/off switch? If so, we could provide a filter others can hook into:

This is already available as you can register/unregister patterns selectively. What was missing is for themes that don't want core patterns entirely and want to provide their own.

**Comment by youknowriad** [comment]
> Want to enable a few of them? Return an array with the patterns you want to be enabled.

This solution also has a downside of making it harder for Core to remove existing patterns in the future. While it's already delicate, I think we shouldn't be making it harder for backward compatibility.

**Comment by youknowriad** [comment]
@nosolosw Good catch on the bug, the condition was actually inverted (lingering from the initial implementation). It should be better now.

**Comment by nosolosw** [comment]
Ah, I see, so the goal is to provide a mechanism that opt-outs from current and future block patterns provided by core (instead of doing it selectively like `unregister_block_pattern( 'core/pattern-name-1' ); etc`. Got it :+1:

**Pull request closed without merging**
