### PR TITLE
Use filesystem classes for move_dir().

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/57375

https://core.trac.wordpress.org/ticket/57386

Not sure which is best.

### CODE REVIEW

**Comment by azaozz** [comment]
Yep, agree this looks a bit cleaner than having "external" `move_dir()` function. Maybe even the `move()` functions in `WP_Filesystem_*` should be updated to handle directories? Maybe a bit tricky to handle the `$overwrite` param there though. It is `false` by default which perhaps should default to "merging" the content of directories?

Looking at the changes, wondering if `wp_opcache_invalidate_directory()` should also be part of `WP_Filesystem_Base`? (Perhaps can skip the `wp_` prefix then). 

Another thing: seems `wp_opcache_invalidate_directory()` should run after `move_dir()` no matter which filesystem method was used (FTP, SSH, etc.)?

**Comment by peterwilsoncc** [comment]
> Maybe even the `move()` functions in `WP_Filesystem_*` should be updated to handle directories?

Coincidentally, I've just been discussing this very thing with @costdev. 

Apparently `move` handles both files and directories in the other file systems, just not the direct file system.

**Comment by costdev** [comment]
> @azaozz Maybe even the move() functions in WP_Filesystem_* should be updated to handle directories?

The `::move()` methods for `WP_Filesystem_FTPExt`, `WP_Filesystem_ftpsockets` and `WP_Filesystem_SSH2` already support moving directories. The original intent of the `::move()` methods seems to be to support moving files. However, the non-direct filesystem classes happen to use commands that support both files and directories.

The additional `move_dir()` methods aren't necessary for the other filesystem classes and would be more code for us to maintain in the long run. IMHO, if the preference is to bring this functionality at the class level, then updating `WP_Filesystem_Direct::move()` to add this functionality is the most appropriate way doing this.

> Maybe a bit tricky to handle the $overwrite param there though. It is false by default which perhaps should default to "merging" the content of directories?

For PHP's `rename()`:
- Files: Can overwrite existing files.
- Directories: Will emit a warning for an existing directory.

Therefore, we can still use `$overwrite` with a default to `false`, but we need to have a condition like this after the `if ( ! $overwrite... )` condition:
```php
if ( $this->is_dir( $source ) && $this->is_dir( $destination ) ) {
	$this->delete( $destination, true );
}
```

> Looking at the changes, wondering if wp_opcache_invalidate_directory() should also be part of WP_Filesystem_Base? (Perhaps can skip the wp_ prefix then).

With `wp_opcache_invalidate()` being a general function, I'm not sure it's worth making the directory equivalent a class method. That said, there's no reason why we couldn't have both, with the general functions being wrappers for the class-level, but that seems like another ticket down the road.

> Another thing: seems wp_opcache_invalidate_directory() should run after move_dir() no matter which filesystem method was used (FTP, SSH, etc.)?

Indeed, and the same goes for `wp_opcache_invalidate()` when used on single files. #3798 runs this [here](https://github.com/WordPress/wordpress-develop/blob/3f3a36137131d26ad3d45b641368c48c8d0ea7c9/src/wp-admin/includes/file.php#L1999) no matter the filesystem method.

That said, are we sure there's no use for a general `move_dir()` function? We have a `copy_dir()` function available to extenders, and a `move_dir()` function may be useful too. If there's a desire to have `move_dir()`, should we be making a decision that affects the filesystem classes at this stage, or is it an opportunity a future enhancement where we could make both `copy_dir()` and `move_dir()` wrappers for filesystem class methods?

**Comment by costdev** [comment]
> > Maybe even the `move()` functions in `WP_Filesystem_*` should be updated to handle directories?
> 
> Coincidentally, I've just been discussing this very thing with @costdev.
> 
> Apparently `move` handles both files and directories in the other file systems, just not the direct file system.

Some information on this that I posted in the Upgrade/Install channel yesterday:
- `WP_Filesystem_FTPExt::move()` - [ftp_rename](https://www.php.net/manual/en/function.ftp-rename.php) - "Renames a file or a directory on the FTP server"
- `WP_Filesystem_ftpsockets::move()` - [$this->ftp->rename](https://github.com/costdev/wordpress-develop/blob/0412d30a33b0e630d2dc4a1657c539147991c8ac/src/wp-admin/includes/class-ftp.php#L410) - Uses `RNFR`/`RNTO` which work on files and directories.
- `WP_Filesystem_SSH2::move()` - [ssh2_sftp_rename ](https://www.php.net/manual/en/function.ssh2-sftp-rename.php)- Ultimately calls [sftp_rename](https://github.com/libssh2/libssh2/blob/bd9c65d68c4152ba0726f5588b4b611410972fbc/src/sftp.c#L2800) (C).

While the last one states "Rename a file on the remote server", search for "Removing and Renaming Files" on [this link](http://www.openssh.com/txt/draft-ietf-secsh-filexfer-02.txt), which states:
> Files (and directories) can be renamed using the SSH_FXP_RENAME message.

Which, as you can [see here](https://github.com/libssh2/libssh2/blob/bd9c65d68c4152ba0726f5588b4b611410972fbc/src/sftp.c#L2839), is what libssh2's `sftp_rename()` function uses.

So non-direct filesystems already have directories covered. It was the direct filesystem that lacked this specific behaviour, via `rename()` with no deletion of an existing directory. `WP_Filesystem_Direct::move()` isn't suitable as it falls back to `::copy()`, which only works for files, not directories. Hence, `copy_dir()` and now `move_dir()`.

**Comment by peterwilsoncc** [comment]
I'm closing this PR as I don't think the file system classes need the new method.

As the non-direct classes already support moving directories in their `::move()` methods, I think the best approach is to make it consistent.

**Comment by azaozz** [comment]
Was just thinking about that too. Seems best to fix `::move()` where needed and make sure it's consistent. Then have a `move_dir()` wrapper similarly to `copy_dir()` (like in this PR).

**Comment by azaozz** [comment]
Related https://github.com/WordPress/wordpress-develop/pull/3909.

**Pull request closed without merging**
