### PR TITLE
Fix localization on install screen

### PR DESCRIPTION
**Pull request by swissspidy**
Works around issues with script localization happening too early because of blocks being registered.

Trac ticket: https://core.trac.wordpress.org/ticket/58696

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by costdev** [comment]
@swissspidy Thanks for working on this! This appears to work for the password strength indicator but not for the Show/Hide button on interaction.

https://github.com/WordPress/wordpress-develop/assets/79332690/64373f93-a136-4d36-8280-f65d024ba985

**Comment by swissspidy** [comment]
@costdev Weird, I cannot reproduce this. Did you perhaps navigate forward/backward in the browser or reload the install page when you recorded this, instead of starting install from scratch? The `$_REQUEST` could have been emptied.

Works fine for me:

https://github.com/WordPress/wordpress-develop/assets/841956/be78233f-a666-4aff-969b-a84b7481c1be

**Comment by costdev** [comment]
@swissspidy Hmm, I'm not sure now. Might be worth getting another tester to check it in case it's maybe something going on locally for me.

**Comment by swissspidy** [comment]
@SergeyBiryukov @ocean90 Would appreciate your review on this one so we can fix it in 6.5 🙏

**Review by jornp — APPROVED** [review]
This is testing well for me:

https://github.com/WordPress/wordpress-develop/assets/75777864/2ca2c73f-57e5-4dca-8383-3cbed7be1723

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/57286

**Pull request closed without merging**
