### PR TITLE
PHP 8.1: various files / fix handling of null (Trac 53635)

### PR DESCRIPTION
**Pull request by jrfnl**
More fixes for `null` after `parse_url()`, but in files for which unit tests can't easily be added.

Note: trac ticket link below not added yet on purpose while this ticket is still WIP.

###  PHP 8.1: plugin/theme editor pages: prevent "passing null to non-nullable" notice

While it is probably unlikely that someone would have a direct link to the plugin/theme editor on their home page or even on someone else's homepage, it is entirely possible for the referrer URL to not have a "path" component.

In PHP 8.1, this would lead to a `basename(): Passing null to parameter #1 ($string) of type string is deprecated` deprecation notice.

Changing the logic around and adding validation for the return type value of `parse_url()` prevents that.

### PHP 8.1: ms_cookie_constants(): prevent "passing null to non-nullable" notice

It is entirely possible for the `siteurl` option to not have a "path" component.

In PHP 8.1, this would lead to a `trim(): Passing null to parameter #1 ($string) of type string is deprecated` deprecation notice.

Changing the logic around and adding validation for the return type value of `parse_url()` prevents that.

Unfortunately, as this function is declaring global constants, adding tests for this change is not really an option without potentially affecting other tests.

Also note, that it is possible, though unlikely, for the option to not be available.
In that case though, the `get_option()` method returns `false` and while passing that to `parse_url()` does not deserve any prices for clean code, it also is not problematic (at this point in time).

Trac ticket: https://core.trac.wordpress.org/ticket/53635

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by hellofromtonya — APPROVED** [review]
@SergeyBiryukov @jrfnl and I discussed and thoroughly reviewed during today's live stream. Though this can benefit from manual testing, stepping up the manual test is difficult. We agree this PR can be committed without first doing the manual testing.

**Review by hellofromtonya — APPROVED** [review]
New commits since approval are part of what was discussed and agreed to. This PR is ready for commit!

**Comment by jrfnl** [comment]
Closing as committed via [51629](https://core.trac.wordpress.org/changeset/51629) and [51630](https://core.trac.wordpress.org/changeset/51630)

P.S.: @SergeyBiryukov Why did you removed the extra parentheses in the condition in `ms_cookie_constants()` ? They were there to prevent issues with operator precedence.

**Comment by SergeyBiryukov** [comment]
> Why did you removed the extra parentheses in the condition in `ms_cookie_constants()` ? They were there to prevent issues with operator precedence.

I think they are redundant here, as `&&` always [takes precedence](https://www.php.net/manual/en/language.operators.precedence.php) over `||`, unless I'm missing something.

In my understanding, they are necessary in cases like this:
`if ( a && ( b || c ) )`
but don't make a difference in cases like this:
`if ( a || ( b && c ) )`

If that is incorrect, happy to add them back :)

**Comment by jrfnl** [comment]
@SergeyBiryukov That is correct, but most people do not know the ins and outs of operator precedence in as much detail, so the parentheses clarify that for the next person reading the code. I'd say: leave it for now, but know that I did put them in for a reason.

**Comment by SergeyBiryukov** [comment]
Ah, that makes perfect sense. I appreciate the explanation and will keep it in mind from now on.

**Pull request closed without merging**
