### PR TITLE
Fix imageareaselect bug for non-integer image dimensions

### LINKED ISSUE #52182: Customizer: Can't crop header images.
### Steps to reproduce the behavior

1. Activate a theme that uses a custom header image: 
2. Go to My Site > Appearance > Customize > Header Image
3. Click on `Add new Image`
4. Select and image and then click on `Select and crop`

#### What I expected to happen

To be able to crop the image to the correct header size and then save it to the header

#### What actually happened

When you get to the next screen, there is no cropping selection. Dragging across the image to create a selected section results in `Drop image`. Clicking on `Crop` results in the error `{file name} There has been an error cropping your image`. if there is a `Skip Cropping` option and you select it, it does not update the header image

There is a video of my test site here: https://d.pr/v/0kpjbn

### Context

Customer reported this in #29153016-HC

#### Browser / OS version

Mac OS 10.15 / Chrome 89

Customer was using Windows 10 with Chrome 83

#### Is this specific to the applied theme? Which one?

First reported on Dynamic news, but I have also tested Dara and Intergalactic and had the same issues

#### Does this happen on simple or atomic sites or both?

Simple. The cropping function works as expected on AT sites

#### Is there any console output or error text?

No

#### Level of impact (Does it block purchases? Does it affect more than just one site?)

It affects more than one site, but doesn't seem to prevent other editing of the site

### PR DESCRIPTION
**Pull request by alshakero**
Trac ticket: https://core.trac.wordpress.org/ticket/54308#ticket

The ticket has all the information needed.

Fixes https://github.com/Automattic/wp-calypso/issues/52182

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by autumnfjeld** [comment]
@arthur791004 @alshakero 
Just confirming that _both_ this PR #1774 and https://github.com/WordPress/wordpress-develop/pull/2302 should be merged to fix https://core.trac.wordpress.org/ticket/54308#ticket.

**Comment by alshakero** [comment]
@autumnfjeld AFAICT, my PR is sufficient to resolve the issue because it circumvents the issue solved in #2302. I [explored both approaches](https://core.trac.wordpress.org/ticket/54308#:~:text=Another%20solution%20might%20be%20to%20check%20if%20any%20of%20the%20coordinates%20are) in my trac ticket.

**Comment by arthur791004** [comment]
@alshakero Thanks for adding my approach to your trac ticket! I think your PR is good and it can fix the case you mentioned. But I'm not sure there is any other case or not. For example, it seems that the developer can set the initial selection via options [here](https://github.com/WordPress/wordpress-develop/blob/429b90a517d897a09e12dd3a6d4141e5fe53e021/src/js/_enqueues/vendor/imgareaselect/jquery.imgareaselect.js#L979). If the value is greater than image width/height, it might resolve `NaN` again. So I still think initializing those variables is perhaps safer.

**Comment by alshakero** [comment]
@arthur791004 that's a great point!

**Comment by autumnfjeld** [comment]
@alshakero   Just curious if there are any blockers to finishing this work.   Did you need any further assistance?

cc: @arthur791004

**Comment by alshakero** [comment]
Hi @autumnfjeld! I'm just waiting for review in [Trac](https://core.trac.wordpress.org/ticket/54308#ticket). Is there anything I can do to accelerate getting this merged?

**Comment by costdev** [comment]
I think the PR needs to either rebase on trunk, or merge trunk to resolve the test failure on PHP 8.2 single site.

**Comment by alshakero** [comment]
Hi @costdev! Thanks. I rebased it 👍🏼

**Comment by ironprogrammer** [comment]
Merged/resolved in [changeset 54903](https://core.trac.wordpress.org/changeset/54903). This PR can be closed.

**Pull request closed without merging**
