### PR TITLE
Update the WP packages with fixes prior to WP 6.2 beta 3

### PR DESCRIPTION
**Pull request by ntsekouras**
Trac ticket: https://core.trac.wordpress.org/ticket/57471

This updated the packages to the latest versions with the latest fixes.

https://github.com/WordPress/gutenberg/commit/1e2b2f680c6378f789d6660bc04b30e35e3a33a3

Includes the following changes:

- Upgrade Playwright to 1.30.0
- [Block Editor - Inserter]: preload media categories empty check - client side
- Navigation: Fixes undo and redo for nesting operations in the navigation block's inspector
- Fix: OffCanvasEditor does not inserts submenu on collapsed items.
- OffCanvasEditor: Only allow some blocks to be converted to submenus
- Navigation: Updates "Add Submenu item" text to "Add Submenu link"
- Update: Make OffCanvasEditor use LeafMoreMenu by default.
- Template Part: Performance: Replace usage of wp_get_theme()->get_stylesheet() with get_stylesheet()
- Widget Editor: Fix a problem with 'Move to Widget Area' button not working
- Reusable Blocks: Use React 18 rendering for import dropdown
- useAsyncList: flush state updates when processing queue
- Refactor the site editor URLs for better backward compatibility
- Template editor: only disable the save button if no changes rather than hiding it
- [Quote]: Fix deprectated large style specificity rule
- Style Book: Allow button text labels for style book icon
- List View: Scroll selected block into view when single block selection changes
- Post editor: revert iframed editor for WP core only
- Fix the Publish region position and focus style.
- Remove "& Shadow" from the Border ScreenHeader title
- Site editor: specify focus state color for template navigation button

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by gziolo** [comment]
Do e2e tests require some changes after including "Post editor: revert iframed editor for WP core only"?

**Comment by ellatrix** [comment]
What e2e tests are run here?

**Comment by ntsekouras** [comment]
>Do e2e tests require some changes after including "Post editor: revert iframed editor for WP core only"?

Probably yes. I'm looking at it right now.

**Comment by ellatrix** [comment]
This bit needs to be reverted:

https://github.com/WordPress/wordpress-develop/commit/07fc9b2d7449314ee658d764ce162e99cef6783b#diff-54454877010d42c1ee0c0c0126c2cb81fc5b7c723197ab2888feea8fd3a49bac

**Comment by gziolo** [comment]
Committed with https://core.trac.wordpress.org/changeset/55392.

**Pull request closed without merging**
