### PR TITLE
Rename `prime_options` `prime_options_by_group`

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/58962

### CODE REVIEW

**Comment by felixarntz** [comment]
@peterwilsoncc I think this is a duplicate of #5554, which I just committed?

**Comment by peterwilsoncc** [comment]
Updated per [WP#58962 (comment)](https://core.trac.wordpress.org/ticket/58962#comment:49)

**Review by felixarntz — COMMENTED** [review]
Per my reply in https://core.trac.wordpress.org/ticket/58962#comment:51, this looks good to me, except that "options cache" should be "option caches" in accordance with the existing priming functions.

**Comment by peterwilsoncc** [comment]
@felixarntz Yep, you're right: singular thing, plural caches it is. Pushed in a04715a21b3e3eeb544d327f76206e6378735dc7

I've made sure the terminology is consistent elsewhere in 7c036e98e4ddbd1f4cda121a6844fe209375e5b6.

**Review by felixarntz — APPROVED** [review]
Thanks @peterwilsoncc, LGTM!

**Review by joemcgill — APPROVED** [review]
I'm happy with this renaming scheme. Thanks all.

**Comment by peterwilsoncc** [comment]
Committed in [r57013](https://core.trac.wordpress.org/changeset/57013) / https://github.com/WordPress/wordpress-develop/commit/fc3aae3a0816f20182204449a2c61127b12c7a70

**Pull request closed without merging**
