### PR TITLE
54760 automatic update, domain if empty site title

### PR DESCRIPTION
**Pull request by kebbet**
https://core.trac.wordpress.org/ticket/54760

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mauriac** [comment]
Hi @kebbet  good work, i have a suggestion, can we wrap the new block in new function, that will be nice as the block is repetitive now. what do you think about?

**Comment by kebbet** [comment]
Thanks @mauriac, I was thinking the same, but was unsure about where to place that functions. Any suggestions?

**Comment by mauriac** [comment]
I'll suggest src/wp-admin/includes/functions.php.

But let's ask committers if they're ok with that, and may be they have any suggestion.

@SergeyBiryukov @audrasjb

**Comment by audrasjb** [comment]
`wp-admin/includes/functions.php` would work, but I'm not sure a specific function is really needed for this… any thought @SergeyBiryukov ?

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/53063

**Pull request closed without merging**
