### PR TITLE
Update to the latest package versions for 5.8 beta1

### PR DESCRIPTION
**Pull request by youknowriad**
This updates WP to the latest WP packages. It includes the backports from https://github.com/WordPress/gutenberg/pull/32484

Trac ticket: https://core.trac.wordpress.org/ticket/52991

Todo: 

 - [x] Changes related to theme.json and block supports
 - [x] Changes related to widgets editor

See the diff in https://github.com/WordPress/gutenberg/pull/32484/files

### CODE REVIEW

**Comment by nosolosw** [comment]
Prepared https://github.com/youknowriad/wordpress-develop/pull/2 for the changes related to `theme.json` and block supports.

**Comment by noisysocks** [comment]
> Changes related to widgets editor

I only see changes to `packages/block-library/src/legacy-widget/index.php` which should be copied over when `grunt build --dev` is ran.

**Comment by youknowriad** [comment]
Thanks @noisysocks @nosolosw

**Comment by youknowriad** [comment]
Committed.

**Pull request closed without merging**
