### PR TITLE
Add an editor settings flag to enable the new gallery for mobile apps for 5.9

### PR DESCRIPTION
**Pull request by glendaviesnz**
Trac ticket: https://core.trac.wordpress.org/ticket/54583

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ocean90 — COMMENTED** [review]
```
1) Tests_Blocks_Editor::test_get_default_block_editor_settings
Failed asserting that actual size 18 matches expected size 17.

/var/www/tests/phpunit/tests/blocks/editor.php:173
```

The test needs an update for the new size.

**Comment by glendaviesnz** [comment]
> The test needs an update for the new size.

Done.

**Review by hellofromtonya — APPROVED** [review]
Testing validates it works on mobile app as intended. Ready for commit.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in https://core.trac.wordpress.org/changeset/52349.

**Pull request closed without merging**
