### PR TITLE
Block Editor: Revert anchor support for dynamic blocks

### PR DESCRIPTION
**Pull request by Mamaduka**
Trac ticket: https://core.trac.wordpress.org/ticket/57830

### CODE REVIEW

**Comment by hellofromtonya** [comment]
>Note: We're not reverting changes made to the `$attributes_to_merge` list. It is necessary to continue work on the feature in the Gutenberg plugin.

So this is a partial revert of https://core.trac.wordpress.org/changeset/55230.

**Comment by Mamaduka** [comment]
@hellofromtonya, correct. Only removing `ABSPATH . WPINC . '/block-supports/anchor.php'` file, but keeping the `$attributes_to_merge` change, so we can continue work in the plugin.

**Review by hellofromtonya — APPROVED** [review]
This is a partial revert of https://core.trac.wordpress.org/changeset/55230.
* The adding `'id'` to `$attributes_to_merge` is not included on purpose ✅ 
* All of other changes are reverted ✅ 
* Test Report: Confirms this PR resolves the issue ✅ 

Ready for commit 👍

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/55443.

**Pull request closed without merging**
