### PR TITLE
Build/Test Tools: Enable running the tests on PHP 8.4 (Trac: 62061)

### PR DESCRIPTION
**Pull request by jrfnl**
PHP 8.4 is expected to be released at the end of November 2024.

Trac ticket 62061 contains a full analysis of the changes needed for WP to be ready for PHP 8.4 and all currently available patches for WP Core have been merged in the mean time.

Enabling the tests to run in CI on PHP 8.4 allows WordPress core to prevent new PHP 8.4 compatibility issues from being introduced.

Notes:
* While a [patch has been pulled](https://github.com/WordPress/wordpress-importer/pull/172) for the Importer plugin, this patch has not been merged yet.
    This means there are currently still five failing tests. These failure are directly related to the Importer plugin and will be fixed once the PR for the plugin has been merged.
    To still allow WP Core to start structurally testing against PHP 8.4, these five tests have been set up now to be skipped on PHP 8.4.
    These tests skips should be removed again once the PR to the plugin has been merged.
* Xdebug-related tests will not be run on PHP 8.4 at this time as the Docker image for PHP 8.4 does not contain Xdebug yet. Once a stable release of Xdebug 3.4.0 is available, it can be added to the Docker image and the test step can then be enabled for PHP 8.4.

Trac ticket: https://core.trac.wordpress.org/ticket/62061

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by jrfnl** [comment]
Rebased without changes on current `trunk` so the remaining test failures can be can be clearly seen. These should only be 7 - 2 related to SimplePie, 5 related to the Importer plugins, but we'll see if anyone introduced new issues in the mean time ;-)

Note: I propose to temporarily skip those 7 tests until SimplePie and the Importer plugin are fixed and the fixes released. Enabling the test runs against PHP 8.4 and not allowing them to fail should then prevent _new_ issues from being introduced.

**Comment by jrfnl** [comment]
Update:

I've updated the commit to:
1. Skip the failing Importer plugin tests for the time being.
2. Add PHP 8.4 to the `.version-support-php.json` file for WP 6.7.
3. Also enable test runs against PHP 8.4 for the `upgrade-testing.yml` workflow.

A build showing a "clean bill of health" for WP Core using the updated version of the workflow can be seen here: https://github.com/WordPress/wordpress-develop/actions/runs/11164654907

**Review by desrosj — APPROVED** [review]
Thanks @jrfnl! After chatting yesterday and reviewing today, I think this is ready to go.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/59168.

**Pull request closed without merging**
