### PR TITLE
HTML API: Report breadcrumbs properly when paused on virtual nodes.

### PR DESCRIPTION
**Pull request by dmsnell**
Follow-up to [[58304]](https://core.trac.wordpress.org/changeset/58304)
See Core-61348

## Status

 - [x] Needs merge to `trunk`
 - [x] Needs backport into 6.6 RC

## Summary

Previously the breadcrumbs were only generated for real nodes, and when visiting virtual nodes, the parser had already traversed past them to the next real node, advancing the breadcrumbs ahead of the matched token.

Test [in the Playground](https://playground.wordpress.net/?blueprint-url=https://gist.githubusercontent.com/dmsnell/c2d294096f3363f3da95dacc6ae4f634/raw/8eda32520c61a2e88da1681f52cfb234a4745672/blueprint-with-core-pr.json)

Screenshot 2024-06-26 at 5 17 25 PM

### CODE REVIEW

**Comment by sirreal** [comment]
This seems to fix breadcrumbs, but `get_current_depth` may report the wrong depth in some cases that are fixes for breadcrumbs with this change.

**Comment by dmsnell** [comment]
> get_current_depth may report the wrong depth in some cases that are fixes for breadcrumbs with this change.

good point. in my head it was using `breadcrumbs()` already, but now it actually is with 21bc01b

**Review by sirreal — APPROVED** [review]
This fixes some breadcrumbs and depth issues in my testing 👍

**Review by adamziel — APPROVED** [review]

**Comment by dmsnell** [comment]
Merged in [[58588]](https://core.trac.wordpress.org/changeset/58588)
https://github.com/wordpress/wordpress-develop/commit/9cbaee349c69baf48e303dfb4a8ad0b0f71ead53

**Comment by gziolo** [comment]
> > get_current_depth may report the wrong depth in some cases that are fixes for breadcrumbs with this change.
>
> good point. in my head it was using breadcrumbs() already, but now it actually is with https://github.com/WordPress/wordpress-develop/commit/21bc01b956ded3bef4ed0df0371ba376bc6c1a8f

What is the minimal test cases that would cover this issue? We are in the RC phase, so better to stay on the safe side. When testing with the Playground link provided everything works as expected.

**Comment by sirreal** [comment]
`</p>` is a good test case for this. I'll add some unit tests in another PR.

[You can see that the P tags are created at the wrong depth with the wrong breadcrumbs here (hover them for a tooltip and notice their nesting)](https://playground.wordpress.net/?plugin=html-api-debugger&url=%2Fwp-admin%2Fadmin.php%3Fpage%3Dhtml-api-debugger%26html%3D%253C%252Fp%253E&wp=beta)

In this PR that's been fixed.

**Comment by gziolo** [comment]
To close the loop here, I backported changes with https://core.trac.wordpress.org/changeset/58590 to the 6.6 release branch.

**Comment by sirreal** [comment]
It would be great to land https://github.com/WordPress/wordpress-develop/pull/6929 as a follow-up to this with unit tests.

**Pull request closed without merging**
