### PR TITLE
HTML API: Fix the position update after changing the modifiable text when length differs

### PR DESCRIPTION
**Pull request by gziolo**
Reported by @adamziel in https://github.com/WordPress/wordpress-develop/pull/7007#issuecomment-2412540433:

> I just isolated the problem:
> 
> ```php
> $p = new WP_HTML_Tag_Processor('Hello there');
> $p->next_token();
> $p->set_modifiable_text('Short');
> echo $p->get_updated_html();
> ```
> 
> It's not occurring with this patch:
> 
> ```diff
> -		$this->bytes_already_parsed = $before_current_tag;
> +		if ($this->get_token_type() === '#tag') {
> +			$this->bytes_already_parsed = $before_current_tag;
> +		}
> ```

Trac ticket: https://core.trac.wordpress.org/ticket/62241

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by sirreal** [comment]
@gziolo I've proposed a fix for this in https://github.com/gziolo/wordpress-develop/pull/2 that can be merged into this PR.

**Comment by gziolo** [comment]
@sirreal, I would appreciate another look after changes applied to unit tests.

**Review by sirreal — APPROVED** [review]
Excellent, I like the updated tests 👍

**Comment by gziolo** [comment]
Committed with https://core.trac.wordpress.org/changeset/59250.

**Comment by adamziel** [comment]
Thank you so much for a timely fix!

**Pull request closed without merging**
