### PR TITLE
Trac 58114: Dashboard: Updates activity widget layout.

### PR DESCRIPTION
**Pull request by kebbet**
https://core.trac.wordpress.org/ticket/58114

## LTR - before (below)
bild

## LTR - after (below)
bild

## RTL - before (below)
bild

## RTL - after (below)
bild

### CODE REVIEW

**Comment by audrasjb** [comment]
Hey @kebbet it looks like there is something wrong in your fourth PR: we seems to have even/odd background on filters, too… 🤔

**Comment by kebbet** [comment]
Thanks for the heads up @audrasjb Looking at the CSS, and spinning up the dev environment again, I can not recreate my screenshot of the filters. Strange indeed, but the code in this PR looks ok to me.

Screenshot of RTL-version, with current PR.
bild

**Comment by audrasjb** [comment]
Ok thanks for the confirmation! I'll have a look then :)

**Comment by audrasjb** [comment]
Before patch:


After patch:

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/55889

**Pull request closed without merging**
