### PR TITLE
Gracefully handle invalid text domains

### PR DESCRIPTION
**Pull request by swissspidy**
Trac ticket: https://core.trac.wordpress.org/ticket/60888

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by knutsp** [comment]
Why does WordPress need to handle this developer error gracefully? It seems the suggested patch just silently hides the error for invalid parameter by replacing it with a valid one before passing it on to the object, still letting `load_textdomain` accepting it in the first place.

IMHO: `load_textdomain` should immeditalely trigger the same error, or, if badly needed, transform it to a warning.

**Comment by swissspidy** [comment]
That's a legit question.

Up until now, WordPress has actually somehow gracefully handled this scenario. As per the bug report, plugins have been doing it wrong like this for years, even though the behavior was entirely undefined. No warning or error happened though. Now with the stricter type hint in the new L10N library in 6.5, there suddenly is a fatal error. That's an implicit backward compatibility break and a bad user experience.

At second glance, we should just bail early instead of defaulting to `default`, as that more closely resembles the previous behavior.

> IMHO: load_textdomain should immeditalely trigger the same error, or, if badly needed, transform it to a warning.

For 6.6 we can consider a `_doing_it_wrong` warning for sure. Similar to https://core.trac.wordpress.org/ticket/44937

For 6.5.1 however, we should just ensure there is no fatal error.

**Comment by lenaseo22** [comment]
It's great to hear that the issue has been fixed in Divi v4.24.3! Sometimes, changes happen quickly, and it's understandable that the change log entry for the fix might not make it into the official change log due to its last-minute nature.

If you'd like to reference the fix for your records or for others who might be interested, you can consider including the change log entry in your own documentation or communications about the update.

If you have any further questions or need assistance with anything else related to Divi or any other topic, feel free to ask!

{{{
#!html
<a href="https://bytevarsity.ca/"></a><a href="http://ukvibesonline.co.uk/"></a><a href="https://dcanews.ca/"></a><a href="https://canadahomesnews.ca/"></a><a href="https://blesa.ca/"></a><a href="https://vixrim.ca/"></a><a href="https://totimescanews.ca/"></a><a href="http://canadianews.ca/"></a><a href="http://newsag.ca/"></a><a href="http://ottawas.ca/"></a><a href="http://canadavista.ca/"></a><a href="https://cryptowavezen.com/"></a><a href="https://bitcryptomining.net/"></a><a href="https://cryptocoinsupdates.com/"></a><a href="https://forexcryptonews.net/"></a><a href="https://bitforexvista.com/"></a><a href="https://stocktradalert.com/"></a><a href="https://tradingsentiment.org/"></a><a href="https://forexinvester.com/"></a><a href="https://stocksnotify.com/"></a><a href="https://stocktrendsalert.com/"></a><a href="https://topforexebroker.com/"></a><a href="https://forexah.com/"></a><a href="https://forexinsides.com/"></a><a href="https://stocksrush.com/"></a>
}}}

**Comment by swissspidy** [comment]
https://core.trac.wordpress.org/changeset/57925

**Pull request closed without merging**
