### PR TITLE
Prevent PHP notice in Customizer when using block theme

### PR DESCRIPTION
**Pull request by westonruter**
The issue was introduced in https://github.com/WordPress/wordpress-develop/pull/2217 where a `WP_Customize_Nav_Menus_Panel::check_capabilities()` method override was introduced which caused the return to be `false` if the current theme doesn't support `menus` nor `widgets`.

The problem is that since `check_capabilities` returns false, when `WP_Customize_Manager::prepare_controls()` runs it will remove any registered panels that the user doesn't have the capability to manage.

Ironically, I actually reviewed that PR and I thought the approach would work, but clearly it doesn't. I did provide an alternative solution, however, which should actually fix the issue here: https://github.com/WordPress/wordpress-develop/pull/2217#discussion_r790977534

Trac ticket: https://core.trac.wordpress.org/ticket/54905

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by noisysocks** [comment]
Makes sense. Marking the panel as inactive instead of removing it would indeed make it so that calls to `get_panel( 'nav_menus' )` don't return an empty value.

What I'm wondering though is: why do we even run `WP_Customize_Nav_Menus::available_items_template`, `WP_Customize_Widgets::output_widget_control_templates`, and `WP_Customize_Nav_Menus::enqueue_scripts` when the theme doesn't support menus nor widgets? It doesn't seem to me that there should ever be a call to `get_panel( 'nav_menus' )` when we know that there won't be a panel with that ID.

**Comment by westonruter** [comment]
Yes. Really the Widgets and Nav Menus components should be disabled entirely. There is a filter for that: [`customize_loaded_components`](https://developer.wordpress.org/reference/hooks/customize_loaded_components/). However, I do not believe it will work here because it has to run when `WP_Customize_Manager` is constructed which happens at `plugins_loaded`, and thus before the theme is loaded. This means it would run too early to check if `wp_is_block_theme()`, right?

**Comment by noisysocks** [comment]
Yeah that's right. Bummer!

OK, marking as inactive seems reasonable all things considered 👍

**Comment by westonruter** [comment]
Committed to `trunk` in https://core.trac.wordpress.org/changeset/54419

**Pull request closed without merging**
