### PR TITLE
Register Comments Query Loop from metadata

### PR DESCRIPTION
**Pull request by cbravobernal**
Add registration from metadata to Comments Query Loop in order to enable translations for the title and description.

Trac ticket: https://core.trac.wordpress.org/ticket/56093

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ockham — APPROVED** [review]
LGTM! :shipit: 🎉 

image

**Comment by ockham** [comment]
@gziolo @adamziel Can we have this once included in WP 6.0.1? 🙌

**Comment by adamziel** [comment]
Sure! CC @SergeyBiryukov

**Comment by gziolo** [comment]
Excellent but simple fix ❤️

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r53631](https://core.trac.wordpress.org/changeset/53631), backported to the 6.0 branch in [r53632](https://core.trac.wordpress.org/changeset/53632).

**Pull request closed without merging**
