### PR TITLE
Update packages for featured image fix

### PR DESCRIPTION
**Pull request by Mamaduka**
Updates include the Post Featured Image block fix required for #3560.

Updates packages:

```
 - @wordpress/block-directory@3.15.12
 - @wordpress/block-library@7.14.12
 - @wordpress/customize-widgets@3.14.12
 - @wordpress/edit-post@6.14.12
 - @wordpress/edit-site@4.14.14
 - @wordpress/edit-widgets@4.14.12
```

Trac ticket: https://core.trac.wordpress.org/ticket/56930

cc @felixarntz

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by felixarntz — APPROVED** [review]
Thanks @Mamaduka!

**Comment by Mamaduka** [comment]
@felixarntz, I don't have commit access, so somebody should merge this PR.

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @Mamaduka PR looks good to me. The new version of packages is available, so could you please update it?

**Comment by Mamaduka** [comment]
Thanks for testing, @mukeshpanchal27!

There have been no new package releases targeting WP, so there is no need for an update. You can find more details on a package's versions page. Example https://www.npmjs.com/package/@wordpress/block-library?activeTab=versions

**Comment by mukeshpanchal27** [comment]
@Mamaduka @wordpress/block-library current version is 8.0.0 isn't it?

**Comment by Mamaduka** [comment]
Correct, we do package releases every two weeks when the Gutenberg plugin is released. Those aren't intended for the core. See https://developer.wordpress.org/block-editor/contributors/code/release/#packages-releases-to-npm-and-wordpress-core-updates

The versions in this PR were cherry-picked for the core to help with #3560.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @Mamaduka for the answer. LGTM.

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/55079.

**Pull request closed without merging**
