### PR TITLE
changed single asterisks to double asterisks for ticket #60513

### PR DESCRIPTION
**Pull request by mahnewr**
I changed one of the /* to a /** to follow proper PHPDoc comments syntax

Trac ticket: https://core.trac.wordpress.org/ticket/60513
---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by kraftbj — APPROVED** [review]
Changes look good to me.

**Review by audrasjb — APPROVED** [review]

**Comment by rudlinkon** [comment]
@mahnewr thanks for the PR, I think we can do the same fix for some places also. I have given two more places where we can apply the same fix.

https://github.com/WordPress/wordpress-develop/blob/4fe09a2df3a3cd8360228051955f66ebf1033374/tests/phpunit/includes/bootstrap.php#L59
https://github.com/WordPress/wordpress-develop/blob/4fe09a2df3a3cd8360228051955f66ebf1033374/tests/phpunit/includes/wp-profiler.php#L3

**Comment by kraftbj** [comment]
I would not change the bootstrap.php since that appears to be a simple multi line comment (see 5.2 of https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/ )

The WP Profiler looks like it could function as the docblock for the class, so it should and have the additional check for completeness, like @ since, etc.

**Review by mukeshpanchal27 — APPROVED** [review]
Nice catch

**Comment by mukeshpanchal27** [comment]
Ready for commit 🎉

**Comment by rudlinkon** [comment]
> I would not change the bootstrap.php since that appears to be a simple multi line comment (see 5.2 of https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/ )
> 
> The WP Profiler looks like it could function as the docblock for the class, so it should and have the additional check for completeness, like @ since, etc.

Thank you @kraftbj so we can add double asterisks on the `wp-profiler.php` file.

**Comment by swissspidy** [comment]
Fixed in https://core.trac.wordpress.org/changeset/57665

**Pull request closed without merging**
