### PR TITLE
Disambiguate translator comments context

### PR DESCRIPTION
**Pull request by swissspidy**
Disambiguate usage of translator comments for `sprintf()` calls with multiple translated strings.
Writing the code on multiple lines makes it clearer which string the comment is intended for.

Trac ticket: https://core.trac.wordpress.org/ticket/59947

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by NekoJonez** [comment]
Will this PR fix the fact that not in all datetime strings... we get a comment to the PHP manual?

**Comment by swissspidy** [comment]
@NekoJonez Yes. Just this one needs to be added in Gutenberg: https://translate.wordpress.org/projects/wp/dev/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=13716800&filters%5Btranslation_id%5D=94748493

**Comment by NekoJonez** [comment]
> @NekoJonez Yes. Just this one needs to be added in Gutenberg: https://translate.wordpress.org/projects/wp/dev/nl-be/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=13716800&filters%5Btranslation_id%5D=94748493

Do I need to open a Gutenberg issue in their GitHub or ...?

**Comment by swissspidy** [comment]
If you'd like to open a PR there, feel free!

It basically needs a separate comment between each of those lines:

https://github.com/WordPress/gutenberg/blob/a7911582cda6f11d1ebddcd27ccbb82fb86022c5/packages/block-editor/src/components/date-format-picker/index.js#L82-L87

**Comment by NekoJonez** [comment]
Will do that in the near future.

**Comment by NekoJonez** [comment]
I tried to make the Gutenberg PR. Curious if I did it right. 
After that, it might be ready for commit no?

**Comment by swissspidy** [comment]
Awesome, thanks!

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/57136

**Pull request closed without merging**
