### PR TITLE
Fix: updates function parameter

### PR DESCRIPTION
**Pull request by kebbet**
Follow up to [[56570](https://core.trac.wordpress.org/changeset/56570)].

https://core.trac.wordpress.org/ticket/57791

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@kebbet, do we have any documentation regarding or any guidelines for this?

**Comment by kebbet** [comment]
> @kebbet, do we have any documentation regarding or any guidelines for this?

Not really atm, just looking at previous efforts, like https://core.trac.wordpress.org/changeset/54956 which was commited to his ticket https://core.trac.wordpress.org/ticket/56788

**Comment by mukeshpanchal27** [comment]
Thanks That changes was committed by @SergeyBiryukov so let's ping him for the clarification. Also i ping @costdev if hi knows anything about for it.

**Review by mukeshpanchal27 — APPROVED** [review]
The changes look fine to me.

**Comment by kebbet** [comment]
This is the ticket för 6.4 -> https://core.trac.wordpress.org/ticket/58976

**Comment by joedolson** [comment]
I think that @SergeyBiryukov's commit message is pretty clear here; we're avoiding using PHP keywords in variable names. So I don't think we need any additional confirmation; this is good to go.

**Comment by joedolson** [comment]
In r56662

**Pull request closed without merging**
