### PR TITLE
Layout: Skip outputting base layout rules that reference content or wide sizes if no layout sizes exist

### PR DESCRIPTION
**Pull request by andrewserong**
This is a backport of https://github.com/WordPress/gutenberg/pull/60489 from the Gutenberg repo.

Skip outputting base layout rules that reference content of wide sizes CSS variables, if no layout sizes exist in the current `theme.json`.

### Testing instructions

Activate Twenty Twenty theme and add the following test markup from https://github.com/WordPress/gutenberg/issues/60413 to a post:

```html
<!-- wp:group {"align":"full","backgroundColor":"primary","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignfull has-primary-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Full group.</p>
<!-- /wp:paragraph -->

<!-- wp:group {"align":"wide","backgroundColor":"accent","layout":{"type":"constrained"}} -->
<div class="wp-block-group alignwide has-accent-background-color has-background"><!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">Wide group.</p>
<!-- /wp:paragraph --></div>
<!-- /wp:group --></div>
<!-- /wp:group -->
```

Save and publish the post. On the site front end, prior to this PR, the wide group block will extend to the full width of its container. With this PR applied, its `max-width` should be that provided by the theme (in the case of Twenty Twenty, it's 120rem).

To test against regressions, switch to a block theme and make sure that constrained layout works as expected in the post and site editors and on the site front end.

Trac ticket: https://core.trac.wordpress.org/ticket/60936

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by andrewserong** [comment]
I've just added a draft for this PR — I haven't quite finished this yet (still need to update tests), but thought I'd at least push the PR to save my progress, as I've finished up for the week. I'll return to this on Monday.

**Comment by andrewserong** [comment]
I've switched the PR over to "ready for review" now that the tests have been updated. A note on the tests as the readability of the changes is not great:

* Tests that are to do with layout now have `contentSize` and `wideSize` and the output strings reflects the CSS variables being output, and the rules that use those CSS variables are present.
* For tests that have nothing to do with layout, the `contentSize` and `wideSize` settings have not been added, and the test strings have been updated to reflect that if those sizes are not present, the rules that reference them are absent in the output.

Between the above two changes to existing tests, there should be good coverage for the two states (outputting rules that reference content/wideSize and skipping the output).

**Review by tellthemachines — APPROVED** [review]
Thanks for the PR! Changes LGTM and work as expected.

**Comment by tellthemachines** [comment]
Committed in [r57948](https://core.trac.wordpress.org/changeset/57948).

**Pull request closed without merging**
