### PR TITLE
Sync packages for WordPress 6.7.1 RC1

### PR DESCRIPTION
**Pull request by cbravobernal**
Syncs Editor packages for WordPress 6.7.1 RC1. Includes the following PRs:
- https://github.com/WordPress/gutenberg/pull/66945
- https://github.com/WordPress/gutenberg/pull/66889
- https://github.com/WordPress/gutenberg/pull/67139

Packages being updated:

```
 - @wordpress/block-directory@5.8.18
 - @wordpress/block-editor@14.3.15
 - @wordpress/block-library@9.8.16
 - @wordpress/commands@1.8.11
 - @wordpress/components@28.8.11
 - @wordpress/core-commands@1.8.15
 - @wordpress/core-data@7.8.15
 - @wordpress/customize-widgets@5.8.16
 - @wordpress/dataviews@4.4.11
 - @wordpress/edit-post@8.8.18
 - @wordpress/edit-site@6.8.18
 - @wordpress/edit-widgets@6.8.16
 - @wordpress/editor@14.8.18
 - @wordpress/fields@0.0.16
 - @wordpress/format-library@5.8.15
 - @wordpress/interface@6.8.11
 - @wordpress/list-reusable-blocks@5.8.11
 - @wordpress/nux@9.8.11
 - @wordpress/patterns@2.8.15
 - @wordpress/plugins@7.8.11
 - @wordpress/preferences@4.8.11
 - @wordpress/reusable-blocks@5.8.15
 - @wordpress/server-side-render@5.8.11
 - @wordpress/widgets@4.8.15
```

Trac ticket: https://core.trac.wordpress.org/ticket/62478

Props:
`matiasbenedetto, ramonjd, mamaduka, getdave, poena, ntsekouras, mcsf, 
jsnajdr, mirka, desrosj, joemcgill, cbravobernal, azaozz, room34, mayanktripathi32, im3dabasia1, jonsurrell`
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by sirreal** [comment]
It looks like this needs `src/wp-includes/assets/script-loader-packages.min.php` to be compiled and committed.

**Comment by cbravobernal** [comment]
> It looks like this needs `src/wp-includes/assets/script-loader-packages.min.php` to be compiled and committed.

Yep, just updated it.

**Review by sirreal — APPROVED** [review]
The diff looks reasonable. I did some light smoke testing in the editor and did not observe any issues.

**Review by desrosj — APPROVED** [review]

**Comment by cbravobernal** [comment]
Committed in https://core.trac.wordpress.org/changeset/59437

**Pull request closed without merging**
