### PR TITLE
Update class-wp-http.php for PHP warning

### PR DESCRIPTION
**Pull request by Rajinsharwar**
Update class-wp-http.php for PHP warning of the get_class() deprecation.

Trac ticket: https://core.trac.wordpress.org/ticket/58876

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
Is there any particular reason to use `static::class` here instead of `self::class` ?

**Comment by Rajinsharwar** [comment]
Hi @jrfnl, I did that cause I thought that might follow the late static binding concept the most.

**Comment by jrfnl** [comment]
> Hi @jrfnl, I did that cause I thought that might follow the late static binding concept the most.

That's fair, though I wonder if we should allow those methods to be overloaded as there could be potential security implications ?

Then again, strictly speaking `static::class` is correct to prevent a potential BC-break. If we don't want those methods to be overloaded, they should probably be made `final` (or the class made `final`).

**Review by jrfnl — APPROVED** [review]

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/56495

**Pull request closed without merging**
