### PR TITLE
Security: Update list of supported versions of WP.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/57217

### CODE REVIEW

**Review by audrasjb — APPROVED** [review]
We're good to go with this patch, thanks Peter.

However, I'm not 100% fine with the emoji characters used to indicate whether the version is supported or not, as it is not super accessible. But that's something for another ticket! 😄

**Comment by peterwilsoncc** [comment]
> However, I'm not 100% fine with the emoji characters used to indicate whether the version is supported or not, as it is not super accessible. But that's something for another ticket! 😄

Agreed. Are you able to create a ticket (if you haven't already) so you get props for the change? There's a test in `tests/phpunit/tests/basic.php` that makes sure the latest stable branch is included in the support list so that may need to change, depending on what it tests for.

**Comment by audrasjb** [comment]
Yes, I'm opening a ticket for this right now :)

**Comment by peterwilsoncc** [comment]
Merged https://core.trac.wordpress.org/changeset/54918

**Pull request closed without merging**
