### PR TITLE
Editor: Update packages for 6.7 RC 3

### PR DESCRIPTION
**Pull request by kevin940726**
Syncs packages from Gutenberg ahead of RC 3. Contains the following PRs:

- https://github.com/WordPress/gutenberg/pull/66625
- https://github.com/WordPress/gutenberg/pull/66621
- https://github.com/WordPress/gutenberg/pull/66516
- https://github.com/WordPress/gutenberg/pull/66566

Trac ticket: https://core.trac.wordpress.org/ticket/62321

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ramonjd** [comment]
Fix for post taxonomy field bug here: https://github.com/WordPress/gutenberg/pull/66625

**Review by ramonjd — APPROVED** [review]
I tested using the test instructions in each Gutenberg PR.

The main ones:

✅  Space restored in tag selector from https://github.com/WordPress/gutenberg/pull/66566

Screenshot 2024-10-31 at 2 58 51 pm

✅  Tag selector focus works from https://github.com/WordPress/gutenberg/pull/66625

✅  Patterns request is avoided when loading site editor from https://github.com/WordPress/gutenberg/pull/66621

**Review by andrewserong — APPROVED** [review]
The included PRs appear to be testing well for me. And a quick smoke test of the post and site editors and the site frontend isn't resulting in any issues as far as I can tell.

LGTM!

**Comment by kevin940726** [comment]
Committed in r59330.

**Pull request closed without merging**
