### PR TITLE
Revert opt-in Appearance Tools support for Classic Themes

### PR DESCRIPTION
**Pull request by Mamaduka**
Reverts changes from https://github.com/WordPress/wordpress-develop/pull/3846. See the core ticket for more details.

Trac ticket: https://core.trac.wordpress.org/ticket/57649

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by audrasjb — APPROVED** [review]
This looks good to me @Mamaduka :)

**Comment by Mamaduka** [comment]
Thanks for the super-fast response, @audrasjb ⚡

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @Mamaduka, LGTM!

**Comment by dream-encode** [comment]
This PR is an exact copy of reverting https://core.trac.wordpress.org/changeset/55076, and that was done on trunk in https://core.trac.wordpress.org/changeset/55273.  Closing this PR as "merged".

**Comment by Mamaduka** [comment]
Thank you, @dream-encode!

**Pull request closed without merging**
