### PR TITLE
Update the WordPress packages with the first batch of fixes for 5.8 beta 2

### PR DESCRIPTION
**Pull request by youknowriad**
Trac ticket https://core.trac.wordpress.org/ticket/53397

## PHP Backports

 - [x] Theme.json infrastructure related changes cc @nosolosw @jorgefilipecosta 
 - [x] Widget editor related changes cc @noisysocks 
 - [x] Skip link fix cc @aristath

The diff is here https://github.com/WordPress/gutenberg/compare/5c890c0ca36bfd21a1ad945d9c0813c0686fec4a...6171e1b04e6d77fe08c64335ffc2419a96af8a36

### CODE REVIEW

**Comment by jorgefilipecosta** [comment]
The theme.json backport is available at https://github.com/WordPress/wordpress-develop/pull/1368. (I was not able to write to this branch)

**Comment by noisysocks** [comment]
Pushed the widgets stuff!

**Comment by aristath** [comment]
skip-link fix is on https://github.com/WordPress/wordpress-develop/pull/1357

**Comment by youknowriad** [comment]
Thanks folks, I'm going to include everything on this PR to do a single commit.

**Comment by youknowriad** [comment]
committed in https://core.trac.wordpress.org/changeset/51149

**Pull request closed without merging**
