### PR TITLE
Only fail importer tests if plugin is missing.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Follow up to r59085.

Instead of preventing the test suite from running, only fail the import related tests if the plugin is not available.

Note, this puts a call to `fail` in the `setIUp` of several tests. It may need to be moved to each individual test if there is a risk that PHP Unit will stop accepting fail calls during the set up.

A failing test run in which the importer is not installed can be seen in this [PHPUnit action run](https://github.com/WordPress/wordpress-develop/actions/runs/11545727401/?pr=7655) against 2084d485d62419025c0fd4c25a83ec2374e76534

The hack to failing the tests in the above commit has since been reverted.

Trac ticket: Core-61530

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by azaozz — APPROVED** [review]
Looks good!

Testing without the WP Importer plugin, there are 14 failed tests all with the new error message that is added here. With the plugin all tests pass.

**Comment by azaozz** [comment]
Thinking perhaps the same approach can be used in other cases. For example the PHP tests may run very slow, and some would fail if the internet connection is slow or flaky. Currently there are nearly 25,000 tests. With a slow/flaky connection they may take 15-20 minutes per run (using Docker/wp-env). Seems that can be improved by skipping tests that require internet to run when they are not essential?

**Comment by peterwilsoncc** [comment]
> Seems that can be improved by skipping tests that require internet to run when they are not essential?

There must be some tests missing the `http` group that ought to have it as network tests ought to run only when the group is specified. I'll open a ticket.

**Comment by peterwilsoncc** [comment]
Sorry, the group name is `external-http`, as noted on the ticket I've created.

**Comment by peterwilsoncc** [comment]
Merged [r59326](https://core.trac.wordpress.org/changeset/59326) / https://github.com/WordPress/wordpress-develop/commit/023af2111b9bbf2fa00705227b9f90ea537cc889

**Pull request closed without merging**
