### PR TITLE
Update SimplePie to version `1.8.0`

### PR DESCRIPTION
**Pull request by faisal-alvi**
Trac ticket: https://core.trac.wordpress.org/ticket/55604

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
The PR only have one file change, There should be more per https://github.com/simplepie/simplepie/compare/1.5.8...1.8.0

**Comment by faisal-alvi** [comment]
@mukeshpanchal27 I've added more files, but since the new version uses `PSR-4`, @peterwilsoncc suggested including the `src` folder as well. I'm still figuring out how to do that.

**Comment by faisal-alvi** [comment]
@mukeshpanchal27 just following up on the blocker here. Can you please ping someone who can review or help with this PR?

**Comment by peterwilsoncc** [comment]
@faisal-alvi I did some very rough experimenting with dropping the simple pie zip in to the existing folder (ie, moving the library files in to the library directory) and replacing inclusion of files with their new autoloader. 

It wasn't super successful as `WP_Feed_Cache_Transient` is now required to implement `SimplePie\Cache\Base` which is not the case.

IN short, it loosk like there will be quite a bit of messing around require to upgrade to 1.8.0.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! This is now resolved in [r59141](https://core.trac.wordpress.org/changeset/59141).

**Pull request closed without merging**
