### PR TITLE
Update NPM packages

### PR DESCRIPTION
**Pull request by desrosj**
Trac ticket: https://core.trac.wordpress.org/ticket/62220

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ockham** [comment]
👋 @desrosj Are you planning to land this in the near future (i.e. well before WP 6.8 Beta 1)?

(FWIW, I'd love that, as I have a [janitorial PR](https://github.com/WordPress/wordpress-develop/pull/7849) that requires a package update 😊)

**Comment by desrosj** [comment]
@ockham I plan to merge this sometime next week! But it's not a high priority.

Is the concern a merge conflict? Or something else? Don't feel blocked to commit your PR if it's ready and I'll adjust. 😄

**Comment by ockham** [comment]
> @ockham I plan to merge this sometime next week! But it's not a high priority.
> 
> Is the concern a merge conflict? Or something else? Don't feel blocked to commit your PR if it's ready and I'll adjust. 😄

Thank you, but I really can't land mine before a package update 😅 A while ago, I removed some now-obsolete functions from the Navigation block's PHP in Gutenberg. My PR moves -- or rather copies -- them to `deprecated.php`. But that means that they're colliding with the function declarations that still exist in Core's `navigation.php` -- until that file is updated by a package sync.

I hope that made sense. But again, not urgent at all -- any time before Beta 1 is fine 😄

**Comment by desrosj** [comment]
@ockham Merged in https://core.trac.wordpress.org/changeset/59509!

There are a few other dependencies with updates that need more work in order to be usable (`sinon`'s update causes test failures, for example). But won't get to those for a bit.

**Comment by ockham** [comment]
Aaand this is where I realize that this PR was about updating 3rd party dependencies, rather than `@wordpress/` packages. In my head, I totally equated "Update NPM packages" with "Sync `@wordpress/` NPM packages".
Bonus points for me for never actually checking the diff 🤦‍♂️ 

Anyway. Sorry for the noise. Nothing to see here. Carry on.

Unprops @ockham.

**Comment by desrosj** [comment]
Sorry! I should have been more specific that it was only `devDependencies`! No worries!

**Pull request closed without merging**
