### PR TITLE
Revert: Changes for #22192 and #59360 tickets

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
This PR revert the changes for [#22192](https://core.trac.wordpress.org/ticket/22192) and [#59360](https://core.trac.wordpress.org/ticket/59360) tickets.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by felixarntz** [comment]
@mukeshpanchal27 I'm not sure we would want to revert _all_ of these changes if we can't get to a solution for https://core.trac.wordpress.org/ticket/59360 in time. As far as I'm aware, the outstanding problem is only occurring on the network option ticket, so maybe we would only need to revert that?

**Comment by joemcgill** [comment]
> As far as I'm aware, the outstanding problem is only occurring on the network option ticket, so maybe we would only need to revert that?

@felixarntz are you sure that we could keep the `update_option()` changes? `update_network_option()` relies on `update_option()` if the function is called on a single site install. Does the bug only affect multisite?

**Comment by felixarntz** [comment]
@joemcgill I'm referring to https://core.trac.wordpress.org/ticket/59360#comment:20, which was only flagged on that ticket. So I'm not sure whether that would also be a problem on 22192.

**Comment by joemcgill** [comment]
I attempted to add the unit tests from https://github.com/WordPress/wordpress-develop/pull/5250, which verified the original behavior, but this is causing a strange error with the dataProvider, which I'm having trouble understanding. I've reverted those changes so this is just a straight revert—not a revert and add tests. I'm thinking I can commit the revert and we can adjust and add tests in a follow-up commit.

Preferably, the tests we add could more closely resemble the ones being removed in this revert, but will need to have the dataProviders updated.

**Comment by felixarntz** [comment]
@joemcgill Looking at https://github.com/WordPress/wordpress-develop/actions/runs/6538297235/job/17753926355, seems like a weird bug indeed. I can't see anywhere in `data_update_option_type_juggling()` that there would be only one value in the data array.

~~That said, rather than adding different tests (as in https://github.com/WordPress/wordpress-develop/pull/5497/commits/77ec8657e95736bcc966f3835c247c63ed7aad94), I think it would be great to maintain as much of the existing core tests as possible. We'll probably mostly have to update some data provider values to reflect the expected behavior _before_ our code changes, but the approach of those tests still looks good to me.~~

Nevermind, I now realize the tests you're adding are those from https://core.trac.wordpress.org/changeset/56648, correct?

**Comment by joemcgill** [comment]
@felixarntz 

> We'll probably mostly have to update some data provider values to reflect the expected behavior before our code changes, but the approach of those tests still looks good to me.

That's exactly what I was getting at with my comment:

> Preferably, the tests we add could more closely resemble the ones being removed in this revert, but will need to have the dataProviders updated.

I'd prefer to add back those unit tests as a separate task, in order to unblock this revert. Sound good?

**Comment by felixarntz** [comment]
@joemcgill SGTM! Also see my updated reply above.

**Comment by joemcgill** [comment]
Exactly. Rather than trying to rewrite all of the tests now, I was just trying to get us back to the state we were in before any code changes were made, since our original tests got refactored during the implementation. However, those odd test errors (which I can reproduce locally, but don't understand) made me rethink trying to do both the revert and test update in the same commit.

**Comment by joemcgill** [comment]
Committed in https://core.trac.wordpress.org/changeset/56946

**Pull request closed without merging**
