### PR TITLE
XML-RPC: blogger.getUsersBlogs: Don't use an additional HTTP request, makes it work with Multisite with forced SSL.

### PR DESCRIPTION
**Pull request by dd32**
Trac ticket: https://core.trac.wordpress.org/ticket/56492

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by desrosj** [comment]
Merged in wp_getUsersBlogs.

**Review by justid — COMMENTED** [review]
@desrosj 
This pr caused another bug.
According to _multisite_getUsersBlogs's comment

`@param array $args {
  Method arguments. Note: arguments must be ordered as documented.
  @type int    $0 Blog ID (unused).
  @type string $1 Username.
  @type string $2 Password.
}`

You can't just pass $args to wp_getUsersBlogs and wish it will work.
This broken change make blogger.getUsersBlogs full down because wp_getUsersBlogs  use $args[0] and $args[1] as username and password which is incorrect.

Better code is:
`$blogs = $this->wp_getUsersBlogs([$args[0], $args[1]);`

**Comment by desrosj** [comment]
This is a closed PR. Could you please open a ticket on Trac with more details?

**Comment by justid** [comment]
> This is a closed PR. Could you please open a ticket on Trac with more details?

I want to , but i cant open the wordpress trac website.(429 Too Many Requests)

This issue is simple:
File class-wp-xmlrpc-server.php, line 4881:
Just change
`$blogs = $this->wp_getUsersBlogs( $args );`
To
```
$blogs = $this->wp_getUsersBlogs( [$args[1], $args[2] );  
// my last comment is incorrect, it should be [$args[1], $args[2] , not [$args[0], $args[1] 
```

Then xml-rpc on multisite will work.
Here is the reason:
_multisite_getUsersBlogs's args are
```
@type int    $0 Blog ID (unused).
@type string $1 Username.
@type string $2 Password.
```

But wp_getUsersBlogs's args are 
```
@type string $0 Username.
@type string $1 Password.
```

**Pull request closed without merging**
