### PR TITLE
Fix docblock reference in _register_theme_block_patterns

### PR DESCRIPTION
**Pull request by joemcgill**
Trac ticket: https://core.trac.wordpress.org/ticket/59869

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by audrasjb — APPROVED** [review]
Thanks for spotting this.
For reference, here is the related section on HelpHub: https://developer.wordpress.org/reference/functions/_register_theme_block_patterns/#changelog

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @joemcgill for the PR. LGTM!

**Review by felixarntz — APPROVED** [review]
Good catch!

**Comment by QAQQL** [comment]
I can't open my blog after updating
图片


Fatal error: Uncaught Error: Call to undefined method WP_Theme::get_block_patterns() in D:\1\wp-includes\block-patterns.php:355 Stack trace: #0 D:\1\wp-includes\class-wp-hook.php(310): _register_theme_block_patterns() #1 D:\1\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters() #2 D:\1\wp-includes\plugin.php(517): WP_Hook->do_action() #3 D:\1\wp-settings.php(632): do_action() #4 D:\1\wp-config.php(92): require_once('D:\\1\\wp-sett...') #5 D:\1\wp-load.php(50): require_once('D:\\1\\wp-conf...') #6 D:\1\wp-blog-header.php(13): require_once('D:\\1\\wp-load...') #7 D:\1\index.php(17): require('D:\\1\\wp-blog...') #8 {main} thrown in D:\1\wp-includes\block-patterns.php on line 355

**Comment by joemcgill** [comment]
Merged in https://core.trac.wordpress.org/changeset/57102

**Comment by joemcgill** [comment]
@QAQQL, if you're still experiencing this issue, can you [open a new ticket here](https://core.trac.wordpress.org/newticket) or add additional details to [this related support forum topic](https://wordpress.org/support/topic/fatal-error-after-update-to-6-4/)?

**Pull request closed without merging**
