### PR TITLE
Sync packages for WP 6.1 RC 1

### PR DESCRIPTION
**Pull request by ockham**
Includes the latest round of Gutenberg bugfix PRs that were approved for inclusion during [yesterday’s triage session](https://wordpress.slack.com/archives/C02QB2JS7/p1665408036271379). The following Gutenberg PRs were cherry-picked:

- https://github.com/WordPress/gutenberg/pull/44640
- https://github.com/WordPress/gutenberg/pull/44652
- https://github.com/WordPress/gutenberg/pull/44584
- https://github.com/WordPress/gutenberg/pull/43181
- https://github.com/WordPress/gutenberg/pull/44650
- https://github.com/WordPress/gutenberg/pull/44731
- https://github.com/WordPress/gutenberg/pull/44660
- https://github.com/WordPress/gutenberg/pull/44718
- https://github.com/WordPress/gutenberg/pull/44721
- https://github.com/WordPress/gutenberg/pull/44463
- https://github.com/WordPress/gutenberg/pull/44415
- https://github.com/WordPress/gutenberg/pull/44676
- https://github.com/WordPress/gutenberg/pull/44150
- https://github.com/WordPress/gutenberg/pull/44098
- https://github.com/WordPress/gutenberg/pull/44637

Needed for today's WP 6.1 RC 1 release.

_Note that this does not include the Fluid Typography fixes (see https://github.com/WordPress/gutenberg/issues/44758 and https://github.com/WordPress/wordpress-develop/pull/3431). For those, I will file a separate PR, in order to de-risk things -- allowing us to merge this PR and consider those changes separately._

Trac ticket: https://core.trac.wordpress.org/ticket/56467

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ockham** [comment]
Merged into core by @davidb in https://core.trac.wordpress.org/changeset/54483.

**Comment by davidB** [comment]
@ockham ,I m not inconvénients into this project. Maybe wrong @ into your comment.

**Comment by ockham** [comment]
> @ockham ,I m not inconvénients into this project. Maybe wrong @ into your comment.

My bad! I meant @dream-encode. Sorry for the mixup!

**Comment by ockham** [comment]
(FWIW, looks like it was actually #3437 that was merged. Since that PR includes the changes made in this one, we can keep in closed.)

**Pull request closed without merging**
