### PR TITLE
Update template.php

### PR DESCRIPTION
**Pull request by mujuonly**
Yoda update

Trac ticket: https://core.trac.wordpress.org/ticket/58585

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by costdev — COMMENTED** [review]
Hi @mujuonly, this isn't actually a violation of Yoda conditions as `count( $post_types ) === 1` can't result in assignment. It also doesn't get flagged by WPCS, so I don't believe there's any change needed here.

**Comment by mujuonly** [comment]
@costdev PHP statement comparing the count of an array variable $post_types to the integer 1.  In Yoda the constant value 1 is placed on the left side of the comparison operator. I think it should align with all other files, in all other core files, the constant integer is in left and the count function is in the right. so I though that's the correct way.

**Comment by mujuonly** [comment]
Screenshot 2023-06-21 at 12 05 17 PM

**Comment by audrasjb** [comment]
There's a reason why Yoda condition are used: it's not for the aesthetical purpose but to avoid variable assignment.
Yoda conditions are useless when no variable assignment is possible (and unwanted on <, >, <=, >= comparisons).

**Comment by jrfnl** [comment]
Let me just quote the handbook:
> When doing logical comparisons involving variables, always put the variable on the right side and put constants, literals, or function calls on the left side. **If neither side is a variable, the order is not important.** 

Ref: https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#yoda-conditions

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Closing per the comments above.

**Pull request closed without merging**
