### PR TITLE
Site Health: fix endpoint names in permission checks

### PR DESCRIPTION
**Pull request by swissspidy**
Props @szepeviktor, see https://github.com/WordPress/wordpress-develop/commit/6ff5bf856a5012526d7fadbbee01ed4ba1ee93e2#commitcomment-125792863

Trac ticket: https://core.trac.wordpress.org/ticket/59236

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
cc @manuelrod @felixarntz

**Review by szepeviktor — APPROVED** [review]
Pascal ruleZ.

**Comment by mukeshpanchal27** [comment]
The `$this->validate_request_permission( 'debug_enabled' )` was introduce [changeset 49154](https://core.trac.wordpress.org/changeset/49154)

**Review by felixarntz — APPROVED** [review]
Great catch @szepeviktor, PR LGTM @swissspidy!

**Comment by swissspidy** [comment]
Merged in https://core.trac.wordpress.org/changeset/56489

**Comment by szepeviktor** [comment]
Thank you all the member of this flashmob! 🙃

**Pull request closed without merging**
