### PR TITLE
Adds "select all" shortcut for Mac on permalinks page when .htaccess is not writable

### PR DESCRIPTION
**Pull request by ajoah**
Patch to add Mac shortcut on permalinks page

Result  :
image

See : https://core.trac.wordpress.org/ticket/54633

### CODE REVIEW

**Review by audrasjb — APPROVED** [review]
Looks good to me.

**Review by SergeyBiryukov — CHANGES_REQUESTED** [review]
Thanks for the PR! I have a couple notes:
* We refer to this Mac key as "Cmd" in the [`wordpress` TinyMCE plugin](https://core.trac.wordpress.org/browser/tags/5.8.2/src/js/_enqueues/vendor/tinymce/plugins/wordpress/plugin.js#L254) bundled with core. Should we maybe do the same here, or is ⌘ a more common/recognizable name?
* The same key combination is mentioned in two more instances in the same file for `web.config` and should be updated there as well.

**Comment by ajoah** [comment]
Hi @SergeyBiryukov,

Well seen :)

Tinymce refers to cmd and ⌘ too : https://core.trac.wordpress.org/browser/tags/5.8.2/src/js/_enqueues/vendor/tinymce/plugins/wordpress/plugin.js#L712
So I replaced the cmd reference by ⌘.

I updated the two other mentions of the shortcut in permalinks file

**Comment by audrasjb** [comment]
Conflicts solved (merged trunk to the PR branch)

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/53047

**Pull request closed without merging**
