### PR TITLE
Upgrading WPCS

### PR DESCRIPTION
**Pull request by pento**
Running Travis tests.

### CODE REVIEW

**Comment by jrfnl** [comment]
@pento Is the exclude pattern the problem ? If so, what were you trying to exclude specifically there ? Is there a way to make the pattern more specific to get round the issue ? Exclude patterns are basically regular expressions, with just the one extra that `*` will be automatically converted to the regex `.*` pattern.

**Comment by pento** [comment]
Yeah, the problem is that our `phpcs.xml.dist` has the rule `<exclude-pattern>/build/*</exclude-pattern>`. Travis puts everything in the `/home/travis/build/WordPress/wordpress-develop` folder. Per squizlabs/PHP_CodeSniffer/#981, this behaviour is unlikely to change, so the workaround is to change the folder on Travis.

**Comment by pento** [comment]
It's to exclude the `build` directory that's created when you run `grunt build`: no point in checking code that's just copied from the `src` directory.

**Comment by jrfnl** [comment]
@pento In that case, the regex exclude pattern I posted above should do the trick.

**Comment by jrfnl** [comment]
@pento Cricky.. just thinking the `<` in the look behind might not be accepted in XML. You could try passing it as:
```xml
<exclude-pattern>(?&lt;!/travis)/build/*</exclude-pattern>
```
... and see if that works. If not, I'll come up with a different regex.

**Comment by pento** [comment]
Yup, [that worked](https://travis-ci.org/WordPress/wordpress-develop/jobs/416702492). 🙂

**Comment by pento** [comment]
Okay, I'm happy with the state of this. I'm going to merge it into Core later today, we can work on getting the custom bits into WPCS 1.1, and then we can easily upgrade Core again.

**Pull request closed without merging**
