### PR TITLE
Update the `array_is_list` compat function, add tests

### PR DESCRIPTION
**Pull request by swissspidy**
The function was polyfilled via another ticket.

This adds tests that were originally added and simplifies the polyfill (assuming the tests still pass)

Trac ticket: https://core.trac.wordpress.org/ticket/55105

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by costdev — APPROVED** [review]
Thanks for putting the PR together @swissspidy!

I'm happy to go with the shorter function contents, though I haven't had a chance to compare both approaches on large arrays. It would be good to get some benchmarks on that if possible, but not a blocker.

LGTM 👍

**Comment by swissspidy** [comment]
Okay so the shorter version fails for the `array(NAN)` case on PHP 7.0 and PHP 7.1

Benchmarking with a larger array now. Turns out the `array_values()` approach is faster for the happy path, see https://3v4l.org/EMpT0/perf (foreach) vs https://3v4l.org/1WsAV/perf (`array_values()`)

For the unhappy path the performance seems equal, see https://3v4l.org/5YMl2/perf (foreach), https://3v4l.org/o1SSY/perf (`array_values()`) and https://3v4l.org/H721m/perf (both).

So that appears to make a case for using both as Symfony does.

**Comment by costdev** [comment]
Not sure how both can ever be run though. If `array_values( $arr ) === $arr`, then when would the `foreach()` run?

**Comment by swissspidy** [comment]
@costdev It's specifically that the output for using `array( NAN )` as the input is different on PHP 7.0 and PHP 7.1. It doesn't really make sense to me.

See https://3v4l.org/nPN8l

**Comment by swissspidy** [comment]
Tests committed in https://core.trac.wordpress.org/changeset/57535

**Pull request closed without merging**
