### PR TITLE
PHP notice if optional argument isn't passed to map_meta_cap()

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/44591

### CODE REVIEW

**Comment by SergeyBiryukov** [comment]
Thanks for the refreshed PR!

Just noting that inserting a type of content, such as "post" or "comment", into a generic string like `...you must always check it against a specific %2$s` is not translatable.

A general best practice in WordPress is to avoid post type and taxonomy names in generic strings due to i18n concerns and structural differences in languages. See some previous discussions for reference:
 * https://core.trac.wordpress.org/ticket/17609#comment:3
 * https://core.trac.wordpress.org/ticket/19099#comment:1
 * https://core.trac.wordpress.org/ticket/37895

To clarify a bit more, while both `post` or `comment` and `...you must always check it against a specific %2$s` string itself are translatable, this or any other generic string like that is not _correctly_ translatable. It does not account for different word forms or declensions in other languages, so no matter how you translate it, the result is still incorrect.

To fix this, separate strings for each type of content should be used instead:
* `When checking for the "%s" capability, you must always check it against a specific post.`
* `When checking for the "%s" capability, you must always check it against a specific page.`
* `When checking for the "%s" capability, you must always check it against a specific comment.`
* `When checking for the "%s" capability, you must always check it against a specific term.`

I can work on this in a bit.

**Comment by peterwilsoncc** [comment]
> To clarify a bit more, while both `post` or `comment` and `...you must always check it against a specific %2$s` string itself are translatable, this or any other generic string like that is not _correctly_ translatable. It does not account for different word forms or declensions in other languages, so no matter how you translate it, the result is still incorrect.

Thanks for the help with i18n, I've pushed some changes in 67770b17c541bdc105cd9f7a3d4155da7819ce0e but please feel free to push to my repository if further work is needed. I'm also happy to make such changes if needs be, the more I know about this as a native English speaker, the better.

**Comment by SergeyBiryukov** [comment]
Thanks for the refresh! This looks good to me in terms of i18n now 👍 

I've pushed some minor formatting changes so that the structure of these blocks is consistent across the function, and is more in line with similar messages elsewhere in core. This includes:
* Only using numbered placeholders if there are multiple placeholders in a string.
* Using `<code>` tags instead of double quotes for code fragments like the post type name or capability name.
* Removing `esc_html()` from `$cap`, as it's not escaped in the existing messages, and neither is the post type or post status. Happy to add the escaping back if necessary, but I think it should be done consistently, whether escaped or not.

Sorry for being a bit late with this review. Since we're now in soft string freeze after Beta 3, I guess we should move this to 6.1.

**Comment by SergeyBiryukov** [comment]
Merged in https://core.trac.wordpress.org/changeset/53408.

**Pull request closed without merging**
