### PR TITLE
Update `build_comment_query_vars_from_block` to handle unapproved comments

### PR DESCRIPTION
**Pull request by DAreRodz**
Backports some changes in `build_comment_query_vars_from_block` to handle comment previews done in the Gutenberg repo. We need these changes in core before merging https://github.com/WordPress/gutenberg/pull/40612  as explained in https://github.com/WordPress/gutenberg/pull/40612#issuecomment-1110107499.

Trac ticket: https://core.trac.wordpress.org/ticket/55634

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ockham — APPROVED** [review]
LGTM!

**Comment by ockham** [comment]
@peterwilsoncc Would you mind committing this to Core? 🙏 

(It's a prerequisite for https://github.com/WordPress/gutenberg/pull/40612 and https://github.com/WordPress/gutenberg/pull/40659, which will fix https://github.com/WordPress/gutenberg/issues/40601.)

**Review by peterwilsoncc — APPROVED** [review]
LGTM, I've added the ticket reference and merged in trunk to ensure the tests are still passing. 

I'll commit it shortly.

**Comment by peterwilsoncc** [comment]
merged in https://core.trac.wordpress.org/changeset/53298

**Pull request closed without merging**
