### PR TITLE
Update option autoload function docs to only encourage boolean autoload values and soft-deprecate 'yes' and 'no'

### PR DESCRIPTION
**Pull request by felixarntz**
This PR only updates documentation.

Trac ticket: https://core.trac.wordpress.org/ticket/61929

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by joemcgill — APPROVED** [review]
These changes look correct. I'm approving pending answers to [my comment](https://core.trac.wordpress.org/ticket/61929#comment:3) on the ticket:

> I think this change makes sense, and aligns with the intent of [[57920]](https://core.trac.wordpress.org/changeset/57920) and what was communicated in the associated [Dev Note post](https://make.wordpress.org/core/2024/06/18/options-api-disabling-autoload-for-large-options/). The argument against is that the function technically does support string values for those parameters for backwards compatibility.
> 
> Do you know if there other places where we intentionally limit the param values in docs to exclude values that are only supported for backwards compatibility purposes?

**Review by mukeshpanchal27 — APPROVED** [review]

**Review by jrfnl — APPROVED** [review]
Thanks @felixarntz LGTM.

**Comment by jrfnl** [comment]
One question (though this doesn't change my approval): is the `@since 6.7.0` correct or should this be `@since 6.6.0` ?
After all, this is a documentation change and it could be argued that the changes in WP 6.6 implicitly deprecated the values, but that the documentation wasn't updated to match and that this PR corrects that oversight.

**Comment by felixarntz** [comment]
> One question (though this doesn't change my approval): is the `@since 6.7.0` correct or should this be `@since 6.6.0` ? After all, this is a documentation change and it could be argued that the changes in WP 6.6 implicitly deprecated the values, but that the documentation wasn't updated to match and that this PR corrects that oversight.

I thought about this too, but think it makes more sense to have this aligned to 6.7.0, as only now we're really thinking about this. There's no functional change in any of those places, but it still feels more appropriate to mark this only deprecated as of now, rather than retroactively. Also, core still uses `'yes'|'no'` in a few places as of 6.6, so that would not be a good state to be in if they had been deprecated already. :)

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/58949

**Comment by jrfnl** [comment]
> > One question (though this doesn't change my approval): is the `@since 6.7.0` correct or should this be `@since 6.6.0` ? After all, this is a documentation change and it could be argued that the changes in WP 6.6 implicitly deprecated the values, but that the documentation wasn't updated to match and that this PR corrects that oversight.
> 
> I thought about this too, but think it makes more sense to have this aligned to 6.7.0, as only now we're really thinking about this. There's no functional change in any of those places, but it still feels more appropriate to mark this only deprecated as of now, rather than retroactively.

I defer to you as the author of the underlying changes. Just wanted to make sure this had been considered.

> Also, core still uses `'yes'|'no'` in a few places as of 6.6, so that would not be a good state to be in if they had been deprecated already. :)

That's not actually an issue with a soft deprecation, though will need to be fixed before a hard deprecation happens (though I seem to remember seeing a commit fixing these already).

**Pull request closed without merging**
