### PR TITLE
Test `continue-on-error`

### PR DESCRIPTION
**Pull request by desrosj**
Trac ticket: https://core.trac.wordpress.org/ticket/53891

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by jrfnl — COMMENTED** [review]
@desrosj Nice one! I hadn't realized you could combine both `if` as well as `continue-on-error` on steps, but _duh_, of course you can 😂 , so 👍🏻 

Just one remark:
* Line 194/slow tests: the `matrix.php != '8.1' &&` part of the condition still needs to be removed + `continue-on-error` still needs to be added.

**Comment by desrosj** [comment]
Thanks @jrfnl! I removed the PHP 8.1 check, but I did not add the `continue-on-error` for that step.

Slow tests are currently only split out for PHP 5.6. If PHP 8.1 started running slow tests, that is something that should get flagged.

**Comment by jrfnl** [comment]
@desrosj Understood, though as `split_slow` is a matrix condition which _could_ be added anywhere, that means there's an undocumented assumption in the workflow that it will not be added for the PHP 8.1 workflows. So, in that sense, as that step does not have a PHP version based condition, it would still be _safer_ to add the `continue-on-error` to it, just in case.

Either way, with a bit of luck, these conditions will only be in the workflow for a month or two at the most, so no biggie.

**Comment by desrosj** [comment]
I don't have a strong preference. @SergeyBiryukov care to be the tie breaker on this if you're able to commit?

**Comment by SergeyBiryukov** [comment]
I don't have a strong preference either, but as the `split_slow` condition is specific to PHP 5.6 per [[50444]](https://core.trac.wordpress.org/changeset/50444), it seems like a safe assumption that it will not be added for the PHP 8.1 workflows. So the PR as is seems good to me :)

**Comment by SergeyBiryukov** [comment]
Merged in https://core.trac.wordpress.org/changeset/51604.

**Pull request closed without merging**
