### PR TITLE
Twenty Twenty-One: Query Loop: Add padding when a background color is set

### PR DESCRIPTION
**Pull request by ryelle**
Before:

| Editor | Frontend |
|--|--|
| Screen Shot 2021-06-21 at 12 38 49 PM | Screen Shot 2021-06-21 at 12 39 08 PM |

After

| Editor | Frontend |
|--|--|
| Screen Shot 2021-06-21 at 12 41 14 PM | Screen Shot 2021-06-21 at 12 40 46 PM |

Trac ticket: https://core.trac.wordpress.org/ticket/53398

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by scruffian** [comment]
This looks good. What do you think about also adding the padding when the block is alignfull?

**Comment by ryelle** [comment]
@scruffian It should, did it not work for you?

**Comment by scruffian** [comment]
It does when it has a background color, but I mean even if it doesn't:

Screenshot 2021-06-23 at 16 10 21

**Comment by ryelle** [comment]
No, to match the behavior of other blocks (and so people can use full-width images), I think it would be best to only add the padding when there's a background color. If someone wants to add space, they can make a group block and control the space themselves with the padding control.

**Comment by scruffian** [comment]
LGTM

**Pull request closed without merging**
