### PR TITLE
About page update 6.4.1 (four issues).

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/59852

### CODE REVIEW

**Review by aaronjorbin — APPROVED** [review]
Looks good to me!

**Comment by abhansnuk** [comment]
Looks good to me.

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/57095

**Comment by peterwilsoncc** [comment]
Merged [r57095](https://core.trac.wordpress.org/changeset/57095) / https://github.com/WordPress/wordpress-develop/commit/3d8bc3190de79f33c92c6a6d01377a28860778fc

**Pull request closed without merging**
