### PR TITLE
Update npm packages for 6.4.2

### PR DESCRIPTION
**Pull request by mikachan**
Trac ticket: https://core.trac.wordpress.org/ticket/59828

Included changes:

- https://github.com/WordPress/gutenberg/pull/55995
- https://github.com/WordPress/gutenberg/pull/55438
- https://github.com/WordPress/gutenberg/pull/55361
- https://github.com/WordPress/gutenberg/pull/55890
- https://github.com/WordPress/gutenberg/pull/55973
- https://github.com/WordPress/gutenberg/pull/55984
- https://github.com/WordPress/gutenberg/pull/54902
- https://github.com/WordPress/gutenberg/pull/55607

New published packages for this update: https://github.com/WordPress/gutenberg/commit/70b30e9461372ae518e3d0e50f7e5085eda8b46e

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by tellthemachines — APPROVED** [review]
Changes LGTM and everything works as expected in testing (I followed the testing steps for the included PRs).

One thing I'm slightly puzzled about is why all the packages are getting version bumps. Did anything change in the workflow from last release to this one? I notice this has been happening for all the updates this release, whereas e.g. for 6.3.2 [only the changed packages got bumped](https://github.com/WordPress/wordpress-develop/pull/5151/files). This is not blocking by any means 😅, just wondering about it.

**Comment by tellthemachines** [comment]
Noting that the following changes were also included in this PR:

[Add check for lightbox values during image block migration](https://github.com/WordPress/gutenberg/commit/370fd4f7a9867fa31ba91efbf9861161e1697d88)

[Add context for translators to any unclear usage of "synced"](https://github.com/WordPress/gutenberg/commit/4c1f4d49ee60b4b48c0da28eec199a800c733cb5) 

[Patterns: use existing download function for JSON downloads to fix no…](https://github.com/WordPress/gutenberg/commit/0b6e6e67369cc89440a3c7d5799e671bad1a4bef) 

This is as expected because they were all marked for inclusion in the next minor release.

**Comment by tellthemachines** [comment]
Committed in [r57109](https://core.trac.wordpress.org/changeset/57109). Leaving this open for commit to the release branch though not sure if it's best to point this PR at the release branch instead of trunk or just open a new one (we should in any case check CI passes with this diff against the release branch)

**Comment by mikachan** [comment]
Thanks so much for helping with this and testing!

> One thing I'm slightly puzzled about is why all the packages are getting version bumps. 

This has been mentioned before during the 6.4 cycle but I can't find where right now. I vaguely remember it being mentioned and it was fine for now, but going into 6.5 maybe we should look more closely at this. 😅

I don't know if there's been an update to the publishing actions or if Lerna has been updated, but it's almost as if Lerna has no context for the current changes, so it assumes everything needs a version bump. I'm not sure what's changed between 6.3 and 6.4 though - maybe @gziolo knows more?

**Comment by gziolo** [comment]
After checking the publishing job I can share that I identified the reason why we still see all packages published. I landed some time ago the fix in the Gutenberg repository that potentially addresses the issue encountered with https://github.com/WordPress/gutenberg/pull/55334 but it only impacts `trunk`. For not fully clear to me reasons, the publishing targeting the WP 6.4 release gets triggered from GitHub UI using the `wp/6.4` branch. In effect, the publishing workflow doesn't use the patched version. To address it we should do two things:
- Update the docs to make it clear that publishing workflow should get triggered using the latest code from `trunk`.
- Cherry-pick the linked PR to `wp/6.4` in case the workflow get still triggered from the branch.

It worked smoothly with WordPress 6.3 and lower. However, once Node.js and npm upgrades happened, we had to stop using the Node script and move all logic to the GitHub workflow to support all the different npm versions used with older wp branches. This is why workflow requires `trunk` to use the most recent version.

**Comment by mikachan** [comment]
Ah this makes sense, thanks @gziolo! I hadn't seen https://github.com/WordPress/gutenberg/pull/55334.

> For not fully clear to me reasons, the publishing targeting the WP 6.4 release gets triggered from GitHub UI using the wp/6.4 branch.

@SiobhyB and I discussed this early in the 6.4 cycle and we decided to go with publishing the packages targeting the `wp/6.4` branch as we thought this was safer and would limit any potential unexpected issues, and we'd also seen a mix of publishing both from `trunk` and from the `wp/X.Y` branch in past runs. I guess we technically limited any issues but also missed a fix 😅 

> Update the docs to make it clear that publishing workflow is triggered using the latest code from trunk.

The [docs](https://developer.wordpress.org/block-editor/contributors/code/release/#wordpress-releases) screenshot does show the target as `trunk`, but this isn't mentioned in the text description. This sentence also threw me off: `Now, the wp/X.Y branch is ready for publishing npm packages.`. I had assumed this also meant "run from the `wp/X.Y` branch", so perhaps we could update this wording. It also didn't feel right to run the package updates from `trunk`, especially as all the other related work is based on the `wp/X.Y` branch.

> Cherry-pick the linked PR to wp/6.4 in case the workflow get still triggered from the branch.

I'm happy to help handle this.

**Comment by tellthemachines** [comment]
Oh I see, thanks @gziolo !

> Update the docs to make it clear that publishing workflow should get triggered using the latest code from trunk.
> Cherry-pick the linked PR to wp/6.4 in case the workflow get still triggered from the branch.

I agree with @mikachan that the docs could be more explicit about which branch to trigger the workflow from, as I also found that super confusing in the past 😅 
Happy to go in and change that!

Cherry picking the fix to the release branch would also be good to avoid confusing anyone packaging a minor release from this branch in the future.

**Comment by gziolo** [comment]
I cherry-picked https://github.com/WordPress/gutenberg/commit/1dd31459ba0a45c62adbcc4ae2fbd15dbed681e4 in the `wp.6.4` branch in Gutenberg that should resolve the issue.

> I agree with @mikachan that the docs could be more explicit about which branch to trigger the workflow from, as I also found that super confusing in the past 😅
> Happy to go in and change that!

Let's do it as well, as it might prevent similar issues in the future. I understand how the combo box for selecting the branch might confuse people. The intention GitHub has with it is to allow the selection of the branch from which the GitHub workflow file is going to be read on CI. In effect, when selecting the `wp/6.4` this is the current workflow (with the patch applied) that is going to get triggered:

https://github.com/WordPress/gutenberg/blob/wp/6.4/.github/workflows/publish-npm-packages.yml

**Comment by mikachan** [comment]
> Committed in [r57109](https://core.trac.wordpress.org/changeset/57109). Leaving this open for commit to the release branch though not sure if it's best to point this PR at the release branch instead of trunk or just open a new one (we should in any case check CI passes with this diff against the release branch)

@tellthemachines, you mentioned above that we may either need to point this PR at the release branch (I guess this is `6.4`?) or open a new one. Which one would you recommend? 

Also, we have one more change that needs to be included in the package update. I'm in the process of updating the packages again [here](https://github.com/WordPress/gutenberg/pull/56372) - should I create a new PR for this, or include it in this PR? I know this PR has already been committed to trunk, so I'm guessing it's best to open a new PR.

**Comment by tellthemachines** [comment]
> Also, we have one more change that needs to be included in the package update.

@mikachan in that case it's probably easier to open a new PR for trunk with that extra change, and then assuming it's all good, open a third PR for the release branch including all the changes.

**Comment by mikachan** [comment]
> in that case it's probably easier to open a new PR for trunk with that extra change, and then assuming it's all good, open a third PR for the release branch including all the changes.

Will do, thank you!

**Comment by mikachan** [comment]
Here's the new PR for trunk with the single extra change: https://github.com/WordPress/wordpress-develop/pull/5696

The tests seem good, although it looks like there's an error with the Playground build process [here](https://github.com/WordPress/wordpress-develop/actions/runs/6956460425/job/18927863791?pr=5696). I'm not sure if that's a blocker or not.

I went ahead and created a PR against the release branch too with all the changes: https://github.com/WordPress/wordpress-develop/pull/5698. All the tests passed here.

Thanks so much for your help 🙇

**Comment by mikachan** [comment]
I'm going to close this PR as these changes have already been committed to trunk in [r57109](https://core.trac.wordpress.org/changeset/57109). We have multiple PRs open for the npm package update (including a separate PR for the [release branch](https://github.com/WordPress/wordpress-develop/pull/5698)), so trying to reduce any confusion!

**Pull request closed without merging**
