### PR TITLE
Update `send_auth_cookies` filter parameters order

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Trac ticket: https://core.trac.wordpress.org/ticket/56971

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by costdev — APPROVED** [review]
LGTM :+1: Thanks @mukeshpanchal27!

**Comment by audrasjb** [comment]
I added another commit to this PR to also change the order in the since mention.

**Comment by mukeshpanchal27** [comment]
Thanks @audrasjb for update.

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/55253

**Pull request closed without merging**
