### PR TITLE
HTML API: Apply linting changes.

### PR DESCRIPTION
**Pull request by dmsnell**
Trac ticket: Core-60060

cc: @tobiasbg

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
LGTM. Is there any sniff there that check this?

**Comment by mukeshpanchal27** [comment]
LGTM. Is there any sniff there that check this?

**Comment by TobiasBg** [comment]
Thanks for the PR. It's not just lowercasing though. The colons should be removed as well.

**Review by SergeyBiryukov — CHANGES_REQUESTED** [review]
Thanks for the PR!

These should be `@todo`, without the trailing colon.

There is also one more instance in `wp-includes/html-api/class-wp-html-active-formatting-elements.php`.

Reference: [PHP Documentation Standards: PHPDoc tags](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#phpdoc-tags).

Note: At this time, there are no automated CI checks for this, so it's just a manual fix to conform to the documentation standards.

**Review by sirreal — APPROVED** [review]
Looks good.

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by ockham** [comment]
Committed to Core in https://core.trac.wordpress.org/changeset/57209/.

**Pull request closed without merging**
