### PR TITLE
Remove orderby from comment counting queries.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Modifies all the WP_Comment_Query calls to remove the orderby if `count === true`.

I can never remember what comes from the GB repo, so it is possible `src/wp-includes/blocks/comments.php` should be changed upstream.

Trac ticket: https://core.trac.wordpress.org/ticket/58368

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by spacedmonkey — APPROVED** [review]
This change seems good to me. As this is a bug, I think we can get this into WP 6.3. Thoughts @peterwilsoncc ?

**Comment by peterwilsoncc** [comment]
@spacedmonkey Do you have any thoughts on tests I should add?

**Comment by spacedmonkey** [comment]
> @spacedmonkey Do you have any thoughts on tests I should add?

@peterwilsoncc I don't personally think this needs to have unit tests.

**Comment by spacedmonkey** [comment]
Committed https://core.trac.wordpress.org/changeset/56747

**Pull request closed without merging**
