### PR TITLE
Update custom CSS handling to be consistent with block global styles.

### PR DESCRIPTION
**Pull request by tellthemachines**
Trac ticket: https://core.trac.wordpress.org/ticket/61395

Syncs changes from https://github.com/WordPress/gutenberg/pull/62357.

Steps for testing:

1. Test with custom CSS added at base level and at block level, in theme.json or through the global styles UI.
2. With TT4 enabled, check that custom CSS for blocks is loaded in the front end only when the block is present on the page;
3. Add `add_filter( 'should_load_separate_core_block_assets', '__return_false', 11 );` to the theme's functions.php and check that custom CSS for all blocks always loads in the front end.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by aaronrobertshaw — APPROVED** [review]
Thanks for putting this together @tellthemachines 👍 

✅ Code changes align with Gutenberg PR
✅ With separate block assets loading, custom css is only loaded when block is present
✅ Without separate block assets loading, custom css is always loaded
✅ Same results when testing custom css via global styles or theme.json

LGTM ✨

**Review by andrewserong — COMMENTED** [review]
Code-wise this is looking good to me, too. The one difference I noticed while testing is that with a classic theme active, it appears that the customizer's Additional CSS doesn't update in real-time with this PR applied.

Can anyone reproduce this issue, or is it just my environment?

## Trunk

https://github.com/WordPress/wordpress-develop/assets/14988353/ad720a3b-c06e-4527-85ba-d3f3f7c22392

## This PR

https://github.com/WordPress/wordpress-develop/assets/14988353/e6d31cd4-9e8b-4a30-aa6c-105ac792b774

---

This feature is otherwise testing well for me in block themes, the site editor and post editor, and with the styles being output correctly on the site frontend.

**Comment by tellthemachines** [comment]
Thanks for reviewing, folks!

> Can anyone reproduce this issue, or is it just my environment?

I could reproduce that locally; it was due to a missing check that made sure dequeuing customizer CSS only happened for block themes. I've replaced the check now so things should work exactly as they do in trunk.

**Comment by tellthemachines** [comment]
I've just put up a PR to fix this in Gutenberg too: https://github.com/WordPress/gutenberg/pull/63331

**Comment by aaronrobertshaw** [comment]
Thanks for the quick fix 🚀 

I could replicate the issue and can confirm the latest tweak in https://github.com/WordPress/wordpress-develop/pull/6750/commits/56d544825335a7b4e24bbf8aff4279c6db8e15f7 fixes it.

| Before | After |
|---|---|
| <video src="https://github.com/WordPress/wordpress-develop/assets/60436221/8f07093b-630c-4972-bf59-f25986a05963" /> | <video src="https://github.com/WordPress/wordpress-develop/assets/60436221/88247430-0ebb-41f0-828e-e9412fbaa859" /> |

**Review by andrewserong — APPROVED** [review]
That's testing nicely for me in classic themes now, while block themes and custom CSS continue to work as expected. Thanks for the follow-up!

**Comment by tellthemachines** [comment]
Thanks for re-testing! Committed in [r58703](https://core.trac.wordpress.org/changeset/58703),

**Comment by noisysocks** [comment]
Thanks for committing this early in the 6.7 cycle ❤️

**Pull request closed without merging**
