### PR TITLE
Nav Menu: Localize "No Parent" and menu item labels in nav menu options

### PR DESCRIPTION
**Pull request by yogeshbhutkar**
### Description
Updated raw strings to use i18n functions.

Trac ticket: https://core.trac.wordpress.org/ticket/62402

### Screenshot of the fix:
Screenshot 2024-11-13 at 3 55 05 PM

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by desrosj — COMMENTED** [review]
Should the two ` of ` strings use `wp.i18n._x` instead of `wp.i18n.__` to provide additional context to translators? It may not be clear what is being translated.

**Comment by yogeshbhutkar** [comment]
Thanks, @desrosj for suggesting an improvement here.

Sure, it would be better to provide context to the translator. I've added a patch for the same. Thanks.

**Comment by desrosj** [comment]
@yogeshbhutkar one more change! @SergeyBiryukov confirmed in track that `wp.i18n.sprintf()` is actually the correct function.

**Comment by yogeshbhutkar** [comment]
Thanks, @desrosj. 

The changes are appended to the PR.

**Review by joedolson — APPROVED** [review]
I made a change purely for readability, but otherwise this is good to go.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/59426 & https://core.trac.wordpress.org/changeset/59431.

**Pull request closed without merging**
