### PR TITLE
Refactored WP_Debug_Data::debug_data() - get_wp_mu_plugins()

### PR DESCRIPTION
**Pull request by apermo**
Changed: Moving $info['wp-mu-plugins'] to own function

I've started a second parallel PR, a little lower, so that we should not get too many merge conflicts.

---

Follow up to https://github.com/WordPress/wordpress-develop/pull/7027 as discussed with @dmsnell and @costdev 

Summary of the coming steps:

1. [wp-filesystem](https://github.com/WordPress/wordpress-develop/pull/7065)
2. [wp-constants](https://github.com/WordPress/wordpress-develop/pull/7106)
3. [wp-database](https://github.com/WordPress/wordpress-develop/pull/7143)
4. [wp-server](https://github.com/WordPress/wordpress-develop/pull/7283)
5. wp-media
6. wp-plugins-active & wp-plugins-inactive
7. **wp-mu-plugins** (we are here)
8. wp-themes-inactive
9. wp-parent-theme
10. wp-active-theme
11. wp-dropins
12. wp-paths-sizes
13. wp-core

Refactoring WP_Debug_Data::debug_data(); into smaller functions for

* better maintainability
* reduced complexity
* preparation for future unit tests
* improved extensibility (see trac for details)
* added php7.2 style type hints
* fixed an error with `$parent_theme_auto_update_string` showing the value from `$auto_updates_string` (This will be handled only in Step 9)

Trac ticket: https://core.trac.wordpress.org/ticket/61648#ticket

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by apermo** [comment]
@dmsnell since we have our structure now, I've opened a second PR, I've opted to have it a little in the middle, so that we can easily rebase if needed with hopefully little to no merge conflicts.

**Comment by dmsnell** [comment]
@apermo I've merged `trunk` into this and hope I did that properly. how does it look? is this ready in your opinion for merging?

**Comment by apermo** [comment]
> @apermo I've merged `trunk` into this and hope I did that properly. how does it look? is this ready in your opinion for merging?

Looks good to me. @dmsnell

**Comment by dmsnell** [comment]
Merged in [[59011]](https://core.trac.wordpress.org/changeset/59011)
https://github.com/wordpress/wordpress-develop/commit/38243be931f7e3829b8cae96cedfb61a0d9c34fe

**Pull request closed without merging**
