### PR TITLE
Add irc6 and ircs

### PR DESCRIPTION
**Pull request by ct-martin**
Add the `irc6` and `ircs` to list of allowed protocols for links

Trac ticket: https://core.trac.wordpress.org/ticket/41432

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Thanks for the patch @ct-martin!

It'd be good to add an `@since` documentation noting that new allowed protocols. See the [PHP Doc Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#since-section-changelogs) for reference.

**Comment by ct-martin** [comment]
@TimothyBJacobs from what I understand, `@since` should be the version at which the change is available. The Trac ticket says `Future Release`, but should I put `5.6.0`? Thanks!

**Comment by TimothyBJacobs** [comment]
Yep! `5.6.0`.

**Comment by ct-martin** [comment]
@TimothyBJacobs thanks! Added and pushed changes (rebased on `master`)

**Comment by TimothyBJacobs** [comment]
Fixed in 4ad4eea. Thanks again for the patch @ct-martin!

**Pull request closed without merging**
