### PR TITLE
Revisions: slash meta values for previews

### PR DESCRIPTION
**Pull request by adamsilverstein**
Correct an issue where meta values with values like a quote `”` could not be previewed. update_metadata expects data to be slashed.

To test this bug:
1. publish a post with a footnote
2. add a quote to the end of the footnote
3. preview the post

expected: footnote shows quote

actual: footnote is missing or missing quote

Trac ticket: https://core.trac.wordpress.org/ticket/20564

See also: https://github.com/WordPress/gutenberg/pull/52988

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@adamsilverstein, If we remove the `wp_slash`, the unit tests pass successfully ✅. Do we still need to implement safeguard measures?

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @adamsilverstein for the PR. Approved with one question: https://github.com/WordPress/wordpress-develop/pull/5344#issuecomment-1740409018

**Review by spacedmonkey — APPROVED** [review]

**Comment by adamsilverstein** [comment]
> @adamsilverstein, If we remove the wp_slash, the unit tests pass successfully ✅. Do we still need to implement safeguard measures?

I added a test that failed before the patch, but removed it to get tests passing in https://github.com/WordPress/wordpress-develop/pull/5344/commits/6927209e425dac834183c5c45c0a62ac174d8906 because it was causing other tests to fail (I suspect because it wasn't cleaning up completely). I'm going to try to reintroduce it in another spot.

**Comment by adamsilverstein** [comment]
@mukeshpanchal27  - I reintroduced the test by putting it in the metaRevisions test file and cleaning it up a bit. This test fails before the PR and essentially reproduces the issue surfaced by the GB E2E test.

**Comment by adamsilverstein** [comment]
Trying again in [`413ac9f` (#5344)](https://github.com/WordPress/wordpress-develop/pull/5344/commits/413ac9fc4eb5299fe6bf738a8b57d98f6c2dc36a); I moved the tests to `tests/phpunit/tests/rest-api/rest-autosaves-controller.php` and simplified a bit.

**Comment by adamsilverstein** [comment]
Fixed in https://core.trac.wordpress.org/changeset/56745

**Pull request closed without merging**
