### PR TITLE
added tests for wp_filesize

### PR DESCRIPTION
**Pull request by pbearne**
Trac ticket: https://core.trac.wordpress.org/ticket/57171

### CODE REVIEW

**Comment by spacedmonkey** [comment]
There were unit tests in the original PR - https://github.com/WordPress/wordpress-develop/pull/2367/files#diff-032b8ca66e0285a30919e60d55165db1e4ab54666b9012512f9e003ca9e07b84

I may have forgotten to commit these 😮‍💨

**Comment by spacedmonkey** [comment]
> There were unit tests in the original PR - https://github.com/WordPress/wordpress-develop/pull/2367/files#diff-032b8ca66e0285a30919e60d55165db1e4ab54666b9012512f9e003ca9e07b84
> 
> I may have forgotten to commit these 😮‍💨

@SergeyBiryukov ^

**Comment by SergeyBiryukov** [comment]
Thanks for the PR!

It looks like there were some pre-existing tests for this function added in [r52837](https://core.trac.wordpress.org/changeset/52837) and moved to a separate file in [r54861](https://core.trac.wordpress.org/changeset/54861).

Keeping the ticket open for now to see if anything from this PR should be added to the existing tests (though at a glance it seems like they are mostly the same), as well as to commit [some other tests](https://github.com/WordPress/wordpress-develop/pull/2367/files#diff-032b8ca66e0285a30919e60d55165db1e4ab54666b9012512f9e003ca9e07b84) pointed out above.

**Comment by SergeyBiryukov** [comment]
I believe this is fixed as of [r54861](https://core.trac.wordpress.org/changeset/54861) and [r54863](https://core.trac.wordpress.org/changeset/54863).

**Pull request closed without merging**
