### PR TITLE
Media php strict comparison

### PR DESCRIPTION
**Pull request by deepakrohillas**
https://core.trac.wordpress.org/ticket/62009

### CODE REVIEW

**Comment by DingGuodong** [comment]
Oh, it's very confusing. I wander that why there is only one change in the file but there are 27 commits?  @deepakrohillas deepakrohilla Could you explain it for me? Thank you !

**Comment by mukeshpanchal27** [comment]
@DingGuodong, this is due to code committed in the branch and some upstream merges. Only the new changes need to be reviewed. When you have a moment, please review them and share your feedback here.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks for PR! In quick review LGTM.

**Review by aristath — APPROVED** [review]

**Comment by DingGuodong** [comment]
> @DingGuodong, this is due to code committed in the branch and some upstream merges. Only the new changes need to be reviewed. When you have a moment, please review them and share your feedback here.

Thanks for your reply. So, I think it is due to the committer pull some commits from another branch before request this PR.
It is too hard for the developer request one PR if in this way. Because of he need to merge many commits before request the PR. I hope this is not a common case. :)

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r59497](https://core.trac.wordpress.org/changeset/59497).

**Pull request closed without merging**
