### PR TITLE
Remove Navigation Area endpoints and utility functions

### PR DESCRIPTION
**Pull request by noisysocks**
This removes the Navigation Area endpoints and utility functions from Core. In https://github.com/WordPress/gutenberg/issues/36524 it was decided to remove the Navigation Area functionality form WP 5.9.

Trac ticket: https://core.trac.wordpress.org/ticket/54506

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by noisysocks** [comment]
Not sure why GitHub isn't letting me request a review from @getdave 🤔

**Comment by getdave** [comment]
> Not sure why GitHub isn't letting me request a review from @getdave 🤔

I guess because I haven't committed here before or something?

**Review by adamziel — COMMENTED** [review]
I don't see the actual JS assets removed as a part of this PR. I guess this is because there are none – webpack turns node_modules into a big JS bundle, but that's only during the build – we don't actually store it in this repo.

🚢

**Review by adamziel — APPROVED** [review]

**Comment by getdave** [comment]
I tried to testing this but my local WordPress develop setup wouldn't start up. Adam's 👍 is good enough for me.

**Review by spacedmonkey — APPROVED** [review]

**Comment by spacedmonkey** [comment]
This looks good @noisysocks . Happy to commit?

**Comment by getdave** [comment]
> This looks good @noisysocks . Happy to commit?

If you wouldn't mind committing @spacedmonkey I think we're good to go.

**Comment by hellofromtonya** [comment]
Committed in changesets https://core.trac.wordpress.org/changeset/52272, https://core.trac.wordpress.org/changeset/52273, and https://core.trac.wordpress.org/changeset/52274.

**Pull request closed without merging**
