### PR TITLE
Block Support Styles: Add priority param

### PR DESCRIPTION
**Pull request by ockham**
Backport of https://github.com/WordPress/gutenberg/pull/41015.

Needed for the package-sync "dry run" PR: https://github.com/WordPress/wordpress-develop/pull/3154#discussion_r958841837

### Questions:

- [ ] Should this include other related changes, e.g. https://github.com/WordPress/gutenberg/pull/43073?
- [ ] ~Does this need a (basic) unit test?~ _Edit: I'm leaning towards No, see https://github.com/WordPress/wordpress-develop/pull/3158#issuecomment-1234327286._

cc/ @glendaviesnz @ramonjd for review 😊 

Gutenberg tracking issue: https://github.com/WordPress/gutenberg/issues/43440
Trac ticket: https://core.trac.wordpress.org/ticket/56467

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
Thanks @ockham LGTU(s)

**Comment by ockham** [comment]
I've filed a counterpart PR for GB: https://github.com/WordPress/gutenberg/pull/43779

**Comment by ockham** [comment]
I've thought about adding a unit test, but I'm now leaning against, for the following reasons:

- `wp_enqueue_block_support_styles` is pretty straight-forward (especially compared to other functions in the same file -- most of which don’t have unit test coverage.) -- It basically just calls `add_action()`.
- It passes a closure to `add_action()`. This means we can't really have a test that checks for that closure (e.g. via [`has_action()`](https://developer.wordpress.org/reference/functions/has_action/), as we can't reference it from outside the function scope.
- AFAICS, this leaves us with some indirect testing, such as running `wp_enqueue_block_support_styles()`, and then `wp_head()` (or `wp_footer()`, respectively), to see if the CSS that was passed to the function was added to the header (or footer, respectively). However, it's kinda messy to look for that styling inside of the (fairly big) header/footer.
- Finally, there isn't really any way to test if the `$priority` was respected -- which is the change we're actually making here.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/54048.

**Pull request closed without merging**
