### PR TITLE
Accept Core Prefix as Trac ticket links.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Core-61865

### CODE REVIEW

**Review by martinkrcho — COMMENTED** [review]
@peterwilsoncc generally your change looks good and it's very simple. I would be happy to merge it as is.

However, GitHub created "Trac Ticket Missing" [comment](https://github.com/WordPress/wordpress-develop/pull/7182#issuecomment-2285225549) on this PR despite your change. Is this expected? I assume it's not using the new logic until merged. Is there a way to force this?

**Comment by peterwilsoncc** [comment]
@martinkrcho I suspect it's because the action uses `pull_request_target` rather than `pull_request` for the action so it's running the version in trunk rather than this branch.

I'm not sure of a way to force this short of a yolo commit and testing it out.

I tested it on my own fork with the `pull_request` event and it seemed to work but it would be good to get a logic check.

**Review by martinkrcho — APPROVED** [review]
Thanks for checking, @peterwilsoncc .

Logic looks good to me.

Switching from `pull_request_target` to `pull_request` would make reviews such as this one easier (we could see the changes applied right away). Could you perhaps create a separate ticket to investigate further? There are some security implications to consider, see https://runs-on.com/github-actions/pull-request-vs-pull-request-target/.

**Comment by peterwilsoncc** [comment]
Merged [r58901](https://core.trac.wordpress.org/changeset/58901) / https://github.com/WordPress/wordpress-develop/commit/efee9258317fda297e11be7c5c418816fdd1f6bb

> There are some security implications to consider, see https://runs-on.com/github-actions/pull-request-vs-pull-request-target/.

I'll need to check with someone but I think that's why it was changed at some point although I could be mistaken.

**Pull request closed without merging**
