### PR TITLE
Remove unnecessary and potentially confusing logic to prevent certain combinations of robots directives

### PR DESCRIPTION
**Pull request by felixarntz**
Trac ticket: https://core.trac.wordpress.org/ticket/52713

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by peterwilsoncc — CHANGES_REQUESTED** [review]
Looks like most of the filter functions can be removed too
* `add_follow_directive`
* `add_nofollow_directive`
* `remove_follow_directive`
* `add_archive_directive`
* `add_noarchive_directive`

Otherwise LGTM, thanks

**Comment by felixarntz** [comment]
@peterwilsoncc Thanks, updated!

**Review by peterwilsoncc — APPROVED** [review]
LGTM, thanks

**Comment by felixarntz** [comment]
Closing, as this was committed a long time ago in https://core.trac.wordpress.org/changeset/50566.

**Pull request closed without merging**
