### PR TITLE
Deprecate media.php inside wp-admin

### PR DESCRIPTION
**Pull request by kebbet**
https://core.trac.wordpress.org/ticket/57612

### CODE REVIEW

**Comment by audrasjb** [comment]
I refreshed the PR to update the `since` mention add for trunk merge purpose :)

**Comment by kebbet** [comment]
> I refreshed the PR to update the `since` mention add for trunk merge purpose :)

Should the last line also be updated to use `6.3.0` ?

**Comment by audrasjb** [comment]
Ah yes, updated :)

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/55647

**Pull request closed without merging**
