### PR TITLE
Feat: Added has_translation function to l10n.php 

### PR DESCRIPTION
**Pull request by mchirag2002**
The added function `has_translate()` tackles the edge case where the user might need to check if the translation exists or not before actually translating the string.
The function returns the translation of the string if it exists and returns `false` if in case the translation does not exist.
This should potentially save the multiple calls for the functions like once to check whether translation exists or not and then to actually translate.

Trac ticket: https://core.trac.wordpress.org/ticket/52696

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by swissspidy** [comment]
This does not work because you don't know if the returned string is the original or just a translation that happens to be identical to the original string.

That's why #6649 works better.

**Comment by mchirag2002** [comment]
@swissspidy Actually in this case the original string would never be returned. If there is no translation present, it would return a boolean false and if there exists a string which has a translation which is identical, only in such case the translated string shall be returned.
Internally the translate function also utilises the same `locate_translate()` function but this reduces the number of function calls you have to make to get the translation of all the strings.

**Comment by swissspidy** [comment]
> if there exists a string which has a translation which is identical, only in such case the translated string shall be returned.

And that is exactly the problem I am describing. This is not desired here.

**Comment by swissspidy** [comment]
Closing in favor of #6805 which is closer and adds tests

**Pull request closed without merging**
