### PR TITLE
Allow remote pattern registration in theme.json when core patterns are disabled

### LINKED ISSUE #41282: When removing core pattern, allow theme.json pattern slugs to be listed in inserter
## What problem does this address?
At the moment, `remove_theme_support( 'core-block-patterns' ); is an all or nothing with allowing pattern directory patterns to be viewed in the inserter. 
Being able to still use the theme.json registration of pattern via slugs from the pattern directory, allows a curated list of patterns and more granular control. 

## What is your proposed solution?
The theme developer would set in functions.php `remove_theme_support( 'core-block-patterns' );` 
and set in theme.json the list of pattern allowed: `"patterns": [ "short-text-surrounded-by-round-images", "partner-logos" ]`

There could be a check that if there is a theme.json pattern setting, it would allow them to be visible in the Inserter. 
Instead an "Disallow all" it should be an explicit allow. 

With the growing number of pattern in the directory, a curation would help with the exposure of patterns in the editor. The more patterns there are the more theme developer would want to restrict the visiblity. This feature would give them the means instead of just blocking all patterns from the directory, select the few that should work well.

### PR DESCRIPTION
**Pull request by ndiego**
Fixes: https://github.com/WordPress/gutenberg/issues/41282

In 6.0 we now have functionality that allows you to [register selected remote patterns](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/#patterns) (from the Pattern Directory) via theme.json. While this is great, it requires you to fully enable all core and remote patterns. This can be a blocker to adoption.

Many theme authors want to have all core and remote patterns disabled by default using remove_theme_support( 'core-block-patterns' ). This ensures they are serving only patterns relevant to their theme to customers/clients.

This PR/Trac ticket removes the theme support check from the function that registers remote patterns specified in theme.json. This allows theme authors to disable core patterns but then selectively register the ones they want from the Pattern Directory. We assume that if a theme author intentionally specifies patterns in theme.json, they intend for them to be present in the pattern inserter and the check is not required.

This change will make the Pattern Directory more appealing/usable from the theme author's perspective.

Note, that while this issue is technically not a "bug", it is a pretty large blocker for Pattern Directory adoption and I feel should be considered for 6.0.1.

Trac ticket: https://core.trac.wordpress.org/ticket/56112

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ryelle** [comment]
I think removing the `get_theme_support( 'core-block-patterns' )` check makes sense here — these aren't core patterns. But the `should_load_remote_block_patterns` check should stay, in case someone wants to explicitly disable external API requests.

For reference, there's only [1 theme in the wp.org directory](https://www.wpdirectory.net/search/01G6XB92F1KBQR38EZZGGDJMGN) that disables the remote loading, but it loads its patterns locally.

**Comment by ndiego** [comment]
Thanks for the feedback @ryelle! That makes good sense. I have updated the PR and added back the `should_load_remote_block_patterns`.

**Review by ryelle — APPROVED** [review]
Looks good now 👍🏻

**Comment by ndiego** [comment]
Thanks @ryelle, are you able to merge? I don't have permission on this repo. In the meantime, I will put together the corresponding PR needed on the Gutenberg side.

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/53793

**Pull request closed without merging**
