### PR TITLE
Change `aria-label` escaping to `esc_attr()`

### PR DESCRIPTION
**Pull request by sabernhardt**
Trac ticket: https://core.trac.wordpress.org/ticket/58387

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @sabernhardt, The changes look good to me.

**Comment by mukeshpanchal27** [comment]
@sabernhardt one question: `$aria_label` is use value of `$screen_reader_text` so do we need to update `$screen_reader_text` also?

**Comment by sabernhardt** [comment]
The standard template uses the `$screen_reader_text` variable inside an `h2` element.

(Without an `$aria_label` argument, the function would reuse `$screen_reader_text` for both the `aria-label` attribute and the heading. They still would have different escaping functions.)

**Comment by mukeshpanchal27** [comment]
Make sense, thanks @sabernhardt for clarification.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r55863](https://core.trac.wordpress.org/changeset/55863).

**Pull request closed without merging**
