### PR TITLE
Update erase-personal-data.php

### PR DESCRIPTION
**Pull request by azharckra**
Removed unwanted space at the end of the string.

Removed unwanted space at the end of the string.

Trac ticket: https://core.trac.wordpress.org/ticket/59473

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Nice catch. Look good to me.

**Comment by kebbet** [comment]
PR looks good to me, I double checked that the following strings does not need that extra space. Good catch!

**Review by kebbet — APPROVED** [review]

**Review by krupal-panchal — APPROVED** [review]
PR LGTM

**Review by hellofromtonya — APPROVED** [review]
Good catch! Marking this patch for commit 👍

**Comment by hellofromtonya** [comment]
Committed via changeset https://core.trac.wordpress.org/changeset/56734. Thank you everyone for your contributions :)

**Pull request closed without merging**
