### PR TITLE
Improve Supported Versions table accessibility in SECURITY.md

### PR DESCRIPTION
**Pull request by audrasjb**
https://core.trac.wordpress.org/ticket/57222

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
This looks good to me.

In your experience do you know if emoji are problematic for screen readers? The question behind the question is will screen reader users hear the first row as "six point one point ex white check mark yes"?

If a simple "yes" will be better for accessibility, I am happy to just go with that.

**Comment by audrasjb** [comment]
Good question @peterwilsoncc :)
It seems that assistive technologies will restitute ✅ as "White Heavy Check Mark".
The recommendation is to avoid using emojis as a replacement for text.

But it's also recommended to place the textual information before the emoji…
Shouldn't we completely remove the emojis from this documentation?

**Comment by peterwilsoncc** [comment]
> Shouldn't we completely remove the emojis from this documentation?

Yeah, let's do that. It's unambiguously accessible.

**Comment by audrasjb** [comment]
@peterwilsoncc I replaced all emojis with plain text words. Really, I think it doesn't hurt :)

**Comment by peterwilsoncc** [comment]
Merged https://core.trac.wordpress.org/changeset/54919

**Pull request closed without merging**
