### PR TITLE
Patch jQuery deprecations in core

### PR DESCRIPTION
**Pull request by Clorith**
Trac ticket: https://core.trac.wordpress.org/ticket/51812

This is an initial patch, with many minor adjustments to a wide array of core files.

Updating the jQuery usage in core is something we should get in early, and will also require some upstream patches to libraries used by WordPress (or, in some cases, updates may exist, the initial focus of this PR is the direct use in core).

A fair amount of deprecations that are not addressed in this PR are being thrown by jQuery UI.

The process taken to identify deprecation issues in core has been a manual one, the initial plan here was to merely do some fancy regex search replace commands, but a lot of components built by core are using similar function names and argument parameters, so instead this has been a manual endeavor, and probably should remain so to keep accidentally breaking changes to a minimum during the alpha stage.

In testing, each admin page was visited, and deprecation warnings addressed individually until there were external libraries throwing warnings. Individual interactions on the page are performed (for example on the classic post editor screen, change the publication time, change the post status), although I make no guarantee there's not scenarios where an interaction may have been missed, so would be good to get more eyes involved.

One exception that is in core, but has not been patched up
```js
// Accessibility mode.
$( window ).on( 'load', function() {
	component.setupAccessibleMode();
});
```

This is used in the different components under [`src/js/_enqueues/wp/widets`](https://github.com/WordPress/wordpress-develop/tree/master/src/js/_enqueues/wp/widgets) which are triggering "too late" in some scenarios, and jQuery throws a warning that the load event has already fired by the time the component is initialized.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by azaozz** [comment]
Great job!

Just a small suggestion: seems it may be better to replace `$.trim( var )` with `''.trim( var )` instad of `var.toString().trim()`. The last would throw an error when `var` is undefined, both `$.trim()` and `''.trim()` would return an empty string. All browsers since IE10 have that, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/trim. For multiple uses can even set local version: `var trim = ''.trim;` at the top, etc. Alternatively can do `var = var || ''` before using `var.toString()`. 

For the way `$( window ).on( 'load',` is used in the widgets js perhaps may need to look at `Document.readyState`, see:  https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState. Seems it was incorrect before the jQuery update but now that throws a warning.

**Comment by Clorith** [comment]
Good catch on the `.trim()` bit, I half expected it to be validated before it reached the point of trying to use it.

The `.on( 'load'` bit has likely been wrong for some time as you say, yeah, isn't the `readyState` technically the same here though, and would still be "too late"? Or am I misreading you perhaps?

**Comment by azaozz** [comment]
> ...isn't the readyState technically the same

Yeah, `document.onreadystatechange` can be used instead of "DOM ready", etc. Thinking it can look at the "property" `document.readyState`. Perhaps something like:

```js
if ( document.readyState === 'complete' ) {
    // Page is fully loaded.
    component.setupAccessibleMode();
} else {
    // Page is still loading.
    $( window ).on( 'load', function() {
        component.setupAccessibleMode();
    });
}
```

**Comment by Clorith** [comment]
Ahh, I see what you mean then, that does make sense then.

I've patched the widgets to use your suggestion above (it made the most sense right off the bat).

For the `toString().trim()` section, I chose the option of `var = var || '';`, as a quick check showed it being the way core has previously done it in another location as well, so sticking to the same made sense.

**Comment by Clorith** [comment]
Patch applied, new PR for future enhancements will follow.

**Pull request closed without merging**
