### PR TITLE
Twenty Thirteen: Correct front-end display of Cover block children

### PR DESCRIPTION
**Pull request by kjellr**
Trac ticket: https://core.trac.wordpress.org/ticket/51224

---

This PR clears up the front-end display of cover block children. To match the editor, they have their margins set to `auto`, and are always the default width.*

_*I find this part weird, but that's how these appear in the editor, so I figured let's match that._  

Test content: https://gist.github.com/kjellr/cb83095e95b28cc914e970ca0c7f7b18

## Screenshots

_Before:_ 
Screen Shot 2021-02-11 at 12 58 44 PM

_After:_
Screen Shot 2021-02-11 at 12 55 02 PM

_Editor (for reference):_
wordpress-develop test_build_wp-admin_post php_post=13 action=edit (1)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by melchoyce** [comment]
Seeing some weirdness in the placeholder still:

image

Everything else seems to be working 👍

**Comment by kjellr** [comment]
That's the Group block placeholder, right? I hadn't touched that block in this PR, so I think that's a separate bug. I took a quick look now, but the fix isn't obvious, so I suggest we punt that to a separate bug report + PR.

**Comment by melchoyce** [comment]
Sounds good 👍

**Review by ryelle — APPROVED** [review]

**Comment by ryelle** [comment]
Committed in [r50346](https://core.trac.wordpress.org/changeset/50346).

**Pull request closed without merging**
