### PR TITLE
59360: Add unit test coverage for `update_network_option`

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
This PR check the behaviour of `update_network_option()`

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
Hello, @felixarntz, @joemcgill, and @spacedmonkey, This PR demonstrates the behavior of the current `update_network_option()` function. @costdev provided valuable suggestions and assistance in identifying backward compatibility (BC) and edge cases, which we have addressed and included in the unit tests.

When you have some free time, could you please review it? Your feedback would be greatly appreciated.

As we are approaching the RCs, we may defer this, but committing these older unit tests will facilitate our progress in implementing code changes and adding new unit tests. Thank you!

**Review by spacedmonkey — APPROVED** [review]
This unit tests look good. 

I think we have enough time next week to get the tweak to update_network_option committed.

**Review by felixarntz — APPROVED** [review]
Thanks @mukeshpanchal27, this looks excellent!

I'll commit this shortly so that we can then work on the actual change for 59360 in a separate PR against the existing tests, to make sure they pass without changes.

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/56797

**Pull request closed without merging**
