### PR TITLE
PHP 8.2 | Tests: explicitly declare all properties

### PR DESCRIPTION
**Pull request by jrfnl**
Dynamic (non-explicitly declared) properties are deprecated as of PHP 8.2 and are expected to become a fatal error in PHP 9.0.

In each of the cases included in this PR, one or more individual tests set a property to allow a filter/action access to certain information.

This commit:
* Explicitly declares these properties and documents in which tests they are being used.
* Add a reset to the default value of the property to a pre-existing `tear_down()` method or adds that method specifically for that purpose.
    This ensures that tests can not accidentally "taint" each other.

As these properties are being declared on test classes, I'm making them all `private`.
Even though the original dynamic property was `public`, this should not be considered a BC break as this only involves test classes.

Includes:
* In the `Tests_Post_Query` class, there were two tests assigning a value to an undeclared `$post_id` property, but subsequently not using the property, so those assignments should have been to a local variable (if they should be assignments at all).
* In the `Test_User_Capabilities` class, the property name had a leading `_` underscore. This is an outdated PHP 4 practice to indicate a `private` property. As PHP 4 is no longer supported, I have removed the leading underscore from the property name.
* In the `Tests_User_Capabilities` class, an unused `$_role_test_wp_roles_role` property was declared somewhere in the middle of the class. I have removed this property.
    This was probably intended to be the declaration of the `$_role_test_wp_roles_init` property, but then the name used in the assignments was changed, but the property declaration name was not.

Trac ticket: https://core.trac.wordpress.org/ticket/56033

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by jrfnl** [comment]
Rebased without changes to get passed an imaginary merge conflict.

**Comment by jrfnl** [comment]
> Rebased without changes to get passed an imaginary merge conflict.

And again...

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r53942](https://core.trac.wordpress.org/changeset/53942).

**Comment by jrfnl** [comment]
Thanks @SergeyBiryukov !

**Pull request closed without merging**
