### PR TITLE
Initial patch for old files update for WordPress 6.7

### PR DESCRIPTION
**Pull request by peterwilsoncc**
Trac ticket: https://core.trac.wordpress.org/ticket/62150

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by dream-encode — COMMENTED** [review]
@peterwilsoncc  Thanks!  Looks good so far!  Nice to have an early PR to have other folks review.

We'll rerun the `^D` and `^A` during the Dry Run to make sure the updates here are still the same.

**Review by pbiron — APPROVED** [review]
LGTM.  I compared this list of deleted files/dirs against the list generated by WP_CLI when upgrading from 6.6.2 to 6.7-beta3 and they are consistent.

By consistent I mean that WP_CLI deletes individual files like _wp-includes/SimplePie/{dir}/{file}_ and this patch deletes _wp-includes/SimplePie/{dir}_.

**Review by pbiron — COMMENTED** [review]
Not necessary, but wouldn't hurt to add a reference to https://core.trac.wordpress.org/changeset/59141 in this comment.

**Comment by peterwilsoncc** [comment]
Proposed commit message:

> Upgrade/Install: Update the $_old_files array for 6.7.
> 
> Update the array of files to be removed during the upgrade routine for WordPress 6.7. The upgrade of the SimplePie library in [59141] included a significant refactor requiring a number directories be removed.
>
> Props, fixes, etc

**Comment by pbiron** [comment]
> Not necessary, but wouldn't hurt to add a reference to https://core.trac.wordpress.org/changeset/59141 in this comment.

I now realize I did something wrong.  I meant the above to be "add that reference to comment at the being of the PR that explains about the SimplePie update" ;-)

**Comment by peterwilsoncc** [comment]
> I now realize I did something wrong. I meant the above to be "add that reference to comment at the being of the PR that explains about the SimplePie update" ;-)

Yes, that makes way more sense. Pushed. It's early, that's my excuse for misunderstanding ;)

**Review by kapilpaul — APPROVED** [review]

**Comment by dream-encode** [comment]
Committed to core in https://core.trac.wordpress.org/changeset/59386.

**Pull request closed without merging**
