### PR TITLE
Bundled Themes: Bump themes versions for WP 5.9.

### PR DESCRIPTION
**Pull request by audrasjb**
Trac ticket: https://core.trac.wordpress.org/ticket/54783

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by desrosj — CHANGES_REQUESTED** [review]
It looks like the package/package-lock file updates are missing here.

Also, for the themes with a build process, you'll need to run the build script to ensure there are no changes that were missed. There's at least one theme that includes the version in a built file.

**Review by desrosj — APPROVED** [review]
Alright this is good to go!

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/52618.

**Pull request closed without merging**
