### PR TITLE
Fix wp_template renaming when `hooked_block_types` filter exists

### PR DESCRIPTION
**Pull request by alshakero**
The ticket explains the problem.

Trac ticket: https://core.trac.wordpress.org/ticket/61550

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by ockham — APPROVED** [review]
LGTM! Thank you very much for the fix!

**Review by ockham — CHANGES_REQUESTED** [review]
Apologies, I might've spoken too soon 😅 

I remembered to look at the comment for [this PR](https://github.com/WordPress/gutenberg/pull/60071) that fixed the same issue for `wp_navigation` post types.

Note [this comment](https://github.com/WordPress/gutenberg/pull/60071/files#r1535417586) on using `isset` vs `empty`:

> `empty()` is bad, because it would miss the cases where the `post_content` is legitimately changed to an empty string. `isset()` is better.

Specifically, per https://github.com/WordPress/wordpress-develop/pull/6867, we could hit an edge case where a hooked block would be injected as the first or last child of an (otherwise empty) Template Part block. If we use `empty()`, this isn't going to work.

We should probably add some test coverage in `tests/phpunit/tests/block-templates/injectIgnoredHookedBlocksMetadataAttributes.php` to cover the case where `$changes->post_content` isn't set (to make sure that https://core.trac.wordpress.org/ticket/61550 is fixed), and another test to cover the case I described in the previous paragraph.

(I can take care of those things next week if you don't have time. Unfortunately, this will mean the fix won't make it into 6.6.1 and will have to wait for 6.6.2 instead.)

**Comment by alshakero** [comment]
Oooh great catch! How about ~~`array_key_exists`~~ `property_exists` which seems even more careful?

**Comment by ockham** [comment]
> Oooh great catch! How about ~`array_key_exists`~ `property_exists` which seems even more careful?

So the only difference between `property_exists()` and `isset()` is that the latter returns `false` if the property exists but is `null`, right? In that case, I'd stick with `if ( ! isset( $changes->post_content ) ) { return $changes; }`, since it'll bail if `$changes->post_content === null`. This is fine IMO, since it's unclear how we'd otherwise apply the Block Hooks algorithm to a post content that's `null`; we'd effectively have to cast it to `''` after all.

It's also more consistent with [what we're doing with `wp_navigation`](https://github.com/WordPress/wordpress-develop/blob/5a30482419f1b0bcc713a7fdee3a14afd67a1bca/src/wp-includes/blocks.php#L1084-L1090) 🙂 Finally, it's hopefully [a rather academic scenario only](https://github.com/WordPress/wordpress-develop/blob/5a30482419f1b0bcc713a7fdee3a14afd67a1bca/src/wp-includes/rest-api/endpoints/class-wp-rest-templates-controller.php#L594-L602) that `$changes->post_content === null`.

**Comment by alshakero** [comment]
Hi @ockham! Thanks for addressing your feedback. I was working on it at the same time and only realized because I couldn't push. Here's my take on the test in case it helps

```php
/**
	 * @ticket 61550
	 */
	public function test_hooked_block_types_filter_with_renamed_template_part() {
		$action = new MockAction();
		add_filter( 'hooked_block_types', array( $action, 'filter' ), 10, 4 );

		$changes             = new stdClass();
		$changes->ID         = 1;
		$changes->post_type  = 'wp_template_part';
		$changes->post_title = 'new title';
		$cloned_changes      = unserialize( serialize( $changes ) );

		$result = inject_ignored_hooked_blocks_metadata_attributes( $changes );

		// Ensure same reference.
		$this->assertSame(
			$changes,
			$result,
			'Should leave the changes object untouched if `post_content` is not set.'
		);

		// Ensure same values.
		$this->assertTrue(
			$result == $cloned_changes, // phpcs:ignore Universal.Operators.StrictComparisons.LooseEqual -- == compares all props and their values.
			'Should leave the changes object untouched if `post_content` is not set.'
		);

		$changes               = new stdClass();
		$changes->ID           = 1;
		$changes->post_type    = 'wp_template_part';
		$changes->post_title   = 'new title';
		$changes->post_content = 'new content';
		$cloned_changes        = unserialize( serialize( $changes ) );

		$result = inject_ignored_hooked_blocks_metadata_attributes( $changes );

		$this->assertNotSame(
			$changes,
			$result,
			'Should process the changes object if `post_content` is set.'
		);

		$changes               = new stdClass();
		$changes->ID           = 1;
		$changes->post_type    = 'wp_template_part';
		$changes->post_title   = 'new title';
		$changes->post_content = '';
		$cloned_changes        = unserialize( serialize( $changes ) );

		$result = inject_ignored_hooked_blocks_metadata_attributes( $changes );

		$this->assertNotSame(
			$changes,
			$result,
			'Should process the changes object if `post_content` is set to an empty string.'
		);
	}
```

**Comment by ockham** [comment]
> Hi @ockham! Thanks for addressing your feedback. I was working on it at the same time and only realized because I couldn't push.

Oh no, I should've posted a comment to let you know! Apologies, I didn't mean to make you duplicate work.

Anyway, thank you for sharing your patch! I'll have a look if there's anything to incorporate into the tests and will probably land the PR later today 😊

**Review by ockham — APPROVED** [review]

**Comment by ockham** [comment]
Committed to Core in https://core.trac.wordpress.org/changeset/58785.

**Comment by ockham** [comment]
Backported to the 6.6 branch in https://core.trac.wordpress.org/changeset/58802.

**Pull request closed without merging**
