### PR TITLE
51956: Fix RSS fatal on category/tag/archive feeds

### PR DESCRIPTION
**Pull request by iandunn**
This is still a WIP, but this demonstrates one possible fix.

Trac ticket: https://core.trac.wordpress.org/ticket/51956

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
Why this fix over the patch in https://core.trac.wordpress.org/attachment/ticket/51056/51056.diff?

**Comment by TimothyBJacobs** [comment]
🤦 I misread your comment as that patch did work, never mind!

**Comment by iandunn** [comment]
No worries :)

**Comment by iandunn** [comment]
Merged in https://core.trac.wordpress.org/changeset/49803

**Pull request closed without merging**
