### PR TITLE
Backport change.

### PR DESCRIPTION
**Pull request by spacedmonkey**
Trac ticket:  https://core.trac.wordpress.org/ticket/58231

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by oandregal** [comment]
I see this backports https://github.com/WordPress/gutenberg/pull/47833 and https://github.com/WordPress/gutenberg/pull/48759 Noting so we don't forget linking this to the original gutenberg PRs and the props to `t-hamano`.

I also see that there is a related ticket https://core.trac.wordpress.org/ticket/58193 and that Felix mentioned he'll work on backporting everything https://github.com/WordPress/gutenberg/pull/47833#issuecomment-1532196824

Changes seem fine to me, though.

**Comment by oandregal** [comment]
There is no process for backports, it changes from person to person. I can share what I do when I backport and what I find helpful:

- Link to all the Gutenberg PRs that are backported in the PR description (in addition to the trac ticket).
- Link to the backport PR in the original Gutenberg PRs: https://github.com/WordPress/gutenberg/pull/47833#issuecomment-1536176801 and https://github.com/WordPress/gutenberg/pull/48759#issuecomment-1536173547

Not that this is mandatory in any way, though I've found it very helpful.

**Review by joemcgill — APPROVED** [review]
The approach seems good to me, and given that this is already been in Gutenberg for a while should be fine to commit.

**Comment by tellthemachines** [comment]
Hi! To confirm, this is meant to be a separate piece from #4380? 

I added this PR to the 6.3 board, please feel free to move it to "needs core commit" if it's good to go!

**Comment by spacedmonkey** [comment]
Committed. https://core.trac.wordpress.org/changeset/55907

**Comment by spacedmonkey** [comment]
> Hi! To confirm, this is meant to be a separate piece from #4380?
> 
> I added this PR to the 6.3 board, please feel free to move it to "needs core commit" if it's good to go!

@tellthemachines I committed as I wanted to unblock my ticket. Let's backport that separately.

**Comment by tellthemachines** [comment]
Thanks @spacedmonkey !

**Pull request closed without merging**
