### PR TITLE
Update `caniuse` and regenerate CSS

### PR DESCRIPTION
**Pull request by desrosj**
Trac ticket: https://core.trac.wordpress.org/ticket/59657.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@desrosj Do we need `package-lock.json` changes?

**Comment by desrosj** [comment]
@mukeshpanchal27 In this case, yes. The package that needs to be updated is not a direct dependency, so it's only defined within the lock file.

**Review by gziolo — APPROVED** [review]
Nice. Everything looks good. @sirreal, was it necessary for anything related to bundling Interactivity code?

**Comment by sirreal** [comment]
Yes, we hit problems and cherry-picked the package-lock changes here to unblock this work: https://github.com/WordPress/wordpress-develop/pull/5922#issuecomment-1910673494

When this PR lands that removes a blocker 👍

**Comment by desrosj** [comment]
I'm going to commit this since this blocks other work and is a reasonable change to make. But I do have some concerns around the frequent churn related to these updates has caused recently. I [documented these changes on the Trac ticket](https://core.trac.wordpress.org/ticket/59657#comment:2).

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/57363.

**Pull request closed without merging**
