### PR TITLE
Updated jquery migrate to version 3.4.0

### PR DESCRIPTION
**Pull request by stalukder03**
Ticket Link: https://core.trac.wordpress.org/ticket/56743

### CODE REVIEW

**Comment by audrasjb** [comment]
Ah. Looks like your PR comes from your `trunk` branch @stalukder03, so I'm unable to resolve the current conflicts. Would you like to open a new PR for this change, please?

**Comment by stalukder03** [comment]
Hi @audrasjb 
Accidentally it gets merged instead of creating a new PR. FYI, I am new to core contributions as well as GitHub actions. I am really sorry for this type of mistake.

**Comment by audrasjb** [comment]
Thanks for resolving the issue!

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/55237

**Pull request closed without merging**
