### PR TITLE
Add the performance testing workflow to the regular testing list.

### PR DESCRIPTION
**Pull request by desrosj**
This adds the Performance testing workflow proposed in #4139 to the old branches workflow to ensure it runs semi-regularly in branches that support it (6.2 forward).

For this to be committed, #4139 should be committed to `trunk` AND the 6.2 branch should be created in WordPress SVN.

Trac ticket: https://core.trac.wordpress.org/ticket/57687.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by felixarntz — APPROVED** [review]
Thanks @desrosj!

~~I assume we want to hold off committing this until #4139 has been committed?~~ I should read PR descriptions 😆 

On that note, do you mean "6.3 branch should be created" in your PR description?

**Comment by desrosj** [comment]
> On that note, do you mean "6.3 branch should be created" in your PR description?

Nope, 6.2 is accurate. If this change is merged into `trunk` prior to the `6.2` branch existing, it will result in an error because the workflow cannot dispatch a run of the performance testing workflow in a non-existent branch.

**Comment by joemcgill** [comment]
Thanks @desrosj. I'm not familiar with the "old branches" workflow. Can you explain why we would want to periodically run performance metrics on old branches aside from when changes are made? Is this mainly just to ensure that the workflows are still working and aren't in need of some maintenance, or is there another reason the old branches workflow exists?

**Comment by desrosj** [comment]
> Is this mainly just to ensure that the workflows are still working and aren't in need of some maintenance

This is the primary reason.

There can be other situations where some workflows start failing unexpectedly, but I don't know that there are any for this specific workflow.

One that comes to mind is the PHPUnit testing workflow. Recently, specific versions of PHP started failing because the local Docker containers had not been updated for several months (GitHub stops running `schedule` events after ~3 months when a repository is completely inactive). Once this was fixed, a newer point release of PHP introduced some problems.

**Comment by desrosj** [comment]
Merged in https://core.trac.wordpress.org/changeset/55507.

**Pull request closed without merging**
