### PR TITLE
Reinstate the `wpdb::$use_mysqli` propert

### PR DESCRIPTION
**Pull request by johnbillion**
Trac ticket: https://core.trac.wordpress.org/ticket/59846

### CODE REVIEW

**Comment by johnbillion** [comment]
I think this would benefit from a unit test to prevent future breakage. I'll work on one shortly.

**Review by joemcgill — APPROVED** [review]
Nice sleuthing. I wonder if we should add a conditional in the `__get()` magic method that would return a deprecation warning if this property is accessed?

**Comment by hellofromtonya** [comment]
>I  wonder if we should add a conditional in the __get() magic method that would return a deprecation warning if this property is accessed?

**Comment by hellofromtonya** [comment]
Sorry, cat on keyboard

**Comment by hellofromtonya** [comment]
>I  wonder if we should add a conditional in the __get() magic method that would return a deprecation warning if this property is accessed?

Could, but then should also look at the other magic methods too. Thinking for this quick fix, restoring the property makes the most the sense.

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/57089 to `trunk` and https://core.trac.wordpress.org/changeset/57090 to the 6.4 branch.

**Pull request closed without merging**
