### PR TITLE
Editor: Sync Gutenberg Packages for WordPress 6.5 RC 1

### PR DESCRIPTION
**Pull request by youknowriad**
Sync Gutenberg to WP Core for WordPress 6.5 RC 1. Based on [this PR](https://github.com/WordPress/gutenberg/pull/59541/) in the Gutenberg repo:

Trac ticket: https://core.trac.wordpress.org/ticket/60315
Trac ticket: https://core.trac.wordpress.org/ticket/60665

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
I tested and few features from the included PRs and they seem ok.

However, I looked on the front of the site and saw this error:

```
Fatal error: Uncaught Error: Call to undefined function wp_interactivity_data_wp_context() in /var/www/html/wp-includes/blocks/navigation.php:555
```

**Comment by youknowriad** [comment]
@getdave yes, the patch for that one is ready to. @swissspidy is just waiting for the current package update to land first.

**Review by getdave — APPROVED** [review]
LGTM on the basis that patch for `wp_interactivity_data_wp_context ` will be applied post-sync

**Comment by youknowriad** [comment]
Commit https://core.trac.wordpress.org/changeset/57760

**Pull request closed without merging**
