### PR TITLE
General: Update document links.

### PR DESCRIPTION
**Pull request by mkismy**
Updated document urls that was moved under `https://developer.wordpress.org/advanced-administration/` to avoid unnecessary redirects.

Trac ticket: https://core.trac.wordpress.org/ticket/60732

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by huzaifaalmesbah** [comment]
Good catch. Thanks for the PR.  Looks good for me.

**Comment by lutzmex** [comment]
How can updating old URLs to new destinations in PHP files help improve web performance and user experience  [ ](https://techpreak.com/)?

**Comment by audrasjb** [comment]
Committed in several changesets, see ticket https://core.trac.wordpress.org/ticket/60732

**Comment by mkismy** [comment]
Thank you!

**Comment by lutzmex** [comment]
Thanks 

{{{ #!html
<a   href="slotasiabet3yes.com"></a>
<a   href="linkbegir.com"></a>
}}}

**Comment by lutzmex** [comment]
Thanks 

{{{ #!html
<a href="https://linkbegir.com"></a>
<a href="https://slotasiabet3yes.com"></a>
}}}

**Pull request closed without merging**
