### PR TITLE
Image: Add the lightbox setting to theme.json

### PR DESCRIPTION
**Pull request by michalczaplinski**
This is a backport PR for WordPress 6.4 that includes the following PHP Gutenberg changes:

- https://github.com/WordPress/gutenberg/pull/54509

Trac ticket: https://core.trac.wordpress.org/ticket/59393

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by tellthemachines — COMMENTED** [review]
Thanks for the PR! The changes from `lib/theme.json` in the linked Gutenberg PR should also be added to the[ core theme.json file](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/theme.json). 

This can't really be tested in core without the scripts that will only be available after the packages are updated, but the changes don't break anything so should be safe to commit beforehand.

**Comment by tellthemachines** [comment]
Added the theme.json change and rebased the branch to see if tests pass.

**Review by tellthemachines — COMMENTED** [review]
I think we're good to go with this! ✅

**Comment by tellthemachines** [comment]
Committed in [r56643](https://core.trac.wordpress.org/changeset/56643).

**Comment by michalczaplinski** [comment]
> Thanks for the PR! The changes from lib/theme.json in the linked Gutenberg PR should also be added to the[ core theme.json file](https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/theme.json).

Thanks for following up on this @tellthemachines and sorry I didn't get to it yesterday! 😊

**Pull request closed without merging**
