### PR TITLE
Backport 45275 from Gutenberg - Add type check to $user_cpt array()

### PR DESCRIPTION
**Pull request by cbravobernal**
Backporting https://github.com/WordPress/gutenberg/pull/45275

Just adding a type check to prevent warnings or fatal errors.

Trac ticket:  https://core.trac.wordpress.org/ticket/56467

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ockham** [comment]
To put this into context -- @scruffian has shared with Carlos and I that he encountered [this issue](https://github.com/WordPress/gutenberg/issues/45240) in the wild. It has so far however proven somewhat hard to reproduce ([see](https://github.com/WordPress/gutenberg/issues/45240#issuecomment-1290514460)).

Carrying over [my comment](https://github.com/WordPress/gutenberg/pull/45275#issuecomment-1290523254) on the GB PR:

> FWIW, I don't mind adding the `in_array` check, since it seems like it can't have any negative side effects.
>
> Ideally, I'd like to be able to reproduce the issue ([see](https://github.com/WordPress/gutenberg/issues/45240#issuecomment-1290514460)) and verify the fix.
>
> Finally, I'd like to understand which code path leads to `$user_cpt` being `null` here? Seems like [`get_user_data_from_wp_global_styles`](https://github.com/WordPress/gutenberg/pull/45275/files#diff-748c1f2130f44e5101c36487ae1878cc0c5bd8ab305150b18786ae82161c6e5eR82) would [fall back to an empty array](https://github.com/WordPress/gutenberg/blob/8d77ce9667621886ee33b984f950286e9f54217d/lib/compat/wordpress-6.0/class-wp-theme-json-resolver-6-0.php#L165-L221) pretty much always 🤔

**Review by ockham — APPROVED** [review]
Approving, based on [my comment here](https://github.com/WordPress/wordpress-develop/pull/3525#issuecomment-1290617210).

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍

**Comment by hellofromtonya** [comment]
I've removed my approval. why?

See the discussion in Slack https://wordpress.slack.com/archives/C02RQBWTW/p1666706883839909. The root cause is not yet known. While I lean into type checking to ensure the expected data type exists (which is why I initially approved it), without knowing the root cause, the type check could be masking a problem by skipping over the expected logic. A better approach would be:

- First, identify the root cause. If expected, then add the type check; else, resolve the issue where the root cause exists.
- If this should always be an `array`, then a data type check _with a notice_ (when not an array) can be considered. Why? To alert developers rather than quietly skipping the logic.

I think more information is needed before attempting to fix.

**Comment by Mamaduka** [comment]
I don't think there is a need for this PR. See https://github.com/WordPress/gutenberg/issues/45240#issuecomment-1304757932.

I'm going to remove it from WP 6.1.1 board.

**Pull request closed without merging**
