### PR TITLE
Add missing dimension attributes to Twenty Twenty-Two header image

### PR DESCRIPTION
**Pull request by felixarntz**
Trac ticket: https://core.trac.wordpress.org/ticket/59256

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by felixarntz** [comment]
@kt-12 I just realized you had already opened a somewhat similar PR in #4864. I think yours covers more images, but doesn't consider block validity, which is likely going to lead to errors in the block editor.

We can proceed with either PR, but let's make sure to align on one cohesive approach. Also please note the new dedicated ticket I opened for this in https://core.trac.wordpress.org/ticket/59256.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @felixarntz for the PR. The changes look good to me.

**Comment by mukeshpanchal27** [comment]
Hello @felixarntz,

I noticed that TT2 includes some additional patterns with images in the following locations:

1. /twentytwentytwo/inc/patterns/general-two-images-text.php
2. /twentytwentytwo/inc/patterns/general-wide-image-intro-buttons.php
3. /twentytwentytwo/inc/patterns/header-large-dark.php
4. /twentytwentytwo/inc/patterns/header-small-dark.php

The question is whether we need to add the "height" and "width" attributes to these images?

**Comment by kt-12** [comment]
@felixarntz If I am not wrong, by block validity you mean that json matches the attribute value, right?
We can go ahead an move other images to this PR, effort of finding the width and height can be reduced by using values from my old pr directly.

**Comment by spacedmonkey** [comment]
I don't think that block validation is going to be a problem. I say update all the other images.

**Review by spacedmonkey — CHANGES_REQUESTED** [review]
What about 

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/general-divider-dark.php#L10

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/general-divider-light.php#L10

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/general-image-with-caption.php#L10

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/page-about-media-left.php#L9

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/general-two-images-text.php#L11

https://github.com/WordPress/wordpress-develop/blob/44e71c8e703bb473924e0d2bd35999d3aa17e734/src/wp-content/themes/twentytwentytwo/inc/patterns/page-sidebar-poster.php#L26

Of the 22 `img` tags there are only 17 widths. Some dimensions have been missed.

**Comment by felixarntz** [comment]
@spacedmonkey I have now covered the two remaining instances. From your previous comment, some of them I had actually already implemented in this PR, and some of them are not using the `core/image` block. It's not as trivial to handle the dimensions for the other blocks, and `core/image` is most critical because of where it is used in the theme, so I think to not increase the scope too much we should only focus on all the `core/image` blocks here.

Please take another look.

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @felixarntz for covering the remaining images. LGTM!

**Review by spacedmonkey — APPROVED** [review]
Look good to commit to me.

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/56613

**Pull request closed without merging**
