### PR TITLE
Correction of function names in docblock

### PR DESCRIPTION
**Pull request by kebbet**
Trac ticket: https://core.trac.wordpress.org/ticket/55646

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by costdev — APPROVED** [review]
LGTM 👍

**Review by mukeshpanchal27 — APPROVED** [review]

**Comment by mukeshpanchal27** [comment]
@SergeyBiryukov Can you please check it as the changes make sense to merge?

**Comment by robinwpdeveloper** [comment]
LGTM 👍

**Review by robinwpdeveloper — APPROVED** [review]

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/54199

**Pull request closed without merging**
