### PR TITLE
Trac40822: nav-menus.php  - Group action to the left

### PR DESCRIPTION
**Pull request by kebbet**
General ticket: https://core.trac.wordpress.org/ticket/40822
Specific ticket: https://core.trac.wordpress.org/ticket/56594

## Before - Edit menu
bild

bild

## After - Edit menu
bild

bild

## Before - New menu
bild

## After - New menu
bild

### CODE REVIEW

**Comment by kebbet** [comment]
Visual result after build `rtl`-version of css.

bild

**Comment by sabernhardt** [comment]
I reopened [Trac 56594](https://core.trac.wordpress.org/ticket/56594) to address this on that ticket.

**Comment by kebbet** [comment]
Commited in https://core.trac.wordpress.org/changeset/56449

**Comment by kelvinjohnguru-source** [comment]
<picture>
  
  <source media="(min-width: 650px)" srcset="http://historiccourthouse.org/wp-content/uploads/2026/01/print9.jpg">
 </picture>

**Pull request closed without merging**
