### PR TITLE
Update the object-cache.php in phpunit fixture to support wp_cache_*_multiple

### PR DESCRIPTION
**Pull request by petitphp**
Add functions `wp_cache_get_multiple`, `wp_cache_add_multiple`, `wp_cache_set_multiple`, `wp_cache_delete_multiple`
in tests/phpunit/includes/object-cache.php

Trac ticket: https://core.trac.wordpress.org/ticket/54864

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by tillkruss** [comment]
@petitphp the memcached tests are failing.

**Comment by petitphp** [comment]
I'll take a look.

**Comment by petitphp** [comment]
@tillkruss I've updated the PR to fix failing tests.

**Comment by tillkruss** [comment]
> I've updated the PR to fix failing tests.

LGTM, let me see if @felixarntz or @SergeyBiryukov can merge this?

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Looks good to me.

It appears that the file was originally copied in [r40561](https://core.trac.wordpress.org/changeset/40561) / [#40619](https://core.trac.wordpress.org/ticket/40619) from [tollmanz/wordpress-pecl-memcached-object-cache](https://github.com/tollmanz/wordpress-pecl-memcached-object-cache), which is now maintained at [humanmade/wordpress-pecl-memcached-object-cache](https://github.com/humanmade/wordpress-pecl-memcached-object-cache) and has a note on the plugin status:
> Since this plugin was last updated, WordPress has introduced a variety of caching API improvements such as [wp_cache_get_multiple()](https://make.wordpress.org/core/2020/08/11/introduce-wp_cache_get_multiple/). This plugin has not been updated to take advantage of these new functions, because Human Made now uses Redis for our own caching backend. It should still work, but it will not be as efficient as it could be given the functionality in the latest versions of WordPress.

The file already has `wp_cache_get_multi()` and `wp_cache_set_multi()`, but the signatures don't exactly match the core functions:
```
function wp_cache_get_multi( $keys, $groups = '', &$cas_tokens = null, $flags = null )
function wp_cache_get_multiple( $keys, $group = '', $force = false )

function wp_cache_set_multi( $items, $groups = '', $expiration = 0 )
function wp_cache_set_multiple( array $data, $group = '', $expire = 0 )
```

So I think it makes sense to introduce the variants of these functions that WordPress core uses.

I've made a few minor adjustments for consistency:
* Placing the new functions directly after the related functions.
* Using camelCase for the method names to match other methods in the class.
* Renaming some parameters: `$data` to `$items` and `$expire` to `$expiration` to match other functions.

**Comment by SergeyBiryukov** [comment]
Merged in [r54423](https://core.trac.wordpress.org/changeset/54423).

**Pull request closed without merging**
