### PR TITLE
[Obsolete] Trac 58978: Suppress console errors from sessionStorage usage in sandboxed post embed iframe

### PR DESCRIPTION
**Pull request by westonruter**
This simply moves the try/catch blocks from inside the `if` statements that reference `sessionStorage` to instead wrap these `if` statements.

Trac ticket: https://core.trac.wordpress.org/ticket/58978

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by felixarntz — APPROVED** [review]
Good catch!

**Comment by westonruter** [comment]
Diff with whitespace suppressed: https://github.com/WordPress/wordpress-develop/pull/4965/files?diff=unified&w=1

image

**Comment by westonruter** [comment]
Humm. Somehow I pushed my branch this to `origin` by mistake when I meant to push it to my fork. (I'm surprised I was able to push to WordPress/wordpress-develop to begin with.) Going to create a separate PR because I suspect the branch will get blown away by the mirroring process.

**Comment by westonruter** [comment]
@felixarntz here's another updated version: https://github.com/WordPress/wordpress-develop/pull/4966

**Pull request closed without merging**
