### PR TITLE
Use wp_get_script_polyfill() for 2021 polyfills.

### PR DESCRIPTION
**Pull request by peterwilsoncc**
https://core.trac.wordpress.org/ticket/52098

### CODE REVIEW

**Review by aristath — APPROVED** [review]
I don't have IE to check if this actually works, but the logic is sound and the code looks OK :+1:

**Comment by carolinan** [comment]
When I test on IE11 I see the following before primary-navigation.js and responsive-embeds.js>
```
<script id='twenty-twenty-one-ie11-polyfills-js-after'>
( ( ! Element.prototype.matches ) || ( ! Element.prototype.closest ) || ( window.NodeList && ! NodeList.prototype.forEach ) ) || document.write( '<script src="http://localhost:8889/wp-content/themes/twentytwentyone/assets/js/polyfills.js?ver=1.0"></scr' + 'ipt>' );
</script>
```

But these JS errors are present

```
Object doesn't support property or method 'forEach'
responsive-embeds.js (18,2)

Object doesn't support property or method 'forEach'
primary-navigation.js (153,3)
```

**Comment by peterwilsoncc** [comment]
Thanks for the reviews folks,

`wp_get_script_polyfill()` uses `document.write()` in an attempt to force the polyfill scripts to load synchronously but IE11 still loads them asynchronously using that method. 

In 5a7c3a376c18d36b7abdb9d90d6466611a9454dd I tried a different approach but it ended up breaking gutenberg so I reverted it. If anyone is able to take a look at the commit, that would be dandy.

**Comment by peterwilsoncc** [comment]
@carolinan @aristath 

I figured it out what I was doing incorrectly. The test should be for the presence of the feature rather than the absence of the feature.

Fixed and ready for another look.

I've tested this in IE11 where the polyfill is loading, and Firefox where it is not.

**Comment by carolinan** [comment]
I have tested the update and it works well, thank you.

**Pull request closed without merging**
