### PR TITLE
Docs: correction of a typo in the comment block of wp_prepare_revisio…

### PR DESCRIPTION
**Pull request by dilipbheda**
Trac ticket: https://core.trac.wordpress.org/ticket/56981

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @dilipbheda LGTM.

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! This looks good.

I have added a minor update to use the correct format for [multi-line comments](https://developer.wordpress.org/coding-standards/inline-documentation-standards/php/#5-2-multi-line-comments) as per the documentation standards.

**Comment by dilipbheda** [comment]
Thank You @SergeyBiryukov :rocket:

**Comment by SergeyBiryukov** [comment]
Merged in [r54749](https://core.trac.wordpress.org/changeset/54749).

**Pull request closed without merging**
