### PR TITLE
Backport: Theme JSON Tests: Refactor base styles to a static variable

### PR DESCRIPTION
**Pull request by scruffian**
Backports https://github.com/WordPress/gutenberg/pull/58975 to core.

I haven't yet been able to run the tests to check it works.

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by tellthemachines — COMMENTED** [review]
I'm not sure there's much benefit to syncing this to core, because these tests really need a wider refactor. I proposed that in https://github.com/WordPress/gutenberg/issues/60842 (feedback welcome!) and intend to work on it in the next weeks.

The fact that this PR already has conflicts after a few days of being open illustrates the problem - every time we make updates to theme.json styles, these test strings also need to be updated, and the updates inevitably conflict 😬 

That said, I don't have anything _against_ this going into core, and am happy to help out with reviewing/committing once conflicts are solved! 

Edit: if we go forward with this it also needs a trac ticket.

**Comment by ellatrix** [comment]
Let's keep this for the end, when all the other backports touching these tests are in.

**Comment by tellthemachines** [comment]
Given #6734 removes base styles from all tests where they aren't relevant, is this change still needed?

**Comment by scruffian** [comment]
Yeah this isn't needed anymore

**Pull request closed without merging**
