### PR TITLE
Use correct default value for JavaScript translations path

### PR DESCRIPTION
**Pull request by ocean90**
Based on https://core.trac.wordpress.org/attachment/ticket/53635/53635-09-script-translations.patch.

Trac ticket: https://core.trac.wordpress.org/ticket/55967

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by swissspidy — APPROVED** [review]

**Comment by jrfnl** [comment]
@ocean90 Thanks for pointing out this ticket.

Please be aware that for PHP 8.1 (which "continues on error", so issues often go unnoticed), two calls to `expectDeprecation()` will need to be removed.

I'd also like to suggest adding tests to cover this change.

For both, see PR #3186. You could probably cherrypick the test changes from that PR (and then add some more tests yourself for the other affected functions 😇 )

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r54349](https://core.trac.wordpress.org/changeset/54349).

**Comment by jrfnl** [comment]
@SergeyBiryukov Is it just me or are some of the changes from this PR missing from the commit ?

**Comment by JJJ** [comment]
Agree with @jrfnl.

Only `i10n.php` made it to SVN; the others were omitted.

jjj-on-2022-09-28-at-13-59-17@2x

**Comment by SergeyBiryukov** [comment]
> Is it just me or are some of the changes from this PR missing from the commit ?

Ah yes, you're right. I went back and forth on whether to make two separate commits or combine them, chose the latter option, but then forgot to include these files. Will do a follow-up commit shortly. Thanks for flagging this!

**Comment by jrfnl** [comment]
Appreciated @SergeyBiryukov !

When the other changes from this PR will be committed, then the change from my PR to the [`src/wp-includes/l10n.php`](https://github.com/WordPress/wordpress-develop/pull/3186/files#diff-31cd15428a59baa3494149d7ccf047ce80c8d7783d6e889c80d118043548ee1a) file can be removed.

**Comment by SergeyBiryukov** [comment]
> When the other changes from this PR will be committed, then the change from my PR to the [`src/wp-includes/l10n.php`](https://github.com/WordPress/wordpress-develop/pull/3186/files#diff-31cd15428a59baa3494149d7ccf047ce80c8d7783d6e889c80d118043548ee1a) file can be removed.

I thought that's still a good change to include just in case a non-string `$path` is passed to the function, but happy to remove if that's preferred 🙂

**Comment by jrfnl** [comment]
> > When the other changes from this PR will be committed, then the change from my PR to the [`src/wp-includes/l10n.php`](https://github.com/WordPress/wordpress-develop/pull/3186/files#diff-31cd15428a59baa3494149d7ccf047ce80c8d7783d6e889c80d118043548ee1a) file can be removed.
> 
> I thought that's still a good change to include just in case a non-string `$path` is passed to the function, but happy to remove if that's preferred 🙂

The problem is that it would _hide_ an error which should be **_fixed_** (at the source of the problem) instead.

**Comment by SergeyBiryukov** [comment]
Merged the remaining changes in [r54351](https://core.trac.wordpress.org/changeset/54351). Thanks again!

**Comment by jrfnl** [comment]
Thanks for handling this @SergeyBiryukov !

**Pull request closed without merging**
