### PR TITLE
Test on updated 50523

### PR DESCRIPTION
**Pull request by joedolson**
Trac ticket: https://core.trac.wordpress.org/ticket/50523

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by joedolson** [comment]
Closed in https://core.trac.wordpress.org/changeset/55919

**Comment by leor347** [comment]
Resolution fixed deleted
Status changed from closed to reopened
Seems there is an unintentional code duplication 
{{{
#!html
<a href="https://magazinetttt8.weebly.com></a>
<a href="https://magazineyyyy8.weebly.com></a>
<a href="https://magazineuuuu8.weebly.com></a>
<a href="https://magazineiiii8.weebly.com></a>
<a href="https://magazineoooo8.weebly.com></a>
<a href="https://magazinepppp8.weebly.com></a>
<a href="https://magazinerrrr9.weebly.com></a>
<a href="https://magazinetttt9.weebly.com></a>
<a href="https://magazineyyyy9.weebly.com></a>
<a href="https://magazineuuuu9.weebly.com></a>
<a href="https://magazineiiii9.weebly.com></a>
<a href="https://magazineoooo9.weebly.com></a>
<a href="https://magazinepppp9.weebly.com></a>
<a href="https://magazinerrrr10.weebly.com></a>
<a href="https://magazinetttt10.weebly.com></a>
<a href="https://magazineyyyy10.weebly.com></a>
<a href="https://magazineuuuu10.weebly.com></a>
<a href="https://magazinepppp10.weebly.com></a>
<a href="https://magazineaaaa1.weebly.com></a>
<a href="https://magazineaaaa2.weebly.com></a>
<a href="https://magazineaaaa3.weebly.com></a>
<a href="https://magazineaaaa4.weebly.com></a>
<a href="https://magazineaaaa5.weebly.com></a>
<a href="https://magazineaaaa6.weebly.com></a>
<a href="https://magazineaaaa7.weebly.com></a>
<a href="https://magazineaaaa8.weebly.com></a>
<a href="https://magazineaaaa9.weebly.com></a>
<a href="https://magazineaaaa10.weebly.com></a>
<a href="https://magazinessss1.weebly.com></a>
<a href="https://magazinessss2.weebly.com></a>
<a href="https://magazinessss3.weebly.com></a>
<a href="https://magazinessss4.weebly.com></a>
<a href="https://magazinessss5.weebly.com></a>
<a href="https://magazinessss6.weebly.com></a>
<a href="https://magazinessss7.weebly.com></a>
<a href="https://magazinessss8.weebly.com></a>
<a href="https://magazinessss9.weebly.com></a>
<a href="https://magazinedddd1.weebly.com></a>
<a href="https://magazinedddd2.weebly.com></a>
<a href="https://magazinedddd3.weebly.com></a>
<a href="https://magazinedddd4.weebly.com></a>
<a href="https://magazinedddd5.weebly.com></a>
<a href="https://magazinedddd6.weebly.com></a>
<a href="https://magazinedddd7.weebly.com></a>
<a href="https://magazinedddd8.weebly.com></a>
<a href="https://magazineffff1.weebly.com></a>
<a href="https://magazineffff2.weebly.com></a>
<a href="https://magazineffff3.weebly.com></a>
<a href="https://magazineffff4.weebly.com></a>
<a href="https://magazineffff5.weebly.com></a>
<a href="https://magazinellll6.weebly.com></a>
<a href="https://magazinellll7.weebly.com></a>
<a href="https://magazinellll8.weebly.com></a>
<a href="https://magazinellll9.weebly.com></a>
<a href="https://magazinellll10.weebly.com></a>
}}}

**Comment by leor347** [comment]
Resolution fixed deleted
Status changed from closed to reopened
Seems there is an unintentional code duplication
{{{
#!html
<a href="https://magazinetttt8.weebly.com></a>
<a href="https://magazineyyyy8.weebly.com></a>
<a href="https://magazineuuuu8.weebly.com></a>
<a href="https://magazineiiii8.weebly.com></a>
<a href="https://magazineoooo8.weebly.com></a>
<a href="https://magazinepppp8.weebly.com></a>
<a href="https://magazinerrrr9.weebly.com></a>
<a href="https://magazinetttt9.weebly.com></a>
<a href="https://magazineyyyy9.weebly.com></a>
<a href="https://magazineuuuu9.weebly.com></a>
<a href="https://magazineiiii9.weebly.com></a>
<a href="https://magazineoooo9.weebly.com></a>
<a href="https://magazinepppp9.weebly.com></a>
<a href="https://magazinerrrr10.weebly.com></a>
<a href="https://magazinetttt10.weebly.com></a>
<a href="https://magazineyyyy10.weebly.com></a>
<a href="https://magazineuuuu10.weebly.com></a>
<a href="https://magazinepppp10.weebly.com></a>
<a href="https://magazineaaaa1.weebly.com></a>
<a href="https://magazineaaaa2.weebly.com></a>
<a href="https://magazineaaaa3.weebly.com></a>
<a href="https://magazineaaaa4.weebly.com></a>
<a href="https://magazineaaaa5.weebly.com></a>
<a href="https://magazineaaaa6.weebly.com></a>
<a href="https://magazineaaaa7.weebly.com></a>
<a href="https://magazineaaaa8.weebly.com></a>
<a href="https://magazineaaaa9.weebly.com></a>
<a href="https://magazineaaaa10.weebly.com></a>
<a href="https://magazinessss1.weebly.com></a>
<a href="https://magazinessss2.weebly.com></a>
<a href="https://magazinessss3.weebly.com></a>
<a href="https://magazinessss4.weebly.com></a>
<a href="https://magazinessss5.weebly.com></a>
<a href="https://magazinessss6.weebly.com></a>
<a href="https://magazinessss7.weebly.com></a>
<a href="https://magazinessss8.weebly.com></a>
<a href="https://magazinessss9.weebly.com></a>
<a href="https://magazinedddd1.weebly.com></a>
<a href="https://magazinedddd2.weebly.com></a>
<a href="https://magazinedddd3.weebly.com></a>
<a href="https://magazinedddd4.weebly.com></a>
<a href="https://magazinedddd5.weebly.com></a>
<a href="https://magazinedddd6.weebly.com></a>
<a href="https://magazinedddd7.weebly.com></a>
<a href="https://magazinedddd8.weebly.com></a>
<a href="https://magazineffff1.weebly.com></a>
<a href="https://magazineffff2.weebly.com></a>
<a href="https://magazineffff3.weebly.com></a>
<a href="https://magazineffff4.weebly.com></a>
<a href="https://magazineffff5.weebly.com></a>
<a href="https://magazinellll6.weebly.com></a>
<a href="https://magazinellll7.weebly.com></a>
<a href="https://magazinellll8.weebly.com></a>
<a href="https://magazinellll9.weebly.com></a>
<a href="https://magazinellll10.weebly.com></a>
}}}

**Comment by leor347** [comment]
Resolution fixed deleted
Status changed from closed to reopened
Seems there is an unintentional code duplication
{{{
#!html
<a href="https://magazinetttt8.weebly.com></a>
<a href="https://magazineyyyy8.weebly.com></a>
<a href="https://magazineuuuu8.weebly.com></a>
<a href="https://magazineiiii8.weebly.com></a>
<a href="https://magazineoooo8.weebly.com></a>
<a href="https://magazinepppp8.weebly.com></a>
<a href="https://magazinerrrr9.weebly.com></a>
<a href="https://magazinetttt9.weebly.com></a>
<a href="https://magazineyyyy9.weebly.com></a>
<a href="https://magazineuuuu9.weebly.com></a>
<a href="https://magazineiiii9.weebly.com></a>
<a href="https://magazineoooo9.weebly.com></a>
<a href="https://magazinepppp9.weebly.com></a>
<a href="https://magazinerrrr10.weebly.com></a>
<a href="https://magazinetttt10.weebly.com></a>
<a href="https://magazineyyyy10.weebly.com></a>
<a href="https://magazineuuuu10.weebly.com></a>
<a href="https://magazinepppp10.weebly.com></a>
<a href="https://magazineaaaa1.weebly.com></a>
<a href="https://magazineaaaa2.weebly.com></a>
<a href="https://magazineaaaa3.weebly.com></a>
<a href="https://magazineaaaa4.weebly.com></a>
<a href="https://magazineaaaa5.weebly.com></a>
<a href="https://magazineaaaa6.weebly.com></a>
<a href="https://magazineaaaa7.weebly.com></a>
<a href="https://magazineaaaa8.weebly.com></a>
<a href="https://magazineaaaa9.weebly.com></a>
<a href="https://magazineaaaa10.weebly.com></a>
<a href="https://magazinessss1.weebly.com></a>
<a href="https://magazinessss2.weebly.com></a>
<a href="https://magazinessss3.weebly.com></a>
<a href="https://magazinessss4.weebly.com></a>
<a href="https://magazinessss5.weebly.com></a>
<a href="https://magazinessss6.weebly.com></a>
<a href="https://magazinessss7.weebly.com></a>
<a href="https://magazinessss8.weebly.com></a>
<a href="https://magazinessss9.weebly.com></a>
}}}

**Comment by leor347** [comment]
Duotone buttons can be added to the image editor.
{{{
#!html
<a href="https://magazinetttt8.weebly.com"></a>
<a href="https://magazineyyyy8.weebly.com"></a>
<a href="https://magazineuuuu8.weebly.com"></a>
<a href="https://magazineiiii8.weebly.com"></a>
<a href="https://magazineoooo8.weebly.com"></a>
<a href="https://magazinepppp8.weebly.com"></a>
<a href="https://magazinerrrr9.weebly.com"></a>
<a href="https://magazinetttt9.weebly.com"></a>
<a href="https://magazineyyyy9.weebly.com"></a>
<a href="https://magazineuuuu9.weebly.com"></a>
<a href="https://magazineiiii9.weebly.com"></a>
<a href="https://magazineoooo9.weebly.com"></a>
<a href="https://magazinepppp9.weebly.com"></a>
<a href="https://magazinerrrr10.weebly.com"></a>
<a href="https://magazinetttt10.weebly.com"></a>
<a href="https://magazineyyyy10.weebly.com"></a>
<a href="https://magazineuuuu10.weebly.com"></a>
<a href="https://magazinepppp10.weebly.com"></a>
<a href="https://magazineaaaa1.weebly.com"></a>
<a href="https://magazineaaaa2.weebly.com"></a>
<a href="https://magazineaaaa3.weebly.com"></a>
<a href="https://magazineaaaa4.weebly.com"></a>
<a href="https://magazineaaaa5.weebly.com"></a>
<a href="https://magazineaaaa6.weebly.com"></a>
<a href="https://magazineaaaa7.weebly.com"></a>
<a href="https://magazineaaaa8.weebly.com"></a>
<a href="https://magazineaaaa9.weebly.com"></a>
<a href="https://magazineaaaa10.weebly.com"></a>
<a href="https://magazinessss1.weebly.com"></a>
<a href="https://magazinessss2.weebly.com"></a>
<a href="https://magazinessss3.weebly.com"></a>
<a href="https://magazinessss4.weebly.com"></a>
<a href="https://magazinessss5.weebly.com"></a>
<a href="https://magazinessss6.weebly.com"></a>
<a href="https://magazinessss7.weebly.com"></a>
<a href="https://magazinessss8.weebly.com"></a>
<a href="https://magazinessss9.weebly.com"></a>
<a href="https://magazinedddd1.weebly.com"></a>
<a href="https://magazinedddd2.weebly.com"></a>
<a href="https://magazinedddd3.weebly.com"></a>
<a href="https://magazinedddd4.weebly.com"></a>
<a href="https://magazinedddd5.weebly.com"></a>
<a href="https://magazinedddd6.weebly.com"></a>
<a href="https://magazinedddd7.weebly.com"></a>
<a href="https://magazinedddd8.weebly.com"></a>
<a href="https://magazineffff1.weebly.com"></a>
<a href="https://magazineffff2.weebly.com"></a>
<a href="https://magazineffff3.weebly.com"></a>
<a href="https://magazineffff4.weebly.com"></a>
<a href="https://magazineffff5.weebly.com"></a>
<a href="https://magazinellll6.weebly.com"></a>
<a href="https://magazinellll7.weebly.com"></a>
<a href="https://magazinellll8.weebly.com"></a>
<a href="https://magazinellll9.weebly.com"></a>
<a href="https://magazinellll10.weebly.com"></a>
}}}

**Comment by leor347** [comment]
Duotone buttons can be added to the image editor.
{{{
#!html
<a href="https://magazinetttt8.weebly.com"></a>
<a href="https://magazineyyyy8.weebly.com"></a>
<a href="https://magazineuuuu8.weebly.com"></a>
<a href="https://magazineiiii8.weebly.com"></a>
<a href="https://magazineoooo8.weebly.com"></a>
<a href="https://magazinepppp8.weebly.com"></a>
<a href="https://magazinerrrr9.weebly.com"></a>
<a href="https://magazinetttt9.weebly.com"></a>
<a href="https://magazineyyyy9.weebly.com"></a>
<a href="https://magazineuuuu9.weebly.com"></a>
<a href="https://magazineiiii9.weebly.com"></a>
<a href="https://magazineoooo9.weebly.com"></a>
<a href="https://magazinepppp9.weebly.com"></a>
<a href="https://magazinerrrr10.weebly.com"></a>
<a href="https://magazinetttt10.weebly.com"></a>
<a href="https://magazineyyyy10.weebly.com"></a>
<a href="https://magazineuuuu10.weebly.com"></a>
<a href="https://magazinepppp10.weebly.com"></a>
<a href="https://magazineaaaa1.weebly.com"></a>
<a href="https://magazineaaaa2.weebly.com"></a>
<a href="https://magazineaaaa3.weebly.com"></a>
<a href="https://magazineaaaa4.weebly.com"></a>
<a href="https://magazineaaaa5.weebly.com"></a>
<a href="https://magazineaaaa6.weebly.com"></a>
<a href="https://magazineaaaa7.weebly.com"></a>
<a href="https://magazineaaaa8.weebly.com"></a>
<a href="https://magazineaaaa9.weebly.com"></a>
<a href="https://magazineaaaa10.weebly.com"></a>
}}}

**Pull request closed without merging**
