### PR TITLE
Add post format search handler

### PR DESCRIPTION
**Pull request by TimothyBJacobs**
Trac ticket: https://core.trac.wordpress.org/ticket/51459

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
@noisysocks could you test this with Gutenberg active?

**Comment by noisysocks** [comment]
Looks good. I ran it with the latest Gutenberg `master` and tested that I could link to a post format using Twenty Sixteen.

Again, we should probably update the Gutenberg plugin to check if `WP_REST_Post_Format_Search_Handler` is already in the handlers array before adding it.

**Comment by noisysocks** [comment]
> Again, we should probably update the Gutenberg plugin to check if `WP_REST_Post_Format_Search_Handler` is already in the handlers array before adding it.

Actually, it doesn't matter, because `WP_REST_Post_Format_Search_Handler` is the class that's defined by Core and the array containing duplicates is transformed into a map:

https://github.com/WordPress/wordpress-develop/blob/98866f50321e9480b24760a8d384f81a2cf4aaec/src/wp-includes/rest-api/endpoints/class-wp-rest-search-controller.php#L80

So all good 👍 :shipit:

**Comment by TimothyBJacobs** [comment]
Merged in c39f290.

**Pull request closed without merging**
