### PR TITLE
Add test to the `aspect-ratio` CSS property in KSES

### PR DESCRIPTION
**Pull request by Rahmon**
This PR adds tests to the `aspect-ratio` CSS property in KSES since this property was added as safe for inline CSS.

Trac ticket: https://core.trac.wordpress.org/ticket/57664

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by mukeshpanchal27 — COMMENTED** [review]
Thanks @Rahmon for the unit test.

**Comment by mukeshpanchal27** [comment]
@desrosj can you please review this when you get moment?

**Review by desrosj — APPROVED** [review]
Thanks @Rahmon! These seem good to me!

I do find myself wishing that each property was tested a bit more thoroughly as the only property present as well as after being tested when combined with others. But that's probably just a nit and definitely outside of the scope here.

I'll leave a bit of time to see if anyone else has additional thoughts and commit in a day or two.

**Review by peterwilsoncc — APPROVED** [review]
@Rahmon Please excuse my presumption but I've pushed a few additional tests to your branch to include some unsafe/malformed properties to the tests.

While I was been presumptuous, I merged in trunk too.

I think this is good for commit once the test runs completes.

**Comment by peterwilsoncc** [comment]
Committed in [r55430](https://core.trac.wordpress.org/changeset/55430) / https://github.com/WordPress/wordpress-develop/commit/63b3c26f07eac4771f0c4d8e4477cb59d0bb7708

Thank you!

**Pull request closed without merging**
