### PR TITLE
Fix separator color issue

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Trac ticket: https://core.trac.wordpress.org/ticket/58558

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
@sabernhardt Could you please take a look

**Review by costdev — CHANGES_REQUESTED** [review]
Thanks for the PR @mukeshpanchal27!

The changes to `style-editor.scss` are good, but I believe you'll need to run `npm i && npm run build` in the theme's directory to generate the changes to `style-editor.css`. Without this, the changes have no effect in the editor and CI will fail when checking that there are no changes to version-controlled files.

**Review by costdev — APPROVED** [review]
Thanis for the update @mukeshpanchal27! Looks good to go now! :+1:

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/56036

**Pull request closed without merging**
