### PR TITLE
Auto-sizes: Align CSS rule with Google Chrome implementation

### PR DESCRIPTION
**Pull request by mukeshpanchal27**
Trac ticket: https://core.trac.wordpress.org/ticket/62515

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by mukeshpanchal27** [comment]
These PR update core CSS to align with Google Chrome implementation. In most issue the sites uses `height:auto` CSS rules so it will stretch to 1500px per CSS that implemented through PR #7813.

Per https://issues.chromium.org/issues/352077687#comment5, either we should pass the height & width for image or it will load 300X150 dimensions.

> This is working as intended based on the spec definition for sizes="auto"
> 
> The user agent stylesheet change is based on the rendering section of the html spec:
> https://html.spec.whatwg.org/#img-contain-size
> 
> The following note is present in the spec:
> "In addition, it is strongly encouraged to specify dimensions using the width and height attributes or with CSS. Without specified dimensions, the image will likely render with 300x150 dimensions because sizes="auto" implies contain-intrinsic-size: 300px 150px in the Rendering section."
> https://html.spec.whatwg.org/#sizes-attributes
> 
> Specifying the images dimensions should work around this problem.

**Review by felixarntz — CHANGES_REQUESTED** [review]
@mukeshpanchal27 This is not a proper fix, as it breaks the behavior again that this is fixing in the first place.

We must not use exactly what Google Chrome uses, because that's precisely what caused the other bug.

**Review by joemcgill — COMMENTED** [review]
Thanks @mukeshpanchal27, but the dimensions added here were intentionally made larger than the default UA stylesheet in Chrome in https://github.com/WordPress/wordpress-develop/pull/7813.

I'd suggest closing this PR.

**Comment by mukeshpanchal27** [comment]
> @mukeshpanchal27 This is not a proper fix, as it breaks the behavior again that this is fixing in the first place.
> 
> We must not use exactly what Google Chrome uses, because that's precisely what caused the other bug.

Thanks for review. As a side effect how we solve the `height` issue for image as chrome return `150px` and WP core return `1500px`?

**Comment by mukeshpanchal27** [comment]
Closing as it re-introduce original issue reported at https://core.trac.wordpress.org/ticket/62413

**Pull request closed without merging**
