### PR TITLE
Remove GUTENBERG_PHASE configuration

### PR DESCRIPTION
**Pull request by talldan**
Removes the GUTENBERG_PHASE configuration that was previously used to remove feature flagged gutenberg code. The way this works has changed in the Gutenberg codebase (see https://github.com/WordPress/gutenberg/pull/38202). The variable is now called `IS_GUTENBERG_PLUGIN` and is a boolean value.

It should be fine to remove this configuration as setting it to `false` would have the same result in it not being present, given `undefined` is also a falsey value.

Trac ticket: [55017](https://core.trac.wordpress.org/ticket/55017)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by talldan** [comment]
I'm not sure how to fix the Test NPM failure on CI, if anyone has advice that would be very much appreciated 😄

**Comment by walbo** [comment]
Running `npm run build:dev` should generate an updated `script-loader-packages.php` file.

**Comment by talldan** [comment]
Thanks, that's now updated 👍

**Comment by gziolo** [comment]
I didn’t notice this PR before. We replaced the old constant with the new one used in Gutenberg. See https://github.com/WordPress/wordpress-develop/commit/bab610091d59f6dd21c7db84ba3e1ca0bab6a211. Should we skip it altogether in WordPress core instead?

**Comment by talldan** [comment]
@gziolo I think it's fine either way. Easiest option is for me to close this PR now 😄 

Thanks for removing the old configuration. 🙇

**Pull request closed without merging**
