### PR TITLE
PHP Backport: Add excerpt support to the wp_block post type

### PR DESCRIPTION
**Pull request by carolinan**
Trac ticket:  https://core.trac.wordpress.org/ticket/61250

Add excerpt to the list of supports when registering the wp_block post type.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by krupal-panchal — APPROVED** [review]
LGTM!

**Comment by ntsekouras** [comment]
Thanks @carolinan! It seems the failures are valid since the excerpt is returned in the API response.

**Comment by carolinan** [comment]
> Thanks @carolinan! It seems the failures are valid since the excerpt is returned in the API response.

I don't know what that means, who can help fix it?

**Comment by ntsekouras** [comment]
>I don't know what that means, who can help fix it?

I'm not excerpt here, but I tried this:
1. In your branch start the dev environment `npm run env:start`
2. Run the php tests `npm run test:php`
3. Just by running the tests, my `tests/qunit/fixtures/wp-api-generated.js` file got updated with the `excerpt` info in `wp/v2/blocks` endpoint.

Can you try the above and then push the changes from the generated file? I believe this should be enough, but if this doesn't work, let's ping some more folks 😄

**Review by ntsekouras — APPROVED** [review]
✅ Thank you!

**Comment by SergeyBiryukov** [comment]
Thanks for the PR! Merged in [r58184](https://core.trac.wordpress.org/changeset/58184).

**Pull request closed without merging**
