### PR TITLE
Permalinks: Sanitize non-visible characters.

### PR DESCRIPTION
**Pull request by costdev**
- Remove `non-visible characters that display without a width`.
- Replace `non-visible characters that display with a width` with hyphen.

Fixes #47912.

Trac ticket: https://core.trac.wordpress.org/ticket/47912

### CODE REVIEW

**Review by hellofromtonya — CHANGES_REQUESTED** [review]
@costdev thank you for adding tests. This code review includes suggestions for improving the tests (i.e. to ensure all test scenarios run even if one fails) and additional happy and unhappy path coverage.

**Comment by costdev** [comment]
@hellofromtonya thanks! Am I correct that the suggestions have been tested and are ready for commiting to the PR?

**Comment by hellofromtonya** [comment]
Great question. @costdev Yes, they should be as I ran the tests and WPCS sniffer locally. Assuming copy/paste didn't mess up the formatting or I didn't fat fingered something, the suggestions should be ready for committing.

**Comment by costdev** [comment]
@hellofromtonya Great!

**Review by hellofromtonya — APPROVED** [review]
Good work @costdev!

**Comment by costdev** [comment]
> Good work @costdev!

Thanks @hellofromtonya, you too !

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/51984.

**Pull request closed without merging**
