### PR TITLE
Adding menus route

### PR DESCRIPTION
**Pull request by spacedmonkey**
Feature plugin - https://github.com/WP-API/menus-endpoints

Trac ticket: https://core.trac.wordpress.org/ticket/40878

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
We need to add `@ticket` annotations for the tests. 

I'm also going to hold off on committing this until the Gutenberg merge happens for 5.5.

**Comment by spacedmonkey** [comment]
> We need to add `@ticket` annotations for the tests.
> 
> I'm also going to hold off on committing this until the Gutenberg merge happens for 5.5.

Ticket number and version number comments added.

**Comment by ellatrix** [comment]
Is this for the navigation screen? If so, not sure if it should be merged now.

**Comment by TimothyBJacobs** [comment]
> Is this for the navigation screen? If so, not sure if it should be merged now.

Yes. I removed it from the milestone Saturday.

**Comment by spacedmonkey** [comment]
Closing in favour #1814

**Pull request closed without merging**
