### PR TITLE
Sync Gutenberg Packages for WordPress 6.5 Beta 3

### PR DESCRIPTION
**Pull request by getdave**
Sync Gutenberg to WP Core for WordPress 6.5 Beta 3. Based on [this PR](https://github.com/WordPress/gutenberg/pull/59394/) in the Gutenberg repo:

Trac ticket: https://core.trac.wordpress.org/ticket/60315

Props get_dave, youknowriad

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by getdave** [comment]
Noticing missing files. Investigating.

**Comment by getdave** [comment]
@swissspidy @dream-encode @youknowriad Gutenberg packages update for Beta 3.

**Comment by getdave** [comment]
I tested this both with and without the latest Gutenberg Plugin active and I noticed no errors.

I also verified a few of the bug fixes without the Gutenberg Plugin active to ensure the updates had been carried across.

**Comment by youknowriad** [comment]
Looking good to me as well.

**Comment by youknowriad** [comment]
Commit https://core.trac.wordpress.org/changeset/57721

**Pull request closed without merging**
