### PR TITLE
Upgrade/Install: Don't toggle maintenance mode for translation updates.

### PR DESCRIPTION
**Pull request by costdev**
Trac ticket: https://core.trac.wordpress.org/ticket/61260

### CODE REVIEW

**Comment by afragen** [comment]
If we caught all the turn on points for maintenance mode, then this looks like it should work to keep maintenance mode from being on during translations.

**Comment by Rajinsharwar** [comment]
This does look good, but I am curious if we really need the check while setting the maintenance mode to true. I mean, we should only check if the $type is '**translations**', and only set the maintenance mode to false if it is not. But while setting **maintenance_mode( true )**, do we need that check @costdev? (Correct me please if I am wrong 🙂)

**Comment by costdev** [comment]
@Rajinsharwar We need to skip translations for both.

When setting maintenance mode to `true`, this creates a `.maintenance` file that puts the site into maintenance mode. This should not be done for translation updates in these locations. This is specifically what causes the reported issue.

When setting maintenance mode to `false`, this attempts to delete a `.maintenance` file, which won't exist. While this isn't an issue in itself, it means that filesystem operations will be attempted unnecessarily, and the `::feedback()` method of the upgrader will also run unnecessarily. While this is not specifically what causes the reported issue, if we are skipping enabling maintenance mode for translation updates, for consistency and limiting attempted filesystem operations, we should skip disabling maintenance mode for translation updates as well.

**Comment by costdev** [comment]
Committed in [r58308](https://core.trac.wordpress.org/changeset/58308).

**Pull request closed without merging**
