### PR TITLE
Query by title in get_page_by_path()

### PR DESCRIPTION
**Pull request by dd32**
Trac ticket: https://core.trac.wordpress.org/ticket/56609

As a follow up to https://core.trac.wordpress.org/ticket/36905

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by dd32** [comment]
Looking at https://core.trac.wordpress.org/changeset/54234 it seems there's no tests that cover the new functionality when there exist multiple of the post_type, so the result was always the same.

A unit test that adds two pages, and ensures that the correct page object is returned would be of benefit here.

**Comment by peterwilsoncc** [comment]
As discussed via Slack, I'm pushing a bunch of commits to this PR to get started on this.

I'm starting with some tests so have reverted the fix to get them failing against the code base as is.

**Comment by peterwilsoncc** [comment]
> Looking at https://core.trac.wordpress.org/changeset/54234 it seems there's no tests that cover the new functionality when there exist multiple of the post_type, so the result was always the same.

I've added some shared fixtures to prepopulate the post table with various post types used within the tests.

> A unit test that adds two pages, and ensures that the correct page object is returned would be of benefit here.

`test_should_match_oldest_published_date_when_titles_match()` should serve this purpose. 

Stripped of the post statuses for convenience, the resulting queries after these changes are

```sql
SELECT   wptests_posts.*
FROM wptests_posts 
WHERE 1=1  AND wptests_posts.post_title = 'foo' AND wptests_posts.post_type = 'page'
ORDER BY wptests_posts.post_date ASC, wptests_posts.ID ASC
LIMIT 0, 1
```

**Comment by TimothyBJacobs** [comment]
Patch and tests look good to me. Discussed with @peterwilsoncc about the change to the `orderby` property. It is odd that it looks like the original `get_page_by_path` since the query doesn't seem to specify any ordering. However it looks like these new tests pass on 6.0, so we should be good to go.

**Comment by peterwilsoncc** [comment]
> However it looks like these new tests pass on 6.0, so we should be good to go.

To document how I tested:

* removed the caching checks in the tests
* replaced the `get_page_by_title()` with the 6.0 version
* removed cache based assertions from tests.
* `phpunit --group 36905` ✅ 
* Swapped the order of insertion of old page in `test_should_match_oldest_published_date_when_titles_match()`
* `phpunit --group 36905` ✅  (still with 6.0 version of function)

**Comment by peterwilsoncc** [comment]
Committed in https://core.trac.wordpress.org/changeset/54271 / 6c6a6747a02d7f196cfc2f8dbe64181caccbee93

**Pull request closed without merging**
