### PR TITLE
Remove `wp_footer` call in legacy widget preview.

### PR DESCRIPTION
**Pull request by costdev**
~~`handle_legacy_widget_preview_iframe()` called `wp_footer()` on each widget on the Appearance > Widgets screen.
This patch removes the call to `wp_footer()`.~~

**PR Update**
Following discussion on Trac, a CSS solution is simpler and suggests equal results. The updates to this PR remove the initial changes and implement a CSS based solution instead.

Discussion on Trac included feedback from the accessibility team who have no specific concerns at this moment. Some keyboard only navigation and screen reader testing of the legacy widget preview screen is desirable.

Trac ticket: https://core.trac.wordpress.org/ticket/53801

### CODE REVIEW

**Comment by draganescu** [comment]
How about if we hide what these hooks output here in a display none div?

**Comment by costdev** [comment]
While this could work for `wp_footer()`, it would return invalid markup for `wp_head()`. 

As the docs specifically state that both functions are intended for output to the _frontend_, we would ideally not call these functions in the widget editor.

However, to reduce BC breaks, we can output enqueued scripts and styles to ensure that the widgets' functionality and styling is maintained in the widget editor.

Thoughts?

**Comment by hellofromtonya** [comment]
The e2e tests are failing on the `Ensure version-controlled files are not modified or deleted` job. Isn't the file being modified part of the published `@wordpress/widgets` package? If yes, should it be [modified in Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/packages/widgets/src/blocks/legacy-widget/index.php)? cc @costdev @draganescu

**Comment by costdev** [comment]
> The e2e tests are failing on the `Ensure version-controlled files are not modified or deleted` job. Isn't the file being modified part of the published `@wordpress/widgets` package? If yes, should it be [modified in Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/packages/widgets/src/blocks/legacy-widget/index.php)? cc @costdev @draganescu 

That's right, it will need a change upstream. Noted [here](https://core.trac.wordpress.org/ticket/53801#comment:40) and at the bottom of [this comment](https://github.com/WordPress/gutenberg/issues/33580#issuecomment-930758395).

I'm not 100% sure if it will require the changes in both repos or if the change upstream will be enough and the build process will update the `legacy-widget.php` file in Core. I _think_ an upstream change will be enough.

**Comment by hellofromtonya** [comment]
Closing this PR as the fix needs to be done in Gutenberg, the package published, and then brought over to Core via a `@wordpress` package update.

Here's the GB [issue](https://github.com/WordPress/gutenberg/issues/33580) and [PR](https://github.com/WordPress/gutenberg/pull/36759) that will resolve the issue.

**Pull request closed without merging**
