### PR TITLE
Script Modules: Do not print importmap polyfill

### PR DESCRIPTION
**Pull request by swissspidy**
Trac ticket: https://core.trac.wordpress.org/ticket/60970

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by desrosj** [comment]
@swissspidy Is there any reason not to remove the other changes in the related commit? It looks like the `wp-polyfill-importmap` handle is not being used anywhere, and the `es-module-shims` dependency where `wp-polyfill-importmap` is built from also appears not to be used.

**Comment by swissspidy** [comment]
Historically we haven't removed old polyfills even though they are no longer used. There's still a bunch of them registered here:

https://github.com/WordPress/wordpress-develop/blob/324aeb7485b800aef96d4c68b9f1ca36dbca1b7c/src/wp-includes/script-loader.php#L90-L126

If we look at them holistically I wouldn't mind cleaning up a little and replace the scripts with blanks or something.

This way we could tidy up `package.json` and our build script a bit as well.

Or are you suggesting only removing this one completely, because it's so new and probably completely unused? And leave the rest as-is?

**Comment by desrosj** [comment]
> Or are you suggesting only removing this one completely, because it's so new and probably completely unused? And leave the rest as-is?

Correct. There's only [5 occurrences of this script handle in the plugin directory](https://wpdirectory.net/search/01J6CPFGG78CHW8AQ9AT3AGGQK), 2 of which are Gutenberg itself. I'd love to not have another obscure polyfill to update every four-ish months.

I'd be open to reviewing this policy more holistically. But should probably do that separately.

**Comment by swissspidy** [comment]
And one of them is from a broken translation file that contains a 404 page's HTML markup 😅 

Just pushed these changes now

**Review by desrosj — APPROVED** [review]

**Comment by swissspidy** [comment]
Committed in https://core.trac.wordpress.org/changeset/58952

**Pull request closed without merging**
