### PR TITLE
Update dev container config - Dev container fixes

### PR DESCRIPTION
**Pull request by samruddhikhandale**
Following up from https://github.com/WordPress/wordpress-develop/pull/4031

Updates dev container config for local development with Dev Containers.

### CODE REVIEW

**Comment by devfle** [comment]
Hi, first of all really cool that you made Wordpress compatible with GitHub CodeSpaces! I also tested it outside of this repository and it works in my repository too. I could see a small issue both here and on my machine, where this step seems to be executed too early:
https://github.com/WordPress/wordpress-develop/blob/trunk/.devcontainer/setup.sh#L18

Wordpress can't be installed via the CLI on my system because some files are still missing. If I build in a "sleep" it works. Otherwise I have to run the CLI command manually.

**Comment by samruddhikhandale** [comment]
> Wordpress can't be installed via the CLI on my system because some files are still missing. If I build in a "sleep" it works. Otherwise I have to run the CLI command manually.

Interesting, I have tested this in a Codespace and locally on my machine, however, this issue never reproduced for me. 

@devfle Can you try switching the `postCreateCommand` [in here](https://github.com/WordPress/wordpress-develop/blob/trunk/.devcontainer/devcontainer.json#L20) to `postStartCommand` and see if it helps?

**Comment by devfle** [comment]
> > Wordpress can't be installed via the CLI on my system because some files are still missing. If I build in a "sleep" it works. Otherwise I have to run the CLI command manually.
> 
> Interesting, I have tested this in a Codespace and locally on my machine, however, this issue never reproduced for me.
> 
> @devfle Can you try switching the `postCreateCommand` [in here](https://github.com/WordPress/wordpress-develop/blob/trunk/.devcontainer/devcontainer.json#L20) to `postStartCommand` and see if it helps?

changed it and removed the sleep and still getting the following wp cli Error: "This does not seem to be a WordPress installation." Because some WP Files are missing.

**Comment by helen** [comment]
Just gave this a go both in Codespaces and locally and it works beautifully! Going to commit so folks have it for WordCamp Asia's contributor day this weekend :)

@devfle Might help if you're able to share more of the creation log, I'm not getting that either so it's a bit hard to figure out which direction to go without more information since we're not able to reproduce yet.

**Comment by helen** [comment]
Committed in https://core.trac.wordpress.org/changeset/55353 / https://github.com/WordPress/wordpress-develop/commit/5a87725ed976b2c436bfd61364c09d7df5f810ea

**Pull request closed without merging**
