### PR TITLE
Bundled Themes: Bump themes versions for WP 6.2

### PR DESCRIPTION
**Pull request by sanketio**
Trac ticket: https://core.trac.wordpress.org/ticket/57689

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by audrasjb** [comment]
Thanks for the PR @sanketio. However, we need to add a changelog item for each version and to update enqueue versions as well.
See [this changeset for 6.2](https://github.com/robinwpdeveloper/wordpress-develop/commit/73b179ab9938113b78d4a30df6d16f5c33f2de88#diff-79b7cc722afffe31d203b10712e25bf27ea591e935a0a7fcdf2981502661250b) for reference.

**Review by audrasjb — CHANGES_REQUESTED** [review]
We need to add a readme changelog item for each theme and to update enqueue versions as well.

**Comment by sanketio** [comment]
Thank you, @audrasjb!

I will update the readme files.

**Comment by sanketio** [comment]
Hi, @audrasjb,

I have updated the theme versions and the asset versions.

**Comment by mukeshpanchal27** [comment]
The ticket already closed in 6.2

**Pull request closed without merging**
