### PR TITLE
Update @wordpress npm packages

### PR DESCRIPTION
**Pull request by noisysocks**
Update WordPress packages ahead of WP 5.7. This is everything that is included in Gutenberg 9.8.

To do:

- [x] Unsure about whether to port i18n change in `client-assets.php`. Have asked in https://github.com/WordPress/gutenberg/pull/28279.
- [x] Need https://github.com/constancecchen/object-fit-polyfill to publish `src` to npm so that we can vendor it.
- [x] Re-check the `client-assets.php` diff for changes I may have missed.
- [x]  Run Gutenberg E2E tests against this branch.
  - [x] Fix failing `reusable-blocks.test.js` test.
  - [x] Fix failing `font-size-picker.test.js` test.

https://core.trac.wordpress.org/ticket/52334

### CODE REVIEW

**Comment by noisysocks** [comment]
>  Need https://github.com/constancecchen/object-fit-polyfill to publish src to npm so that we can vendor it.

Spoke to @ajlende about this. He's going to open a PR which adds `src` to the npm package.

**Comment by noisysocks** [comment]
> Fix failing font-size-picker.test.js test.

This is the only remaining failure I get when I run Gutenberg E2E tests against this branch:

```
  ● Font Size Picker › should apply a custom font size using the font size input

    expect(received).toMatchSnapshot()

    Snapshot name: `Font Size Picker should apply a custom font size using the font size input 1`

    - Snapshot  - 1
    + Received  + 1

    - <!-- wp:paragraph {"style":{"typography":{"fontSize":"23px"}}} -->
    + <!-- wp:paragraph {"style":{"typography":{"fontSize":23}}} -->
      <p style="font-size:23px">Paragraph to be made "small"</p>
      <!-- /wp:paragraph -->

      76 | 		// Ensure content matches snapshot.
      77 | 		const content = await getEditedPostContent();
    > 78 | 		expect( content ).toMatchSnapshot();
         | 		                  ^
      79 | 	} );
      80 | 
      81 | 	it( 'should reset a named font size using the reset button', async () => {

      at Object.<anonymous> (specs/editor/various/font-size-picker.test.js:78:21)
          at runMicrotasks (<anonymous>)
```

This seemingly relates to https://github.com/WordPress/gutenberg/pull/27083. I'm having a hard time figuring out if `px` should be appended in Core or if that's a FSE-related change that should remain in the plugin only. Do you know, @jorgefilipecosta ? If it should be changed in Core, where should that change happen?

**Comment by noisysocks** [comment]
> > Need https://github.com/constancecchen/object-fit-polyfill to publish src to npm so that we can vendor it.
> 
> Spoke to @ajlende about this. He's going to open a PR which adds `src` to the npm package.

https://github.com/constancecchen/object-fit-polyfill/pull/59

**Comment by noisysocks** [comment]
> Unsure about whether to port i18n change in client-assets.php. Have asked in WordPress/gutenberg#28279.

Preference is to land Core-46089 as a proper fix for this. Will land the workaround that Gutenberg has if that can't be done for 5.7.

**Comment by noisysocks** [comment]
> > Fix failing font-size-picker.test.js test.
> ...
> This seemingly relates to [WordPress/gutenberg#27083](https://github.com/WordPress/gutenberg/pull/27083). I'm having a hard time figuring out if `px` should be appended in Core or if that's a FSE-related change that should remain in the plugin only. Do you know, @jorgefilipecosta ? If it should be changed in Core, where should that change happen?

It looks like in the plugin it sets the attribute to `23px` because there is a `px` in `editorSettings.__experimentalFeatures.global.typography.fontSizes`. In my mind it makes sense to leave this as is (no `px`) because we do not want `__experimentalFeatures` to be added to Core.

**Review by tellthemachines — COMMENTED** [review]
Tested locally; changes build correctly and everything seems working fine. Only one small issue in the editor: typing `/freeform` doesn't bring up the Classic block as expected (this works in Gutenberg 9.8)

**Comment by noisysocks** [comment]
> Only one small issue in the editor: typing /freeform doesn't bring up the Classic block as expected (this works in Gutenberg 9.8)

Hmm... this seems okay to me?

**Pull request closed without merging**
