### PR TITLE
Load `theme-preview.php` after pluggable functions get defined

### LINKED ISSUE #53284: Block Theme Previews does not work if we call the `get_template` or `get_stylesheet` functions early
### Description

Block Theme Previews does not work if we call the `get_template` or `get_stylesheet` functions before the pluggable functions are not ready. So, if a 3rd party plugin (e.g. CoBlocks, Elementor, Classic Editor, and WooCommerce) needs to access the template or stylesheet before the pluggable functions are ready, then the site with such a plugin will break (see the reproduction instruction below).

The reason this error happens is;

- Block Theme Previews adds hooks to `stylesheet` and `template`. https://github.com/WordPress/wordpress-develop/blob/4417367/src/wp-includes/theme-previews.php#L80-L81
- It checks `current_user_can( 'switch_themes' )`, which uses `wp_get_current_user` inside of it. https://github.com/WordPress/wordpress-develop/blob/4417367/src/wp-includes/theme-previews.php#L17-L19
- `wp_get_current_user` is initialized after `pluggable.php` is called. https://github.com/WordPress/wordpress-develop/blob/1d7554d/src/wp-settings.php#L482-L484

A possible solution would be one of the following;

- Load the [pluggable functions](https://github.com/WordPress/wordpress-develop/blob/1d7554d/src/wp-settings.php#L482-L484) early
- Load [`theme-previews.php`](https://github.com/WordPress/wordpress-develop/blob/1d7554d/src/wp-settings.php#L184) after the pluggable functions
- Load the pluggable functions on demand in `theme-previews.php`
- Tell developers for the 3rd party plugins not to access the template or stylesheet directly when loading plugins (a developer guide should be covered, maybe)
- Something else

### Step-by-step reproduction instructions

1. Add a file in `wp-content/plugins/sample-plugin/sample-plugin.php` on your site.

```php
<?php
/*
Plugin Name: Sample plugin
*/

$wp_theme = wp_get_theme();
$wp_theme->get_stylesheet();
```

2. Go to `/wp-admin/themes.php` and click `Live Preview` button on your installed **Block theme**. 
3. See the error: `Uncaught Error: Call to undefined function wp_get_current_user()`

### Screenshots, screen recording, code snippet

Screen Shot 2023-08-03 at 16 25 19

### Environment info

- WordPress: 6.3-RC3-56344
- Gutenberg: 16.3.0

### Please confirm that you have searched existing issues in the repo.

Yes

### Please confirm that you have tested with all plugins deactivated except Gutenberg.

Yes

### PR DESCRIPTION
**Pull request by okmttdhr**
This PR fixes https://github.com/WordPress/gutenberg/issues/53284. https://github.com/WordPress/wordpress-develop/pull/4959 tried to fix the same issue, but there is a concern about its reliability, depending on timing. 

Hence, this PR changed to load `theme-previews.php`, which is the cause of this issue, after the pluggable functions. The reason for this is that running capability checks before defining pluggable functions itself does not seem to be a good approach. 

Fixes https://github.com/WordPress/gutenberg/issues/53284
Trac ticket: https://core.trac.wordpress.org/ticket/59000 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by okmttdhr** [comment]
Hello, @SergeyBiryukov @johnbillion!
I've made the changes as described in the PR to make the block theme previews work on every site. I'd appreciate it if you take a look!

Both failing tests ([E2E](https://github.com/WordPress/wordpress-develop/actions/runs/5899516959/job/16002154583?pr=5028), [performance](https://github.com/WordPress/wordpress-develop/actions/runs/5899516986/job/16002151576?pr=5028)) are passing on my local, at least. 
Screen Shot 2023-08-18 at 16 35 34
Screen Shot 2023-08-18 at 16 35 42

**Comment by scruffian** [comment]
This makes perfect sense to me, thanks for working on it.

**Comment by okmttdhr** [comment]
Hello, @azaozz @mtias @noisysocks! 
To fix the crash of Block Theme Previews, I'd appreciate it if you could review and commit this change to the core. Thank you in advance!

**Comment by okmttdhr** [comment]
> Hello, @azaozz @mtias @noisysocks! To fix the crash of Block Theme Previews, I'd appreciate it if you could review and commit this change to the core. Thank you in advance!

I'm closing this PR in favor of a new one: https://github.com/WordPress/wordpress-develop/pull/5107.

**Pull request closed without merging**
