### PR TITLE
use 'esc_url' for 'get_permalink'

### PR DESCRIPTION
**Pull request by hz-tyfoon**
Trac ticket: [56667](https://core.trac.wordpress.org/ticket/56667)

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by robinwpdeveloper — APPROVED** [review]
LGTM 👍

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @hz-tyfoon. LGTM.

**Comment by fuadragib01** [comment]
Ok, LGTM. Thank you @hz-tyfoon

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/54341

**Pull request closed without merging**
