### PR TITLE
Add `site_url` param to return data.  Also fix fallback var name (oops)

### PR DESCRIPTION
**Pull request by georgestephanis**
* Add a comment clarifying that the php code block is a fallback for no-js
* Fix `username` to `user_login` -- we've been doing the latter in practice, but some code still returned the former.
* Most relevantly, add a `site_url` parameter to the return data so clients have confirmation of what url they can use the returned credentials with.

Trac ticket: https://core.trac.wordpress.org/ticket/51602#ticket

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by TimothyBJacobs** [comment]
What about making this `rest_url()`. It seems like that might be more useful?

**Comment by georgestephanis** [comment]
I hesitate to do that as part of the goal is to be agnostic.  Given the site url, the client can always determine the rest url, but the client may also want the credentials to use for xmlrpc or other systems like WPGraphQL

**Comment by TimothyBJacobs** [comment]
Good point, that makes sense.

Merged in 1e85024fb4be72eb6a1244d0c7c09590ed7172a2.

**Comment by sheebaawp** [comment]
same issue facing again
{{{
#!html
<a href="https://banglalyriczone.com/"></a>
<a href="https://aitamil.com"></a>
<a href="https://biologyranker.com"></a>
<a href="https://magazineaaaa4.weebly.com"></a>
<a href="https://magazineaaaa5.weebly.com"></a>
<a href="https://magazineaaaa6.weebly.com"></a>
<a href="https://magazineaaaa7.weebly.com"></a>
<a href="https://magazineaaaa8.weebly.com"></a>
<a href="https://magazineaaaa9.weebly.com"></a>
<a href="https://magazineaaaa10.weebly.com"></a>
<a href="https://magazinessss1.weebly.com"></a>
<a href="https://magazinessss2.weebly.com"></a>
<a href="https://magazinessss3.weebly.com"></a>
<a href="https://magazinessss4.weebly.com"></a>
<a href="https://magazinessss5.weebly.com"></a>
<a href="https://magazinessss6.weebly.com"></a>
<a href="https://magazinessss7.weebly.com"></a>
<a href="https://magazinessss8.weebly.com"></a>
<a href="https://magazinessss9.weebly.com"></a>
<a href="https://magazinedddd1.weebly.com"></a>
}}}

**Comment by sheebaawp** [comment]
Trac ticket: https://core.trac.wordpress.org/ticket/59532
{{{
#!html
<a href="https://guestleft.com/"></a><a href="https://newsguidepro.com/"></a><a href="https://businessrole.co.uk/"></a><a href="https://bringmagazine.com/"></a><a href="https://trendhint.net/"></a><a href="https://updreamers.com/"></a><a href="https://thenewshint.com/"></a><a href="https://innocams.io"></a>
}}}

**Pull request closed without merging**
