### PR TITLE
Docs: Improve wp_get_object_terms() return type.

### PR DESCRIPTION
**Pull request by audrasjb**
Trac ticket: https://core.trac.wordpress.org/ticket/56327

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by dd32** [comment]
Per ticket, this should also touch the filter value for the `get_object_terms` and `wp_get_object_terms` filters

**Comment by audrasjb** [comment]
@dd32 PR updated. Does it works for you?

**Review by dd32 — APPROVED** [review]
These changes appear to match my expectation of the values here! 👍

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @audrasjb LGTM.

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/54441

**Pull request closed without merging**
