### PR TITLE
trac-57281: update phpmailer to 6.7.1

### PR DESCRIPTION
**Pull request by kapilpaul**
https://core.trac.wordpress.org/ticket/57281

### CODE REVIEW

**Review by mukeshpanchal27 — APPROVED** [review]
Thanks @kapilpaul, As per the note https://core.trac.wordpress.org/ticket/57281#comment:2 the changes look good to me.

**Comment by mukeshpanchal27** [comment]
@jrfnl Can you please review it when you get time? Do we needs to open new ticket or can we commit in same ticket?

**Review by jrfnl — CHANGES_REQUESTED** [review]
Seriously ?

As I said before:
> FYI: PHPMailer 6.7.1 has just been released, but aside from the version number it does not contain any changes to the files included in WP, so AFAIC **no update is needed**.

**Comment by jrfnl** [comment]
Closing as superseded by Trac https://core.trac.wordpress.org/ticket/57874

**Pull request closed without merging**
