### PR TITLE
Test old branches on a schedule

### PR DESCRIPTION
**Pull request by desrosj**
Trac ticket: https://core.trac.wordpress.org/ticket/52653.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by desrosj** [comment]
Besides the personal access token I would need to configure, I think this is in a good spot. But, I'm not sure how we'd be able to test it without adding the `workflow_dispatch` trigger to an older branch. Then we could change this new workflow to run on `pull_request_target`, and see if it is triggered successfully. Otherwise I don't think this will run.

**Comment by desrosj** [comment]
I've gotten this working by using the `actions/github-script` action and the `workflow_dispatch` event.

Here's how I've tested:
- Created a branch off of `5.5` called `5.5-test`.
- Added the `workflow_dispatch` event to each workflow in that test branch.
- Added the `pull_request` trigger event to the new, `test-old-branches.yml` file.
- [Opened a PR for my fork](https://github.com/desrosj/wordpress-develop/pull/21) to merge this [branch and trigger the workflow with a paired down list of versions](https://github.com/desrosj/wordpress-develop/actions/runs/618644090).
- Observed [manual runs dispatched for the `5.5-test` branch for each workflow](https://github.com/desrosj/wordpress-develop/actions?query=branch%3A5.5-test).
- Polished the[ workflow and pushed again to confirm all branches receive jobs for their appropriate workflows](https://github.com/desrosj/wordpress-develop/actions/runs/622361357).

One downfall of manually dispatching workflows is that the branch does not display to the right of the workflow like `push`  or `pull_request` events. But, they do show when filtering by branch, and after clicking into a workflow, you can click the SHA value to see the commit the workflow was triggered for (it will always be the most recent commit within the branch). This is a GHA limitation, though. I was unable to find any way to change the workflow name, or display more information on the run.

Previously on TravisCI, the older branches ran monthly and more recent ones weekly. This runs them all weekly. There was also a setting to only run scheduled builds if there had not been one run in the previous 24 hours for a branch. That has also not been copied over.

**Comment by johnbillion** [comment]
Is there a need for the current branch (currently 5.7) to be included in this matrix?

**Comment by desrosj** [comment]
The schedule event trigger will only work in the primary branch. If 5.7 is not included, it would only be tested if a commit is made.

**Comment by desrosj** [comment]
Merged into Core in https://core.trac.wordpress.org/changeset/50590.

**Pull request closed without merging**
