### PR TITLE
Disable post meta/term cache updating for wp_global_styles

### PR DESCRIPTION
**Pull request by ocean90**
Neither post metas nor terms are used so this can be disabled to reduce the queries by one.

Trac ticket: 

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by spacedmonkey** [comment]
@ocean90 Can you confirm that this does remove queries. 

Post meta is loaded. As this post is converted to an array, that loads post meta. 
Screenshot 2022-11-21 at 14 32 25

**Comment by ocean90** [comment]
@spacedmonkey I haven't verified it on a clean install but I got one less term query on a client site. Will check again later, this was just for verifying if there are failing tests.

Though, it makes no sense to convert the post to an array. 😞 Only `post_content` and `ID` fields are actually used.

**Comment by spacedmonkey** [comment]
> Though, it makes no sense to convert the post to an array. 😞 Only post_content and ID fields are actually used.

I agree. How about manually converting this to an array. So 

```
$user_cpt = array(
  'ID' => $post->ID, 
  'post_content' => $post->post_content,
);
```

This is a private method, so it is a little easier to change.

**Comment by spacedmonkey** [comment]
@ocean90 This code is from gutenberg, it might be better to do this work in the gutenberg repo and it will be backported.

**Comment by ocean90** [comment]
> @ocean90 This code is from gutenberg, it might be better to do this work in the gutenberg repo and it will be backported.

Thanks, created https://github.com/WordPress/gutenberg/issues/45978 as a starting point.

**Comment by spacedmonkey** [comment]
I have my own PR here - https://github.com/WordPress/gutenberg/pull/46043

**Pull request closed without merging**
