### PR TITLE
Fix: make `Patterns` in admin menu translatable.

### PR DESCRIPTION
**Pull request by kebbet**
https://core.trac.wordpress.org/ticket/60825

### CODE REVIEW

**Comment by swissspidy** [comment]
We should just use `_x( 'Patterns', 'site editor menu item' )` instead of `__( 'Patterns', 'site editor menu item' )`

No translator comment or anything

**Comment by kebbet** [comment]
Doing some research on swedish translations, I think no comment at all should be best, as `_x` will genereate a new string.

https://translate.wordpress.org/projects/wp/dev/sv/default/?filters%5Bterm%5D=Patterns&filters%5Bcase_sensitive%5D=yes&filters%5Bterm_scope%5D=scope_any&filters%5Bstatus%5D=current_or_waiting_or_fuzzy_or_untranslated&filters%5Buser_login%5D=&filter=Apply+Filters&sort%5Bby%5D=references&sort%5Bhow%5D=desc

**Comment by swissspidy** [comment]
That is correct. See the discussion on the ticket about that. We have a couple of options here.

**Review by audrasjb — APPROVED** [review]

**Comment by audrasjb** [comment]
Using `__( 'Patterns' )` looks like our best option there.
Approving this for `commit`.

**Comment by swissspidy** [comment]
https://core.trac.wordpress.org/changeset/57864

**Pull request closed without merging**
