### PR TITLE
Update @wordpress packages

### PR DESCRIPTION
**Pull request by noisysocks**
Update packages to include these bug fixes from Gutenberg:

- https://github.com/WordPress/gutenberg/pull/36887
- https://github.com/WordPress/gutenberg/pull/38093
- https://github.com/WordPress/gutenberg/pull/38123
- https://github.com/WordPress/gutenberg/pull/38168

Trac ticket: https://core.trac.wordpress.org/ticket/54487

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Review by talldan — APPROVED** [review]
Looks good 👍 

When testing I noticed there's still a bug related to https://github.com/WordPress/gutenberg/pull/38093. If the browser viewport is small / medium sized (phone or tablet), the Edit Styles link doesn't work  as expected. It looks like the sidebar does open, but is closed straight away by some responsive cleverness, and the Styles Welcome Guide only flickers briefly on screen. I'll make a Gutenberg issue for this.

This PR is technically still good though, just a call needs to be made by release leads on the above about whether to backport an additional fix.

**Comment by noisysocks** [comment]
Thank you @talldan! Create an issue and I'll note it as "good to fix in RC 4 if we can, but not a blocker" along with https://github.com/WordPress/gutenberg/issues/34729.

**Comment by talldan** [comment]
Here's an issue: https://github.com/WordPress/gutenberg/issues/38172

**Comment by noisysocks** [comment]
Committed in https://core.trac.wordpress.org/changeset/52624 and https://core.trac.wordpress.org/changeset/52625.

**Pull request closed without merging**
