### PR TITLE
Help/About: Update the About page for 6.7

### PR DESCRIPTION
**Pull request by ryelle**
This PR introduces the new content for the 6.7 About page. This release, the layout is staying the same as the previous release, so the changes here are only content updates. I've also removed the images for now (there are some proposed in the ticket but I don't think they're final). The SVG icons have are also now slightly larger.

@ndiego could you take a look at the screenshot here and just make sure I copied from the correct Figma artboard and there are no copy-paste issues? (feel free to tag someone else in)

about-page

Trac ticket: https://core.trac.wordpress.org/ticket/61961

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by ndiego** [comment]
The main section looks great, thanks @ryelle! The bottom section is a tad different in the [mockup](https://www.figma.com/design/7awIY9a3ZjBNf0WSmCPzQ2/6.7-Highlight-Grid%2C-Microsite%2C-About-Page?node-id=2046-10547&node-type=frame&t=eUj28xHRjlNdQMXe-0) (screenshot below).

image

The font in the "Learn more about WordPress 6.7" is slightly larger, and there are linked heading in the release notes and field guide sections.

**Comment by ryelle** [comment]
Yeah, it's been mocked up like that every release, but we've kept that section the same to reduce string changes - I think it's just an artifact of copying the previous mockup which was never updated. However, if changing it is a strong opinion this release I can do it.

**Comment by ryelle** [comment]
I've updated the final section:

Screenshot 2024-10-14 at 5 33 58 PM

**Comment by ryelle** [comment]
Committed in [r59234](https://core.trac.wordpress.org/changeset/59234/).

**Pull request closed without merging**
