### PR TITLE
Update the block theme folders to be templates and parts

### PR DESCRIPTION
**Pull request by youknowriad**
Backport the theme folders change from the Gutenberg plugin.

Trac ticket: https://core.trac.wordpress.org/ticket/54493

### CODE REVIEW

**Comment by ockham** [comment]
Gutenberg counterpart PR: https://github.com/WordPress/gutenberg/pull/36647

**Comment by ockham** [comment]
This LGTM. Unfortunately, I can't currently test manually (some issue with MySQL in my local dev setup, probably yet another collision with my GB dev setup 🙄 ).

Instead, I've tested these changes on top of #1920 (by running unit tests), and they're unfortunately failing 😕 

```
There were 3 failures:

1) Block_Template_Test::test_child_theme_block_template_takes_precedence_over_equally_specific_parent_theme_php_template
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/var/www/src/wp-includes/template-canvas.php'
+'/var/www/tests/phpunit/includes/../data/themedir1/block-theme/page-1.php'

/var/www/tests/phpunit/tests/block-template.php:153

2) Block_Template_Test::test_custom_page_block_template_takes_precedence_over_all_other_templates
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'Content'
+'<!-- wp:paragraph -->
+<p>Page Template</p>
+<!-- /wp:paragraph -->'

/var/www/tests/phpunit/tests/block-template.php:193
```

Would it make sense to get #1920 in first for added confidence?

**Review by ockham — APPROVED** [review]
Looking good! Thanks Riad 👍

**Comment by youknowriad** [comment]
committed in https://core.trac.wordpress.org/changeset/52247

**Pull request closed without merging**
