### PR TITLE
Rename variables used in wpautop and related tests.

### PR DESCRIPTION
**Pull request by ironprogrammer**
Updates phpunit test names to reflect variable name updates originally proposed by @ricomoorman and later amended by @peterwilsoncc via https://github.com/WordPress/wordpress-develop/pull/2215.

This change is in conjunction with the above PR submitted by @peterwilsoncc.

See https://core.trac.wordpress.org/ticket/25615.

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by peterwilsoncc** [comment]
Thanks for catching these @ironprogrammer

**Comment by ironprogrammer** [comment]
Merged in @peterwilsoncc's branch so we have a single PR to work from.

**Comment by peterwilsoncc** [comment]
> Merged in @peterwilsoncc's branch so we have a single PR to work from.

Thanks Brian, I've closed my PR in favour of this one. I've also renamed this PR to indicate it now covers both the source code and related tests.

**Comment by hellofromtonya** [comment]
The PR looks good to me. But I have a thought.

In the Trac ticket, several folks voiced concerns about preserving developer humor and personality. The code was written originally in this concept, i.e. to be funny. What if a comment is added in the docblock that points folks to a link of the previous version? 

Why? To serve as a bridge across all concerns voices for and against the pee pee version.

@peterwilsoncc @ironprogrammer what do you think?

**Review by hellofromtonya — APPROVED** [review]
LGTM 👍

**Comment by peterwilsoncc** [comment]
> What if a comment is added in the docblock that points folks to a link of the previous version?
> 
> Why? To serve as a bridge across all concerns voices for and against the pee pee version.

I don't think there needs to be a link.

The concerns about developer facing humour were from a different era of WP so I think it's safe to assume the attitudes of the past may have been valid at the time but it's no longer the case.

**Comment by hellofromtonya** [comment]
Cool. Thanks @peterwilsoncc. With that, this PR is ready for commit.

**Comment by hellofromtonya** [comment]
Committed via https://core.trac.wordpress.org/changeset/52789.

**Pull request closed without merging**
