### PR TITLE
Upgrade/Install: Delay automatic updates after installation.

### PR DESCRIPTION
**Pull request by costdev**
**Note:**
**The changes in this PR cannot be tested in a `wordpress-develop` checkout because automatic updates do not run in version-controlled systems. Download 6.6 Beta X, then paste these changes in place before attempting to install the site.**

**Alternatively, if you have permissions for this repo, download the build artifact from the bottom of [this page](https://github.com/WordPress/wordpress-develop/actions/runs/9525415794).**

---

After installation, the user is directed to the `Log In` page. This triggers the `wp_schedule_update_checks()` function which is hooked to `init`. As a result, the user may be presented with a maintenance mode screen just after installing WordPress.

To improve the user experience, this delays Core updates by 1 hour, plugin updates by 1.5 hours, and theme updates by 2 hours.

Trac ticket: https://core.trac.wordpress.org/ticket/61457

### CODE REVIEW

**Review by peterwilsoncc — COMMENTED** [review]
I tested this on WordPress-Develop by adding `add_filter( 'automatic_updates_is_vcs_checkout', '__return_false' );` as an mu-plugin.

On trunk I was immediately presented with a maintenance mode screen, on this branch I was able to login immediately.

I think this change makes sense but it was my suggestion so of course I do. It would be good to get a few others to express an opinion too.

My one question is why the scheduling is being modified in `wp_install()` rather than in `wp_schedule_update_checks()`?

**Comment by costdev** [comment]
> My one question is why the scheduling is being modified in `wp_install()` rather than in `wp_schedule_update_checks()`?

The main reason is context. The normal scheduling of `wp_schedule_update_checks()` isn't a problem for other calls to the function (extender calls included). The issue arises when it runs on the next `do_action( 'init' );` call after installation. By having `wp_install()` set appropriate scheduling for post-installation, this ensures there is only a delay in that context.

An additional but related reason is that other calls to `wp_schedule_update_checks()` expect those actions to be scheduled for an instant run when no existing event exists. Changing the scheduling inside the function would break expectations when it's unnecessary to do so.

@hellofromtonya @desrosj @audrasjb @johnbillion Are any of you available to add your thoughts on this PR? I'd like to land this ahead of 6.6 Beta 3 tomorrow as the final planned Beta of the 6.6 cycle. Thanks!

**Comment by hellofromtonya** [comment]
## Test Report

## Env

* macOS
* PHP 8.3
* nginx
* 6.6 Beta 2
* Firefox
* Single site

## Test Steps

1. I added a `wp-content/mu-plugins.test.php` file with this code in it:
```php
<?php

add_filter( 'automatic_updates_is_vcs_checkout', '__return_false' );
```
2. Then reset the database using WP-CLI:
```
wp db reset --yes
```
3. Walked through the install screens.
4. Clicked the Login link. Expect: Should be redirected to the Login screen.

## Actual Results

Without this patch, able to reproduce the issue:
❌ got maintenance mode after clicking the Login link. 

With this patch, ✅ was redirected to the Login screen.

This PR resolves the issue ✅

**Review by hellofromtonya — APPROVED** [review]
As noted in [my test report](https://github.com/WordPress/wordpress-develop/pull/6828#issuecomment-2174054957), this patch resolves the issue.

I agree with @costdev to include the changes in `wp_install()` function ([see his reasoning here](https://github.com/WordPress/wordpress-develop/pull/6828#issuecomment-2172701559)).

This change LGTM for `commit`.

**Review by peterwilsoncc — APPROVED** [review]
@costdev @hellofromtonya Thanks, that works for me.

**Comment by dd32** [comment]
> > My one question is why the scheduling is being modified in `wp_install()` rather than in `wp_schedule_update_checks()`?
>
> An additional but related reason is that other calls to `wp_schedule_update_checks()` expect those actions to be scheduled for an instant run when no existing event exists. Changing the scheduling inside the function would break expectations when it's unnecessary to do so.

Personally, I don't think there's a realistic expectation of that, and scheduling it at `time()` is purely the default value that most choose to use as the starting point for cron tasks.

I don't feel strongly about this though, but I do feel it would be cleaner than the PR.

**Comment by costdev** [comment]
@dd32 I see your point, and though the code changes would be cleaner if only modifying `wp_schedule_update_checks()` directly, it's possible that this could have unintended consequences.

For example, code that clears the cron schedule for automatic updates, then runs `wp_schedule_update_checks()` for a one-line call to start automatic updates checks immediately. Should further functionality and/or behaviour expect that to be immediate, we don't know the potential impact a delay for all use cases could have.

Given that this is possible, it's a risk I don't feel is worth taking to resolve the issue in the ticket, which is specifically in a post-installation context.

**Comment by peterwilsoncc** [comment]
I chatted to Colin a bit further about when to delay/offset the cron jobs.

Given that the release is in beta, we think it might be best to reevaluate whether the offset can be added in the original location post release. That will allow for further work looking in to the situation described above and a considered decision about any implications.

**Comment by costdev** [comment]
@dd32 Are you happy for us to commit this PR's changes for 6.6 Beta 3 and look at whether to change this to the `wp_schedule_updates_checks()` function in a later release?

**Comment by hellofromtonya** [comment]
>Given that the release is in beta, we think it might be best to reevaluate whether the offset can be added in the original location post release. That will allow for further work looking in to the situation described above and a considered decision about any implications.

Good plan. 

* Get the fix as is committed in time for the last scheduled beta release (which is in a few hours - 16 UTC).
* Then evaluate if there are "unintended consequences" for changing `wp_schedule_update_checks()` in the "post-installation context."

**Review by hellofromtonya — APPROVED** [review]
Still LGTM for 6.6 Beta 3 commit as it resolves the reported issue in the "post-installation context."

Plus, [there's a plan to evaluate](https://github.com/WordPress/wordpress-develop/pull/6828#issuecomment-2175776304) "unintended consequences" concerns of changing in `wp_schedule_update_checks()` in this context.

**Comment by costdev** [comment]
Committed in [r58435](https://core.trac.wordpress.org/changeset/58435).

**Pull request closed without merging**
