### PR TITLE
Help: update overview texts to use `Update` to describe a button label

### PR DESCRIPTION
**Pull request by kebbet**
https://core.trac.wordpress.org/ticket/57608

### CODE REVIEW

**Comment by kebbet** [comment]
Before:
bild


After:
bild

**Review by costdev — APPROVED** [review]
Thanks for the PR @kebbet! LGTM 👍

**Comment by kebbet** [comment]
See the ticket for context of the latest commit.

The screen after latest patch:
bild

**Review by costdev — APPROVED** [review]
Thanks for the further updates @kebbet! LGTM :+1:

**Comment by audrasjb** [comment]
committed in https://core.trac.wordpress.org/changeset/55195

**Pull request closed without merging**
