### PR TITLE
Enhance code quality related to `WP_Theme_JSON::append_to_selector()` calls by introducing `prepend_to_selector()`

### PR DESCRIPTION
**Pull request by felixarntz**
Backport of https://github.com/WordPress/gutenberg/pull/50266

Trac ticket: https://core.trac.wordpress.org/ticket/58193

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by oandregal** [comment]
Hi Felix, would you be able to send this PR to Gutenberg? That's where the source of truth for this code lives.

This makes sense from a "code wise" perspective to me. It'd be good to engage the original authors/reviewers for help as well, so the pattern is more widely shared.

**Comment by felixarntz** [comment]
@oandregal Makes sense. I just opened https://github.com/WordPress/gutenberg/pull/50266 :)

**Comment by felixarntz** [comment]
Closing this in favor of https://github.com/WordPress/gutenberg/pull/50266

**Comment by tellthemachines** [comment]
Hi! I see the respective change in Gutenberg has been merged, but unless I'm mistaken this PR will still be needed to make the update in core? Shall we reopen it?

**Comment by felixarntz** [comment]
Thanks @tellthemachines, good point. I thought this was gonna be backported together with #4412, but I've reopened this PR and updated it against `trunk` as well as the minor changes in order to match the Gutenberg implementation that was merged.

**Review by spacedmonkey — APPROVED** [review]

**Comment by felixarntz** [comment]
Committed in https://core.trac.wordpress.org/changeset/55950.

**Pull request closed without merging**
