### PR TITLE
Disable lazy loading term meta get_block_templates.

### PR DESCRIPTION
**Pull request by spacedmonkey**
Trac ticket: https://core.trac.wordpress.org/ticket/58230#ticket

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by oandregal** [comment]
Added Andrei as reviewer. If the original reviewers can be tagged in wordpress-develop, I suggest adding them here, as they know best about the changes. It also helps the review load to be distributed among everyone.

Code-wise the changes are the same from the original PR. There are no test instructions in any place I've checked (here, trac ticket, or the original PR), so I don't know what I should test or what I need to look at. I'll leave space for others to comment here (happy to help if test instructions are provided).

**Comment by spacedmonkey** [comment]
@oandregal As this is a performance improvement, there is no functional change. So that is not to test other than if the code make sense. Do feel free to run benchmarks against this change.

**Review by westonruter — APPROVED** [review]
LGTM.

Original PR, merged as part of Gutenberg 15.2: https://github.com/WordPress/gutenberg/pull/47999

**Comment by spacedmonkey** [comment]
https://github.com/WordPress/wordpress-develop/commit/e4e3bb397e4c92907dc7a9878fef57a5a9ccd4cc

**Pull request closed without merging**
