### PR TITLE
Fix test broken test. 

### PR DESCRIPTION
**Pull request by spacedmonkey**
Fix broken test and uncomment it out. 

Trac ticket:  https://core.trac.wordpress.org/ticket/55593

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by SergeyBiryukov** [comment]
This works for me, thanks!

* Could we use the same approach in the `update_post_thumbnail_cache()` test above? That one also fails for me locally, though not on GitHub for some reason.
* I think `$primed_posts_found` or `$primed_ids_found` would be more appropriate than `$primed_query_found`, as we're not searching for a query here.
* I was wondering if we could use something like this instead of the whole `MockAction` approach:
  ```
  // Verify that all $parent_ids are cached.
  $this->assertEmpty( array_diff( $parent_ids, _get_non_cached_ids( $parent_ids, 'posts' ) ) );
  ```
  Seems like a more straightforward way to check.

**Comment by SergeyBiryukov** [comment]
> I was wondering if we could use something like this instead of the whole `MockAction` approach:
>   ```
>   // Verify that all $parent_ids are cached.
>   $this->assertEmpty( array_diff( $parent_ids, _get_non_cached_ids( $parent_ids, 'posts' ) ) );
>   ```
>   Seems like a more straightforward way to check.

Sorry, I think I meant something like this:
```
$cached_ids = array_keys( array_filter( wp_cache_get_multiple( $parent_ids, 'posts' ) ) );
$this->assertSameSets( $parent_ids, $cached_ids );
```
But that doesn't seem to work in my testing.

**Comment by spacedmonkey** [comment]
@SergeyBiryukov I worked out the root cause of the issue and pushed a fix.

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by SergeyBiryukov** [comment]
Ah, that also works. Looks good 👍

**Comment by spacedmonkey** [comment]
Committed.

**Pull request closed without merging**
