### PR TITLE
Dependencies: Set prefer-dedupe true in npm configuration

### PR DESCRIPTION
**Pull request by sirreal**
This change was applied in Gutenberg:

https://github.com/WordPress/gutenberg/pull/61630

Quoting that PR:

> The `npm dedupe` command searches
> and attempts to simplify the overall structure of the local package
> tree to allow dependent packages to be shared more effectively. As
> detailed in #61532, reducing the amount of dependency duplication is
> beneficial for a few reasons:
>
> - Fewer packages overall.
> - Faster installation.
> - Less size to transfer and store on disk.
> - Usually bundle size is reduced (although this depends on which
>   versions of packages are used).
>
> However, unless the command is run regularly, the project's dependency
> tree easily falls out of order.

See https://docs.npmjs.com/cli/v10/commands/npm-dedupe

Trac ticket: https://core.trac.wordpress.org/ticket/62190

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by sirreal** [comment]
I've created another PR that performs `npm dedupe`: https://github.com/WordPress/wordpress-develop/pull/7538

**Comment by desrosj** [comment]
Let's merge this change into #7538. I think it's fine to handle in the same commit!

**Comment by sirreal** [comment]
Sounds good, now that #7526 has landed there shouldn't be any conflicts 👍

**Comment by sirreal** [comment]
Superseded by #7538.

**Pull request closed without merging**
