### PR TITLE
Upgrade to Requests 2.0.0

### PR DESCRIPTION
**Pull request by jrfnl**
### Upgrade references to the Requests library in the WP code 

Trac ticket: https://core.trac.wordpress.org/ticket/54504

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by jrfnl** [comment]
Rebased and updated to test the latest changes in the Requests library.

**Comment by jrfnl** [comment]
Marked as ready for review and updated with the final Requests 2.0.0 code.

**Review by SergeyBiryukov — APPROVED** [review]

**Comment by jrfnl** [comment]
Closing as committed via changeset [52244](https://core.trac.wordpress.org/changeset/52244).

**Comment by jrfnl** [comment]
Re-opening as the commit was reverted.

**Comment by peterwilsoncc** [comment]
This has got a merge conflict and and older version of Requests. 

@jrfnl:
* do you still wish to get the requests bump in WP 6.0? 
* if so, which version? I saw there was a release in the last 24 hours or so.

The trac ticket for upgrade is tagged `early`, and the beta is two weeks away so it would be good to see something soonish.

Mainly for my own notes: for the purposes of testing this is a randomly selected [before zip file](https://github.com/WordPress/WordPress/archive/1c07680a7a2f7c54e9f8c72f19ea278644a3cec0.zip).

**Comment by peterwilsoncc** [comment]
Sorry @jrfnl, I just noticed there isn't a patch for https://core.trac.wordpress.org/ticket/54582 yet, you may wish to hold of on decisions until that goes through.

**Comment by jrfnl** [comment]
> This has got a merge conflict and and older version of Requests.
> 
> @jrfnl:
> 
>     * do you still wish to get the requests bump in WP 6.0?
>     * if so, which version? I saw there was a release in the last 24 hours or so.
> 
> The trac ticket for upgrade is tagged `early`, and the beta is two weeks away so it would be good to see something soonish.
> 
> Mainly for my own notes: for the purposes of testing this is a randomly selected [before zip file](https://github.com/WordPress/WordPress/archive/1c07680a7a2f7c54e9f8c72f19ea278644a3cec0.zip).

> Sorry @jrfnl, I just noticed there isn't a patch for https://core.trac.wordpress.org/ticket/54582 yet, you may wish to hold of on decisions until that goes through.

@peterwilsoncc Thanks for the ping. As you already noticed, any patch to upgrade Requests to the 2.x series depends on [Trac #54582](https://core.trac.wordpress.org/ticket/54582) being fixed first.

Also be aware that this patch was created 7 months ago and will need more than just a rebase to fix merge conflicts.
* A new search will have to be done across the WP codebase to find all uses of the old Requests classes and replace them as new code referencing the old classes may have been introduced in the mean time.
* The Requests files will need an update to version 2.0.1 (or 2.0.2, though for the purposes of WP, 2.0.2 contains no changes from 2.0.1 other than the version number constant as the only difference is an updated certificate bundle and WP uses its own); or depending on when Trac#54582 is resolved, whatever the current version of Requests is by that time.

This patch can serve as a basis/inspiration for a new patch, but should by no means by regarded as a viable patch to go into Core as is, by now.

**Comment by hellofromtonya** [comment]
Closing this PR in favor of https://github.com/WordPress/wordpress-develop/pull/3732.

**Pull request closed without merging**
