### PR TITLE
Ticket/51519 - Remove use of jQuery ready()

### PR DESCRIPTION
**Pull request by pramodjodhani**
Replace jQuery ready() with the alternate syntax `$( function() {} )` because `ready()` has been deprecated. 

Trac ticket:https://core.trac.wordpress.org/ticket/51519

### CODE REVIEW

**Comment by Clorith** [comment]
Thank you for the PR, it does look like there's some accidentally included extra files related to PHP, namely the `src/wp-includes/assets/script-loader-packages.php` and `tests/phpunit/data/link-manager.zip`.

Would you be able to refresh your PR to not include these unrelated files?

**Comment by desrosj** [comment]
@pramodjodhani are you able to refresh the PR? Looks like there are now merge conflicts.

**Comment by pramodjodhani** [comment]
Hello @Clorith and @desrosj,

Sorry for the delay. Please can you check again?

**Comment by hellofromtonya** [comment]
Committed PR #1908 (see changeset https://core.trac.wordpress.org/changeset/52285) instead of this PR. Why? It includes the non-vendor changes + additional fixes for other instances.

**Pull request closed without merging**
