### PR TITLE
Replace "Full site editing" with "Site Editor"

### PR DESCRIPTION
**Pull request by audrasjb**
https://core.trac.wordpress.org/ticket/57026

### CODE REVIEW

**Review by peterwilsoncc — APPROVED** [review]
This matches what I see searching for `site edit`, `full site` and `\bfse\b` (regex).

**Comment by carolinan** [comment]
Looks good to me.

-For the theme tag it would be good to create an alias and not only change the label, so that theme developers can use the shorter term. 
This also needs to be updated in the api.

**Review by krupal-panchal — APPROVED** [review]
LGTM

**Comment by audrasjb** [comment]
Good point @carolinan :)
Let's commit this change first so it's ready to ship with 6.1.1 if it's possible.
Then I'll open a Meta Trac ticket to ask for a change in WordPress.org, then we can open a new ticket to change the tag accordingly :)

**Comment by audrasjb** [comment]
Committed in https://core.trac.wordpress.org/changeset/54786

**Pull request closed without merging**
