### PR TITLE
Editor: Sync changes from the Gutenberg plugin for WordPress 6.0.2 RC

### PR DESCRIPTION
**Pull request by gziolo**
Trac ticket: https://core.trac.wordpress.org/ticket/56414

---
**This Pull Request is for code review only. Please keep all other discussion in the Trac ticket. Do not merge this Pull Request. See [GitHub Pull Requests for Code Review](https://make.wordpress.org/core/handbook/contribute/git/github-pull-requests-for-code-review/) in the Core Handbook for more details.**

### CODE REVIEW

**Comment by gziolo** [comment]
That should be it as for code changes required. I still run local testing. I wanted to run CI jobs in parallel.

**Comment by gziolo** [comment]
Tested PRs:

https://github.com/WordPress/gutenberg/pull/42975

Screenshot 2022-08-23 at 17 24 14

https://github.com/WordPress/gutenberg/pull/41101

Screenshot 2022-08-23 at 17 26 20
Screenshot 2022-08-23 at 17 26 39

**Review by SergeyBiryukov — APPROVED** [review]
Thanks for the PR, looks good to me 🙂 👍

**Comment by gziolo** [comment]
Committed with https://core.trac.wordpress.org/changeset/53929.

**Pull request closed without merging**
